
?
)ru.ad#holiday@group.v.calendar.google.comАндорраAD
7
)ru.ae#holiday@group.v.calendar.google.comОАЭAE
E
)ru.af#holiday@group.v.calendar.google.comАфганистанAF
?
)ru.al#holiday@group.v.calendar.google.comАлбанияAL
?
)ru.am#holiday@group.v.calendar.google.comАрменияAM
=
)ru.ao#holiday@group.v.calendar.google.comАнголаAO
C
)ru.ar#holiday@group.v.calendar.google.comАргентинаAR
E
/ru.austrian#holiday@group.v.calendar.google.comАвстрияAT
K
1ru.australian#holiday@group.v.calendar.google.comАвстралияAU
;
)ru.aw#holiday@group.v.calendar.google.com
АрубаAW
G
)ru.az#holiday@group.v.calendar.google.comАзербайджанAZ
W
)ru.ba#holiday@group.v.calendar.google.com&Босния и ГерцеговинаBA
A
)ru.bb#holiday@group.v.calendar.google.comБарбадосBB
C
)ru.bd#holiday@group.v.calendar.google.comБангладешBD
?
)ru.be#holiday@group.v.calendar.google.comБельгияBE
H
)ru.bf#holiday@group.v.calendar.google.comБуркина-ФасоBF
H
0ru.bulgarian#holiday@group.v.calendar.google.comБолгарияBG
?
)ru.bh#holiday@group.v.calendar.google.comБахрейнBH
?
)ru.bi#holiday@group.v.calendar.google.comБурундиBI
;
)ru.bj#holiday@group.v.calendar.google.com
БенинBJ
?
)ru.bm#holiday@group.v.calendar.google.comБермудыBM
?
)ru.bo#holiday@group.v.calendar.google.comБоливияBO
H
0ru.brazilian#holiday@group.v.calendar.google.comБразилияBR
=
)ru.bs#holiday@group.v.calendar.google.comБагамыBS
A
)ru.bw#holiday@group.v.calendar.google.comБотсванаBW
A
)ru.by#holiday@group.v.calendar.google.comБеларусьBY
C
/ru.canadian#holiday@group.v.calendar.google.comКанадаCA
L
)ru.cd#holiday@group.v.calendar.google.comКонго - КиншасаCD
7
)ru.cf#holiday@group.v.calendar.google.comЦАРCF
R
)ru.cg#holiday@group.v.calendar.google.com!Конго - БраззавильCG
C
)ru.ch#holiday@group.v.calendar.google.comШвейцарияCH
G
)ru.ci#holiday@group.v.calendar.google.comКот-д’ИвуарCI
9
)ru.cl#holiday@group.v.calendar.google.comЧилиCL
?
)ru.cm#holiday@group.v.calendar.google.comКамерунCM
>
,ru.china#holiday@group.v.calendar.google.com
КитайCN
A
)ru.co#holiday@group.v.calendar.google.comКолумбияCO
D
)ru.cr#holiday@group.v.calendar.google.comКоста-РикаCR
9
)ru.cu#holiday@group.v.calendar.google.comКубаCU
D
)ru.cv#holiday@group.v.calendar.google.comКабо-ВердеCV
9
)ru.cy#holiday@group.v.calendar.google.comКипрCY
>
,ru.czech#holiday@group.v.calendar.google.com
ЧехияCZ
E
-ru.german#holiday@group.v.calendar.google.comГерманияDE
?
-ru.danish#holiday@group.v.calendar.google.com
ДанияDK
`
)ru.do#holiday@group.v.calendar.google.com/Доминиканская РеспубликаDO
;
)ru.dz#holiday@group.v.calendar.google.com
АлжирDZ
?
)ru.ec#holiday@group.v.calendar.google.comЭквадорEC
?
)ru.ee#holiday@group.v.calendar.google.comЭстонияEE
=
)ru.eg#holiday@group.v.calendar.google.comЕгипетEG
?
)ru.er#holiday@group.v.calendar.google.comЭритреяER
B
,ru.spain#holiday@group.v.calendar.google.comИспанияES
?
)ru.et#holiday@group.v.calendar.google.comЭфиопияET
H
.ru.finnish#holiday@group.v.calendar.google.comФинляндияFI
;
)ru.fj#holiday@group.v.calendar.google.com
ФиджиFJ
K
)ru.fo#holiday@group.v.calendar.google.comФарерские о-ваFO
C
-ru.french#holiday@group.v.calendar.google.comФранцияFR
;
)ru.ga#holiday@group.v.calendar.google.com
ГабонGA
M
)ru.uk#holiday@group.v.calendar.google.comВеликобританияGB
?
)ru.gd#holiday@group.v.calendar.google.comГренадаGD
=
)ru.ge#holiday@group.v.calendar.google.comГрузияGE
9
)ru.gh#holiday@group.v.calendar.google.comГанаGH
C
)ru.gi#holiday@group.v.calendar.google.comГибралтарGI
E
)ru.gl#holiday@group.v.calendar.google.comГренландияGL
=
)ru.gm#holiday@group.v.calendar.google.comГамбияGM
=
)ru.gn#holiday@group.v.calendar.google.comГвинеяGN
Z
)ru.gq#holiday@group.v.calendar.google.com)Экваториальная ГвинеяGQ
@
,ru.greek#holiday@group.v.calendar.google.comГрецияGR
C
)ru.gt#holiday@group.v.calendar.google.comГватемалаGT
9
)ru.gu#holiday@group.v.calendar.google.comГуамGU
H
)ru.gw#holiday@group.v.calendar.google.comГвинея-БисауGW
F
0ru.hong_kong#holiday@group.v.calendar.google.comГонконгHK
A
)ru.hn#holiday@group.v.calendar.google.comГондурасHN
G
/ru.croatian#holiday@group.v.calendar.google.comХорватияHR
;
)ru.ht#holiday@group.v.calendar.google.com
ГаитиHT
F
0ru.hungarian#holiday@group.v.calendar.google.comВенгрияHU
K
1ru.indonesian#holiday@group.v.calendar.google.comИндонезияID
D
,ru.irish#holiday@group.v.calendar.google.comИрландияIE
C
-ru.jewish#holiday@group.v.calendar.google.comИзраильIL
?
-ru.indian#holiday@group.v.calendar.google.com
ИндияIN
9
)ru.iq#holiday@group.v.calendar.google.comИракIQ
9
)ru.ir#holiday@group.v.calendar.google.comИранIR
A
)ru.is#holiday@group.v.calendar.google.comИсландияIS
B
.ru.italian#holiday@group.v.calendar.google.comИталияIT
=
)ru.jm#holiday@group.v.calendar.google.comЯмайкаJM
A
)ru.jo#holiday@group.v.calendar.google.comИорданияJO
C
/ru.japanese#holiday@group.v.calendar.google.comЯпонияJP
;
)ru.ke#holiday@group.v.calendar.google.com
КенияKE
A
)ru.kg#holiday@group.v.calendar.google.comКиргизияKG
A
)ru.kh#holiday@group.v.calendar.google.comКамбоджаKH
=
)ru.km#holiday@group.v.calendar.google.comКоморыKM
9
)ru.kp#holiday@group.v.calendar.google.comКНДРKP
Y
2ru.south_korea#holiday@group.v.calendar.google.comРеспублика КореяKR
=
)ru.kw#holiday@group.v.calendar.google.comКувейтKW
K
)ru.ky#holiday@group.v.calendar.google.comКаймановы о-ваKY
C
)ru.kz#holiday@group.v.calendar.google.comКазахстанKZ
;
)ru.lb#holiday@group.v.calendar.google.com
ЛиванLB
G
)ru.li#holiday@group.v.calendar.google.comЛихтенштейнLI
B
)ru.lk#holiday@group.v.calendar.google.comШри-ЛанкаLK
?
)ru.lr#holiday@group.v.calendar.google.comЛиберияLR
=
)ru.ls#holiday@group.v.calendar.google.comЛесотоLS
C
1ru.lithuanian#holiday@group.v.calendar.google.com
ЛитваLT
E
)ru.lu#holiday@group.v.calendar.google.comЛюксембургLU
B
.ru.latvian#holiday@group.v.calendar.google.comЛатвияLV
;
)ru.ly#holiday@group.v.calendar.google.com
ЛивияLY
?
)ru.ma#holiday@group.v.calendar.google.comМароккоMA
=
)ru.mc#holiday@group.v.calendar.google.comМонакоMC
?
)ru.md#holiday@group.v.calendar.google.comМолдоваMD
E
)ru.me#holiday@group.v.calendar.google.comЧерногорияME
E
)ru.mg#holiday@group.v.calendar.google.comМадагаскарMG
C
)ru.mk#holiday@group.v.calendar.google.comМакедонияMK
9
)ru.ml#holiday@group.v.calendar.google.comМалиML
A
)ru.mn#holiday@group.v.calendar.google.comМонголияMN
;
)ru.mo#holiday@group.v.calendar.google.com
МакаоMO
C
)ru.mq#holiday@group.v.calendar.google.comМартиникаMQ
=
)ru.mt#holiday@group.v.calendar.google.comМальтаMT
A
)ru.mu#holiday@group.v.calendar.google.comМаврикийMU
=
)ru.mw#holiday@group.v.calendar.google.comМалавиMW
D
.ru.mexican#holiday@group.v.calendar.google.comМексикаMX
G
/ru.malaysia#holiday@group.v.calendar.google.comМалайзияMY
A
)ru.mz#holiday@group.v.calendar.google.comМозамбикMZ
?
)ru.na#holiday@group.v.calendar.google.comНамибияNA
;
)ru.ne#holiday@group.v.calendar.google.com
НигерNE
?
)ru.ng#holiday@group.v.calendar.google.comНигерияNG
C
)ru.ni#holiday@group.v.calendar.google.comНикарагуаNI
H
,ru.dutch#holiday@group.v.calendar.google.comНидерландыNL
H
0ru.norwegian#holiday@group.v.calendar.google.comНорвегияNO
;
)ru.np#holiday@group.v.calendar.google.com
НепалNP
U
2ru.new_zealand#holiday@group.v.calendar.google.comНовая ЗеландияNZ
9
)ru.om#holiday@group.v.calendar.google.comОманOM
=
)ru.pa#holiday@group.v.calendar.google.comПанамаPA
9
)ru.pe#holiday@group.v.calendar.google.comПеруPE
L
2ru.philippines#holiday@group.v.calendar.google.comФилиппиныPH
A
)ru.pk#holiday@group.v.calendar.google.comПакистанPK
A
-ru.polish#holiday@group.v.calendar.google.comПольшаPL
F
)ru.pr#holiday@group.v.calendar.google.comПуэрто-РикоPR
M
1ru.portuguese#holiday@group.v.calendar.google.comПортугалияPT
A
)ru.py#holiday@group.v.calendar.google.comПарагвайPY
;
)ru.qa#holiday@group.v.calendar.google.com
КатарQA
?
)ru.re#holiday@group.v.calendar.google.comРеюньонRE
E
/ru.romanian#holiday@group.v.calendar.google.comРумынияRO
=
)ru.rs#holiday@group.v.calendar.google.comСербияRS
B
.ru.russian#holiday@group.v.calendar.google.comРоссияRU
=
)ru.rw#holiday@group.v.calendar.google.comРуандаRW
\
3ru.saudiarabian#holiday@group.v.calendar.google.com!Саудовская АравияSA
V
)ru.sc#holiday@group.v.calendar.google.com%Сейшельские ОстроваSC
;
)ru.sd#holiday@group.v.calendar.google.com
СуданSD
B
.ru.swedish#holiday@group.v.calendar.google.comШвецияSE
H
0ru.singapore#holiday@group.v.calendar.google.comСингапурSG
G
)ru.sh#holiday@group.v.calendar.google.comо-в Св. ЕленыSH
H
0ru.slovenian#holiday@group.v.calendar.google.comСловенияSI
E
-ru.slovak#holiday@group.v.calendar.google.comСловакияSK
H
)ru.sl#holiday@group.v.calendar.google.comСьерра-ЛеонеSL
D
)ru.sm#holiday@group.v.calendar.google.comСан-МариноSM
?
)ru.sn#holiday@group.v.calendar.google.comСенегалSN
=
)ru.so#holiday@group.v.calendar.google.comСомалиSO
?
)ru.sr#holiday@group.v.calendar.google.comСуринамSR
F
)ru.ss#holiday@group.v.calendar.google.comЮжный СуданSS
T
)ru.st#holiday@group.v.calendar.google.com#Сан-Томе и ПринсипиST
C
)ru.sv#holiday@group.v.calendar.google.comСальвадорSV
;
)ru.sy#holiday@group.v.calendar.google.com
СирияSY
C
)ru.sz#holiday@group.v.calendar.google.comСвазилендSZ
7
)ru.td#holiday@group.v.calendar.google.comЧадTD
9
)ru.tg#holiday@group.v.calendar.google.comТогоTG
?
)ru.th#holiday@group.v.calendar.google.comТаиландTH
;
)ru.tn#holiday@group.v.calendar.google.com
ТунисTN
B
.ru.turkish#holiday@group.v.calendar.google.comТурцияTR
Q
)ru.tt#holiday@group.v.calendar.google.com Тринидад и ТобагоTT
C
-ru.taiwan#holiday@group.v.calendar.google.comТайваньTW
A
)ru.tz#holiday@group.v.calendar.google.comТанзанияTZ
F
0ru.ukrainian#holiday@group.v.calendar.google.comУкраинаUA
=
)ru.ug#holiday@group.v.calendar.google.comУгандаUG
S
*ru.usa#holiday@group.v.calendar.google.com!Соединенные ШтатыUS
?
)ru.uy#holiday@group.v.calendar.google.comУругвайUY
E
)ru.uz#holiday@group.v.calendar.google.comУзбекистанUZ
?
)ru.va#holiday@group.v.calendar.google.comВатиканVA
C
)ru.ve#holiday@group.v.calendar.google.comВенесуэлаVE
V
)ru.vi#holiday@group.v.calendar.google.com%Виргинские о-ва (США)VI
G
1ru.vietnamese#holiday@group.v.calendar.google.comВьетнамVN
;
)ru.ye#holiday@group.v.calendar.google.com
ЙеменYE
?
)ru.yt#holiday@group.v.calendar.google.comМайоттаYT
7
)ru.sa#holiday@group.v.calendar.google.comЮАРZA
=
)ru.zm#holiday@group.v.calendar.google.comЗамбияZM
A
)ru.zw#holiday@group.v.calendar.google.comЗимбабвеZW_
0ru.christian#holiday@group.v.calendar.google.com+Христианские праздникиW
.ru.judaism#holiday@group.v.calendar.google.com%Еврейские праздники_
.ru.islamic#holiday@group.v.calendar.google.com-Мусульманские праздникиk
<ru.orthodox_christianity#holiday@group.v.calendar.google.com+Православные праздникиru