
=
)bg.ad#holiday@group.v.calendar.google.comАндораAD
c
)bg.ae#holiday@group.v.calendar.google.com2Обединени арабски емирстваAE
E
)bg.af#holiday@group.v.calendar.google.comАфганистанAF
?
)bg.al#holiday@group.v.calendar.google.comАлбанияAL
?
)bg.am#holiday@group.v.calendar.google.comАрменияAM
=
)bg.ao#holiday@group.v.calendar.google.comАнголаAO
C
)bg.ar#holiday@group.v.calendar.google.comАржентинаAR
E
/bg.austrian#holiday@group.v.calendar.google.comАвстрияAT
K
1bg.australian#holiday@group.v.calendar.google.comАвстралияAU
;
)bg.aw#holiday@group.v.calendar.google.com
АрубаAW
G
)bg.az#holiday@group.v.calendar.google.comАзербайджанAZ
U
)bg.ba#holiday@group.v.calendar.google.com$Босна и ХерцеговинаBA
A
)bg.bb#holiday@group.v.calendar.google.comБарбадосBB
C
)bg.bd#holiday@group.v.calendar.google.comБангладешBD
=
)bg.be#holiday@group.v.calendar.google.comБелгияBE
H
)bg.bf#holiday@group.v.calendar.google.comБуркина ФасоBF
H
0bg.bulgarian#holiday@group.v.calendar.google.comБългарияBG
?
)bg.bh#holiday@group.v.calendar.google.comБахрейнBH
?
)bg.bi#holiday@group.v.calendar.google.comБурундиBI
;
)bg.bj#holiday@group.v.calendar.google.com
БенинBJ
?
)bg.bm#holiday@group.v.calendar.google.comБермудаBM
?
)bg.bo#holiday@group.v.calendar.google.comБоливияBO
H
0bg.brazilian#holiday@group.v.calendar.google.comБразилияBR
=
)bg.bs#holiday@group.v.calendar.google.comБахамиBS
A
)bg.bw#holiday@group.v.calendar.google.comБотсванаBW
?
)bg.by#holiday@group.v.calendar.google.comБеларусBY
C
/bg.canadian#holiday@group.v.calendar.google.comКанадаCA
L
)bg.cd#holiday@group.v.calendar.google.comКонго (Киншаса)CD
j
)bg.cf#holiday@group.v.calendar.google.com9Централноафриканска републикаCF
N
)bg.cg#holiday@group.v.calendar.google.comКонго (Бразавил)CG
C
)bg.ch#holiday@group.v.calendar.google.comШвейцарияCH
G
)bg.ci#holiday@group.v.calendar.google.comКот д’ИвоарCI
9
)bg.cl#holiday@group.v.calendar.google.comЧилиCL
?
)bg.cm#holiday@group.v.calendar.google.comКамерунCM
>
,bg.china#holiday@group.v.calendar.google.com
КитайCN
A
)bg.co#holiday@group.v.calendar.google.comКолумбияCO
D
)bg.cr#holiday@group.v.calendar.google.comКоста РикаCR
9
)bg.cu#holiday@group.v.calendar.google.comКубаCU
D
)bg.cv#holiday@group.v.calendar.google.comКабо ВердеCV
;
)bg.cy#holiday@group.v.calendar.google.com
КипърCY
Q
,bg.czech#holiday@group.v.calendar.google.comЧешка републикаCZ
E
-bg.german#holiday@group.v.calendar.google.comГерманияDE
?
-bg.danish#holiday@group.v.calendar.google.com
ДанияDK
\
)bg.do#holiday@group.v.calendar.google.com+Доминиканска републикаDO
;
)bg.dz#holiday@group.v.calendar.google.com
АлжирDZ
?
)bg.ec#holiday@group.v.calendar.google.comЕквадорEC
?
)bg.ee#holiday@group.v.calendar.google.comЕстонияEE
=
)bg.eg#holiday@group.v.calendar.google.comЕгипетEG
?
)bg.er#holiday@group.v.calendar.google.comЕритреяER
B
,bg.spain#holiday@group.v.calendar.google.comИспанияES
?
)bg.et#holiday@group.v.calendar.google.comЕтиопияET
H
.bg.finnish#holiday@group.v.calendar.google.comФинландияFI
;
)bg.fj#holiday@group.v.calendar.google.com
ФиджиFJ
R
)bg.fo#holiday@group.v.calendar.google.com!Фарьорски островиFO
C
-bg.french#holiday@group.v.calendar.google.comФранцияFR
;
)bg.ga#holiday@group.v.calendar.google.com
ГабонGA
X
)bg.uk#holiday@group.v.calendar.google.com'Обединеното кралствоGB
?
)bg.gd#holiday@group.v.calendar.google.comГренадаGD
=
)bg.ge#holiday@group.v.calendar.google.comГрузияGE
9
)bg.gh#holiday@group.v.calendar.google.comГанаGH
C
)bg.gi#holiday@group.v.calendar.google.comГибралтарGI
E
)bg.gl#holiday@group.v.calendar.google.comГренландияGL
=
)bg.gm#holiday@group.v.calendar.google.comГамбияGM
=
)bg.gn#holiday@group.v.calendar.google.comГвинеяGN
V
)bg.gq#holiday@group.v.calendar.google.com%Екваториална ГвинеяGQ
@
,bg.greek#holiday@group.v.calendar.google.comГърцияGR
C
)bg.gt#holiday@group.v.calendar.google.comГватемалаGT
9
)bg.gu#holiday@group.v.calendar.google.comГуамGU
H
)bg.gw#holiday@group.v.calendar.google.comГвинея-БисауGW
F
0bg.hong_kong#holiday@group.v.calendar.google.comХонконгHK
A
)bg.hn#holiday@group.v.calendar.google.comХондурасHN
G
/bg.croatian#holiday@group.v.calendar.google.comХърватияHR
;
)bg.ht#holiday@group.v.calendar.google.com
ХаитиHT
F
0bg.hungarian#holiday@group.v.calendar.google.comУнгарияHU
K
1bg.indonesian#holiday@group.v.calendar.google.comИндонезияID
D
,bg.irish#holiday@group.v.calendar.google.comИрландияIE
A
-bg.jewish#holiday@group.v.calendar.google.comИзраелIL
?
-bg.indian#holiday@group.v.calendar.google.com
ИндияIN
9
)bg.iq#holiday@group.v.calendar.google.comИракIQ
9
)bg.ir#holiday@group.v.calendar.google.comИранIR
A
)bg.is#holiday@group.v.calendar.google.comИсландияIS
B
.bg.italian#holiday@group.v.calendar.google.comИталияIT
=
)bg.jm#holiday@group.v.calendar.google.comЯмайкаJM
A
)bg.jo#holiday@group.v.calendar.google.comЙорданияJO
C
/bg.japanese#holiday@group.v.calendar.google.comЯпонияJP
;
)bg.ke#holiday@group.v.calendar.google.com
КенияKE
E
)bg.kg#holiday@group.v.calendar.google.comКиргизстанKG
A
)bg.kh#holiday@group.v.calendar.google.comКамбоджаKH
P
)bg.km#holiday@group.v.calendar.google.comКоморски островиKM
J
)bg.kp#holiday@group.v.calendar.google.comСеверна КореяKP
M
2bg.south_korea#holiday@group.v.calendar.google.comЮжна КореяKR
=
)bg.kw#holiday@group.v.calendar.google.comКувейтKW
R
)bg.ky#holiday@group.v.calendar.google.com!Кайманови островиKY
C
)bg.kz#holiday@group.v.calendar.google.comКазахстанKZ
;
)bg.lb#holiday@group.v.calendar.google.com
ЛиванLB
E
)bg.li#holiday@group.v.calendar.google.comЛихтенщайнLI
B
)bg.lk#holiday@group.v.calendar.google.comШри ЛанкаLK
?
)bg.lr#holiday@group.v.calendar.google.comЛиберияLR
=
)bg.ls#holiday@group.v.calendar.google.comЛесотоLS
C
1bg.lithuanian#holiday@group.v.calendar.google.com
ЛитваLT
E
)bg.lu#holiday@group.v.calendar.google.comЛюксембургLU
B
.bg.latvian#holiday@group.v.calendar.google.comЛатвияLV
;
)bg.ly#holiday@group.v.calendar.google.com
ЛибияLY
=
)bg.ma#holiday@group.v.calendar.google.comМарокоMA
=
)bg.mc#holiday@group.v.calendar.google.comМонакоMC
?
)bg.md#holiday@group.v.calendar.google.comМолдоваMD
D
)bg.me#holiday@group.v.calendar.google.comЧерна гораME
E
)bg.mg#holiday@group.v.calendar.google.comМадагаскарMG
C
)bg.mk#holiday@group.v.calendar.google.comМакедонияMK
9
)bg.ml#holiday@group.v.calendar.google.comМалиML
A
)bg.mn#holiday@group.v.calendar.google.comМонголияMN
;
)bg.mo#holiday@group.v.calendar.google.com
МакаоMO
C
)bg.mq#holiday@group.v.calendar.google.comМартиникаMQ
;
)bg.mt#holiday@group.v.calendar.google.com
МалтаMT
A
)bg.mu#holiday@group.v.calendar.google.comМаврицийMU
=
)bg.mw#holiday@group.v.calendar.google.comМалавиMW
D
.bg.mexican#holiday@group.v.calendar.google.comМексикоMX
G
/bg.malaysia#holiday@group.v.calendar.google.comМалайзияMY
A
)bg.mz#holiday@group.v.calendar.google.comМозамбикMZ
?
)bg.na#holiday@group.v.calendar.google.comНамибияNA
;
)bg.ne#holiday@group.v.calendar.google.com
НигерNE
?
)bg.ng#holiday@group.v.calendar.google.comНигерияNG
C
)bg.ni#holiday@group.v.calendar.google.comНикарагуаNI
J
,bg.dutch#holiday@group.v.calendar.google.comНидерландияNL
H
0bg.norwegian#holiday@group.v.calendar.google.comНорвегияNO
;
)bg.np#holiday@group.v.calendar.google.com
НепалNP
S
2bg.new_zealand#holiday@group.v.calendar.google.comНова ЗеландияNZ
9
)bg.om#holiday@group.v.calendar.google.comОманOM
=
)bg.pa#holiday@group.v.calendar.google.comПанамаPA
9
)bg.pe#holiday@group.v.calendar.google.comПеруPE
J
2bg.philippines#holiday@group.v.calendar.google.comФилипиниPH
A
)bg.pk#holiday@group.v.calendar.google.comПакистанPK
?
-bg.polish#holiday@group.v.calendar.google.com
ПолшаPL
F
)bg.pr#holiday@group.v.calendar.google.comПуерто РикоPR
M
1bg.portuguese#holiday@group.v.calendar.google.comПортугалияPT
A
)bg.py#holiday@group.v.calendar.google.comПарагвайPY
;
)bg.qa#holiday@group.v.calendar.google.com
КатарQA
?
)bg.re#holiday@group.v.calendar.google.comРеюнионRE
E
/bg.romanian#holiday@group.v.calendar.google.comРумънияRO
=
)bg.rs#holiday@group.v.calendar.google.comСърбияRS
@
.bg.russian#holiday@group.v.calendar.google.com
РусияRU
=
)bg.rw#holiday@group.v.calendar.google.comРуандаRW
Z
3bg.saudiarabian#holiday@group.v.calendar.google.comСаудитска АрабияSA
?
)bg.sc#holiday@group.v.calendar.google.comСейшелиSC
;
)bg.sd#holiday@group.v.calendar.google.com
СуданSD
B
.bg.swedish#holiday@group.v.calendar.google.comШвецияSE
H
0bg.singapore#holiday@group.v.calendar.google.comСингапурSG
F
)bg.sh#holiday@group.v.calendar.google.comСвета ЕленаSH
H
0bg.slovenian#holiday@group.v.calendar.google.comСловенияSI
E
-bg.slovak#holiday@group.v.calendar.google.comСловакияSK
F
)bg.sl#holiday@group.v.calendar.google.comСиера ЛеонеSL
D
)bg.sm#holiday@group.v.calendar.google.comСан МариноSM
?
)bg.sn#holiday@group.v.calendar.google.comСенегалSN
?
)bg.so#holiday@group.v.calendar.google.comСомалияSO
?
)bg.sr#holiday@group.v.calendar.google.comСуринамSR
D
)bg.ss#holiday@group.v.calendar.google.comЮжен СуданSS
T
)bg.st#holiday@group.v.calendar.google.com#Сао Томе и ПринсипиST
A
)bg.sv#holiday@group.v.calendar.google.comСалвадорSV
;
)bg.sy#holiday@group.v.calendar.google.com
СирияSY
C
)bg.sz#holiday@group.v.calendar.google.comСвазилендSZ
7
)bg.td#holiday@group.v.calendar.google.comЧадTD
9
)bg.tg#holiday@group.v.calendar.google.comТогоTG
?
)bg.th#holiday@group.v.calendar.google.comТайландTH
;
)bg.tn#holiday@group.v.calendar.google.com
ТунисTN
B
.bg.turkish#holiday@group.v.calendar.google.comТурцияTR
Q
)bg.tt#holiday@group.v.calendar.google.com Тринидад и ТобагоTT
A
-bg.taiwan#holiday@group.v.calendar.google.comТайванTW
A
)bg.tz#holiday@group.v.calendar.google.comТанзанияTZ
F
0bg.ukrainian#holiday@group.v.calendar.google.comУкрайнаUA
=
)bg.ug#holiday@group.v.calendar.google.comУгандаUG
M
*bg.usa#holiday@group.v.calendar.google.comСъединени щатиUS
?
)bg.uy#holiday@group.v.calendar.google.comУругвайUY
E
)bg.uz#holiday@group.v.calendar.google.comУзбекистанUZ
?
)bg.va#holiday@group.v.calendar.google.comВатиканVA
C
)bg.ve#holiday@group.v.calendar.google.comВенецуелаVE
k
)bg.vi#holiday@group.v.calendar.google.com:Американски Вирджински островиVI
G
1bg.vietnamese#holiday@group.v.calendar.google.comВиетнамVN
;
)bg.ye#holiday@group.v.calendar.google.com
ЙеменYE
;
)bg.yt#holiday@group.v.calendar.google.com
МайотYT
F
)bg.sa#holiday@group.v.calendar.google.comЮжна АфрикаZA
=
)bg.zm#holiday@group.v.calendar.google.comЗамбияZM
A
)bg.zw#holiday@group.v.calendar.google.comЗимбабвеZW[
0bg.christian#holiday@group.v.calendar.google.com'Християнски празнициQ
.bg.judaism#holiday@group.v.calendar.google.comЮдейски празнициY
.bg.islamic#holiday@group.v.calendar.google.com'Мюсюлмански празнициg
<bg.orthodox_christianity#holiday@group.v.calendar.google.com'Православни празнициbg