
=
)fa.ad#holiday@group.v.calendar.google.comآندوراAD
S
)fa.ae#holiday@group.v.calendar.google.com"امارات متحدهٔ عربیAE
C
)fa.af#holiday@group.v.calendar.google.comافغانستانAF
=
)fa.al#holiday@group.v.calendar.google.comآلبانیAL
A
)fa.am#holiday@group.v.calendar.google.comارمنستانAM
=
)fa.ao#holiday@group.v.calendar.google.comآنگولاAO
A
)fa.ar#holiday@group.v.calendar.google.comآرژانتینAR
A
/fa.austrian#holiday@group.v.calendar.google.com
اتریشAT
I
1fa.australian#holiday@group.v.calendar.google.comاسترالیاAU
;
)fa.aw#holiday@group.v.calendar.google.com
آروباAW
P
)fa.az#holiday@group.v.calendar.google.comجمهوری آذربایجانAZ
M
)fa.ba#holiday@group.v.calendar.google.comبوسنی و هرزگوینBA
A
)fa.bb#holiday@group.v.calendar.google.comباربادوسBB
?
)fa.bd#holiday@group.v.calendar.google.comبنگلادشBD
;
)fa.be#holiday@group.v.calendar.google.com
بلژیکBE
G
)fa.bf#holiday@group.v.calendar.google.comبورکینافاسوBF
J
0fa.bulgarian#holiday@group.v.calendar.google.comبلغارستانBG
;
)fa.bh#holiday@group.v.calendar.google.com
بحرینBH
?
)fa.bi#holiday@group.v.calendar.google.comبوروندیBI
9
)fa.bj#holiday@group.v.calendar.google.comبنینBJ
=
)fa.bm#holiday@group.v.calendar.google.comبرموداBM
=
)fa.bo#holiday@group.v.calendar.google.comبولیویBO
B
0fa.brazilian#holiday@group.v.calendar.google.com
برزیلBR
=
)fa.bs#holiday@group.v.calendar.google.comباهاماBS
A
)fa.bw#holiday@group.v.calendar.google.comبوتسواناBW
=
)fa.by#holiday@group.v.calendar.google.comبلاروسBY
C
/fa.canadian#holiday@group.v.calendar.google.comکاناداCA
J
)fa.cd#holiday@group.v.calendar.google.comکنگو - کینشاساCD
W
)fa.cf#holiday@group.v.calendar.google.com&جمهوری افریقای مرکزیCF
J
)fa.cg#holiday@group.v.calendar.google.comکنگو - برازویلCG
;
)fa.ch#holiday@group.v.calendar.google.com
سوئیسCH
@
)fa.ci#holiday@group.v.calendar.google.comساحل عاجCI
9
)fa.cl#holiday@group.v.calendar.google.comشیلیCL
=
)fa.cm#holiday@group.v.calendar.google.comکامرونCM
:
,fa.china#holiday@group.v.calendar.google.comچینCN
=
)fa.co#holiday@group.v.calendar.google.comکلمبیاCO
C
)fa.cr#holiday@group.v.calendar.google.comکاستاریکاCR
9
)fa.cu#holiday@group.v.calendar.google.comکوباCU
@
)fa.cv#holiday@group.v.calendar.google.comکیپ‌وردCV
9
)fa.cy#holiday@group.v.calendar.google.comقبرسCY
E
,fa.czech#holiday@group.v.calendar.google.comجمهوری چکCZ
?
-fa.german#holiday@group.v.calendar.google.com
آلمانDE
C
-fa.danish#holiday@group.v.calendar.google.comدانمارکDK
N
)fa.do#holiday@group.v.calendar.google.comجمهوری دومینیکنDO
?
)fa.dz#holiday@group.v.calendar.google.comالجزایرDZ
?
)fa.ec#holiday@group.v.calendar.google.comاکوادورEC
=
)fa.ee#holiday@group.v.calendar.google.comاستونیEE
7
)fa.eg#holiday@group.v.calendar.google.comمصرEG
=
)fa.er#holiday@group.v.calendar.google.comاریترهER
B
,fa.spain#holiday@group.v.calendar.google.comاسپانیاES
=
)fa.et#holiday@group.v.calendar.google.comاتیوپیET
B
.fa.finnish#holiday@group.v.calendar.google.comفنلاندFI
9
)fa.fj#holiday@group.v.calendar.google.comفیجیFJ
D
)fa.fo#holiday@group.v.calendar.google.comجزایر فاروFO
A
-fa.french#holiday@group.v.calendar.google.comفرانسهFR
9
)fa.ga#holiday@group.v.calendar.google.comگابنGA
A
)fa.uk#holiday@group.v.calendar.google.comبریتانیاGB
=
)fa.gd#holiday@group.v.calendar.google.comگرناداGD
?
)fa.ge#holiday@group.v.calendar.google.comگرجستانGE
7
)fa.gh#holiday@group.v.calendar.google.comغناGH
F
)fa.gi#holiday@group.v.calendar.google.comجبل‌الطارقGI
?
)fa.gl#holiday@group.v.calendar.google.comگرینلندGL
=
)fa.gm#holiday@group.v.calendar.google.comگامبیاGM
9
)fa.gn#holiday@group.v.calendar.google.comگینهGN
J
)fa.gq#holiday@group.v.calendar.google.comگینهٔ استواییGQ
>
,fa.greek#holiday@group.v.calendar.google.com
یونانGR
A
)fa.gt#holiday@group.v.calendar.google.comگواتمالاGT
9
)fa.gu#holiday@group.v.calendar.google.comگوامGU
H
)fa.gw#holiday@group.v.calendar.google.comگینهٔ بیسائوGW
G
0fa.hong_kong#holiday@group.v.calendar.google.comهنگ‌کنگHK
?
)fa.hn#holiday@group.v.calendar.google.comهندوراسHN
C
/fa.croatian#holiday@group.v.calendar.google.comکرواسیHR
=
)fa.ht#holiday@group.v.calendar.google.comهائیتیHT
H
0fa.hungarian#holiday@group.v.calendar.google.comمجارستانHU
G
1fa.indonesian#holiday@group.v.calendar.google.comاندونزیID
@
,fa.irish#holiday@group.v.calendar.google.comایرلندIE
C
-fa.jewish#holiday@group.v.calendar.google.comاسرائیلIL
;
-fa.indian#holiday@group.v.calendar.google.comهندIN
9
)fa.iq#holiday@group.v.calendar.google.comعراقIQ
;
)fa.ir#holiday@group.v.calendar.google.com
ایرانIR
=
)fa.is#holiday@group.v.calendar.google.comایسلندIS
D
.fa.italian#holiday@group.v.calendar.google.comایتالیاIT
A
)fa.jm#holiday@group.v.calendar.google.comجامائیکاJM
9
)fa.jo#holiday@group.v.calendar.google.comاردنJO
?
/fa.japanese#holiday@group.v.calendar.google.comژاپنJP
9
)fa.ke#holiday@group.v.calendar.google.comکنیاKE
C
)fa.kg#holiday@group.v.calendar.google.comقرقیزستانKG
=
)fa.kh#holiday@group.v.calendar.google.comکامبوجKH
=
)fa.km#holiday@group.v.calendar.google.comکوموروKM
D
)fa.kp#holiday@group.v.calendar.google.comکرهٔ شمالیKP
M
2fa.south_korea#holiday@group.v.calendar.google.comکرهٔ جنوبیKR
9
)fa.kw#holiday@group.v.calendar.google.comکویتKW
F
)fa.ky#holiday@group.v.calendar.google.comجزایر کِیمنKY
A
)fa.kz#holiday@group.v.calendar.google.comقزاقستانKZ
;
)fa.lb#holiday@group.v.calendar.google.com
لبنانLB
J
)fa.li#holiday@group.v.calendar.google.comلیختن‌اشتاینLI
D
)fa.lk#holiday@group.v.calendar.google.comسری‌لانکاLK
=
)fa.lr#holiday@group.v.calendar.google.comلیبریاLR
;
)fa.ls#holiday@group.v.calendar.google.com
لسوتوLS
G
1fa.lithuanian#holiday@group.v.calendar.google.comلیتوانیLT
E
)fa.lu#holiday@group.v.calendar.google.comلوکزامبورگLU
@
.fa.latvian#holiday@group.v.calendar.google.com
لتونیLV
9
)fa.ly#holiday@group.v.calendar.google.comلیبیLY
;
)fa.ma#holiday@group.v.calendar.google.com
مراکشMA
=
)fa.mc#holiday@group.v.calendar.google.comموناکوMC
?
)fa.md#holiday@group.v.calendar.google.comمولداویMD
F
)fa.me#holiday@group.v.calendar.google.comمونته‌نگروME
E
)fa.mg#holiday@group.v.calendar.google.comماداگاسکارMG
?
)fa.mk#holiday@group.v.calendar.google.comمقدونیهMK
9
)fa.ml#holiday@group.v.calendar.google.comمالیML
A
)fa.mn#holiday@group.v.calendar.google.comمغولستانMN
=
)fa.mo#holiday@group.v.calendar.google.comماکائوMO
A
)fa.mq#holiday@group.v.calendar.google.comمارتینیکMQ
9
)fa.mt#holiday@group.v.calendar.google.comمالتMT
;
)fa.mu#holiday@group.v.calendar.google.com
موریسMU
=
)fa.mw#holiday@group.v.calendar.google.comمالاویMW
@
.fa.mexican#holiday@group.v.calendar.google.com
مکزیکMX
A
/fa.malaysia#holiday@group.v.calendar.google.com
مالزیMY
A
)fa.mz#holiday@group.v.calendar.google.comموزامبیکMZ
?
)fa.na#holiday@group.v.calendar.google.comنامیبیاNA
9
)fa.ne#holiday@group.v.calendar.google.comنیجرNE
=
)fa.ng#holiday@group.v.calendar.google.comنیجریهNG
E
)fa.ni#holiday@group.v.calendar.google.comنیکاراگوئهNI
<
,fa.dutch#holiday@group.v.calendar.google.comهلندNL
@
0fa.norwegian#holiday@group.v.calendar.google.comنروژNO
9
)fa.np#holiday@group.v.calendar.google.comنپالNP
J
2fa.new_zealand#holiday@group.v.calendar.google.comنیوزیلندNZ
9
)fa.om#holiday@group.v.calendar.google.comعمانOM
=
)fa.pa#holiday@group.v.calendar.google.comپاناماPA
7
)fa.pe#holiday@group.v.calendar.google.comپروPE
H
2fa.philippines#holiday@group.v.calendar.google.comفیلیپینPH
?
)fa.pk#holiday@group.v.calendar.google.comپاکستانPK
A
-fa.polish#holiday@group.v.calendar.google.comلهستانPL
C
)fa.pr#holiday@group.v.calendar.google.comپورتوریکوPR
E
1fa.portuguese#holiday@group.v.calendar.google.comپرتغالPT
A
)fa.py#holiday@group.v.calendar.google.comپاراگوئهPY
7
)fa.qa#holiday@group.v.calendar.google.comقطرQA
?
)fa.re#holiday@group.v.calendar.google.comرئونیونRE
C
/fa.romanian#holiday@group.v.calendar.google.comرومانیRO
?
)fa.rs#holiday@group.v.calendar.google.comصربستانRS
@
.fa.russian#holiday@group.v.calendar.google.com
روسیهRU
=
)fa.rw#holiday@group.v.calendar.google.comروانداRW
T
3fa.saudiarabian#holiday@group.v.calendar.google.comعربستان سعودیSA
9
)fa.sc#holiday@group.v.calendar.google.comسیشلSC
;
)fa.sd#holiday@group.v.calendar.google.com
سودانSD
>
.fa.swedish#holiday@group.v.calendar.google.comسوئدSE
F
0fa.singapore#holiday@group.v.calendar.google.comسنگاپورSG
>
)fa.sh#holiday@group.v.calendar.google.comسنت هلنSH
F
0fa.slovenian#holiday@group.v.calendar.google.comاسلوونیSI
C
-fa.slovak#holiday@group.v.calendar.google.comاسلواکیSK
A
)fa.sl#holiday@group.v.calendar.google.comسیرالئونSL
F
)fa.sm#holiday@group.v.calendar.google.comسان‌مارینوSM
;
)fa.sn#holiday@group.v.calendar.google.com
سنگالSN
=
)fa.so#holiday@group.v.calendar.google.comسومالیSO
?
)fa.sr#holiday@group.v.calendar.google.comسورینامSR
F
)fa.ss#holiday@group.v.calendar.google.comسودان جنوبیSS
S
)fa.st#holiday@group.v.calendar.google.com"سائوتومه و پرینسیپST
E
)fa.sv#holiday@group.v.calendar.google.comالسالوادورSV
;
)fa.sy#holiday@group.v.calendar.google.com
سوریهSY
A
)fa.sz#holiday@group.v.calendar.google.comسوازیلندSZ
7
)fa.td#holiday@group.v.calendar.google.comچادTD
9
)fa.tg#holiday@group.v.calendar.google.comتوگوTG
=
)fa.th#holiday@group.v.calendar.google.comتایلندTH
9
)fa.tn#holiday@group.v.calendar.google.comتونسTN
@
.fa.turkish#holiday@group.v.calendar.google.com
ترکیهTR
Q
)fa.tt#holiday@group.v.calendar.google.com ترینیداد و توباگوTT
A
-fa.taiwan#holiday@group.v.calendar.google.comتایوانTW
A
)fa.tz#holiday@group.v.calendar.google.comتانزانیاTZ
F
0fa.ukrainian#holiday@group.v.calendar.google.comاوکراینUA
?
)fa.ug#holiday@group.v.calendar.google.comاوگانداUG
I
*fa.usa#holiday@group.v.calendar.google.comایالات متحدهUS
?
)fa.uy#holiday@group.v.calendar.google.comاروگوئهUY
A
)fa.uz#holiday@group.v.calendar.google.comازبکستانUZ
?
)fa.va#holiday@group.v.calendar.google.comواتیکانVA
?
)fa.ve#holiday@group.v.calendar.google.comونزوئلاVE
`
)fa.vi#holiday@group.v.calendar.google.com/جزایر ویرجین ایالات متحدهVI
E
1fa.vietnamese#holiday@group.v.calendar.google.comویتنامVN
7
)fa.ye#holiday@group.v.calendar.google.comیمنYE
;
)fa.yt#holiday@group.v.calendar.google.com
مایوتYT
J
)fa.sa#holiday@group.v.calendar.google.comافریقای جنوبیZA
=
)fa.zm#holiday@group.v.calendar.google.comزامبیاZM
A
)fa.zw#holiday@group.v.calendar.google.comزیمبابوهZWQ
0fa.christian#holiday@group.v.calendar.google.comتعطیلات مسیحیانO
.fa.judaism#holiday@group.v.calendar.google.comتعطیلات یهودیانQ
.fa.islamic#holiday@group.v.calendar.google.comتعطیلات مسلمانانj
<fa.orthodox_christianity#holiday@group.v.calendar.google.com*تعطیلات مسیحیان ارتدکسfa