
C
)hi.ad#holiday@group.v.calendar.google.comएंडोराAD
c
)hi.ae#holiday@group.v.calendar.google.com2संयुक्त अरब अमीरातAE
U
)hi.af#holiday@group.v.calendar.google.com$अफ़गानिस्तानAF
L
)hi.al#holiday@group.v.calendar.google.comअल्बानियाAL
L
)hi.am#holiday@group.v.calendar.google.comआर्मेनियाAM
C
)hi.ao#holiday@group.v.calendar.google.comअंगोलाAO
O
)hi.ar#holiday@group.v.calendar.google.comअर्जेंटीनाAR
R
/hi.austrian#holiday@group.v.calendar.google.comऑस्ट्रियाAT
Z
1hi.australian#holiday@group.v.calendar.google.com!ऑस्ट्रेलियाAU
@
)hi.aw#holiday@group.v.calendar.google.comअरूबाAW
L
)hi.az#holiday@group.v.calendar.google.comअज़रबैजानAZ
u
)hi.ba#holiday@group.v.calendar.google.comDबोस्निया और हर्ज़ेगोविनाBA
I
)hi.bb#holiday@group.v.calendar.google.comबारबाडोसBB
O
)hi.bd#holiday@group.v.calendar.google.comबांग्लादेशBD
I
)hi.be#holiday@group.v.calendar.google.comबेल्जियमBE
Y
)hi.bf#holiday@group.v.calendar.google.com(बुर्किना फ़ासोBF
V
0hi.bulgarian#holiday@group.v.calendar.google.comबुल्गारियाBG
@
)hi.bh#holiday@group.v.calendar.google.comबहरीनBH
F
)hi.bi#holiday@group.v.calendar.google.comबुरुंडीBI
@
)hi.bj#holiday@group.v.calendar.google.comबेनिनBJ
C
)hi.bm#holiday@group.v.calendar.google.comबरमूडाBM
I
)hi.bo#holiday@group.v.calendar.google.comबोलीवियाBO
P
0hi.brazilian#holiday@group.v.calendar.google.comब्राज़ीलBR
C
)hi.bs#holiday@group.v.calendar.google.comबहामासBS
O
)hi.bw#holiday@group.v.calendar.google.comबोत्स्वानाBW
F
)hi.by#holiday@group.v.calendar.google.comबेलारूसBY
F
/hi.canadian#holiday@group.v.calendar.google.comकनाडाCA
X
)hi.cd#holiday@group.v.calendar.google.com'कांगो - किंशासाCD
l
)hi.cf#holiday@group.v.calendar.google.com;मध्य अफ़्रीकी गणराज्यCF
c
)hi.cg#holiday@group.v.calendar.google.com2कांगो – ब्राज़ाविलCG
X
)hi.ch#holiday@group.v.calendar.google.com'स्विट्ज़रलैंडCH
N
)hi.ci#holiday@group.v.calendar.google.comकोट डी आइवरCI
=
)hi.cl#holiday@group.v.calendar.google.comचिलीCL
C
)hi.cm#holiday@group.v.calendar.google.comकैमरूनCM
=
,hi.china#holiday@group.v.calendar.google.com	चीनCN
I
)hi.co#holiday@group.v.calendar.google.comकोलंबियाCO
O
)hi.cr#holiday@group.v.calendar.google.comकोस्टारिकाCR
C
)hi.cu#holiday@group.v.calendar.google.comक्यूबाCU
G
)hi.cv#holiday@group.v.calendar.google.comकेप वर्डCV
F
)hi.cy#holiday@group.v.calendar.google.comसाइप्रसCY
S
,hi.czech#holiday@group.v.calendar.google.comचेक गणराज्यCZ
G
-hi.german#holiday@group.v.calendar.google.comजर्मनीDE
M
-hi.danish#holiday@group.v.calendar.google.comडेनमार्कDK
_
)hi.do#holiday@group.v.calendar.google.com.डोमिनिकन गणराज्यDO
L
)hi.dz#holiday@group.v.calendar.google.comअल्जीरियाDZ
I
)hi.ec#holiday@group.v.calendar.google.comइक्वाडोरEC
L
)hi.ee#holiday@group.v.calendar.google.comएस्टोनियाEE
@
)hi.eg#holiday@group.v.calendar.google.comमिस्रEG
L
)hi.er#holiday@group.v.calendar.google.comइरिट्रियाER
C
,hi.spain#holiday@group.v.calendar.google.comस्पेनES
L
)hi.et#holiday@group.v.calendar.google.comइथियोपियाET
N
.hi.finnish#holiday@group.v.calendar.google.comफ़िनलैंडFI
@
)hi.fj#holiday@group.v.calendar.google.comफ़िजीFJ
\
)hi.fo#holiday@group.v.calendar.google.com+फ़ेरो द्वीपसमूहFO
J
-hi.french#holiday@group.v.calendar.google.comफ़्रांसFR
@
)hi.ga#holiday@group.v.calendar.google.comगैबॉनGA
\
)hi.uk#holiday@group.v.calendar.google.com+यूनाइटेड किंगडमGB
I
)hi.gd#holiday@group.v.calendar.google.comग्रेनाडाGD
I
)hi.ge#holiday@group.v.calendar.google.comजॉर्जियाGE
=
)hi.gh#holiday@group.v.calendar.google.comघानाGH
O
)hi.gi#holiday@group.v.calendar.google.comजिब्राल्टरGI
L
)hi.gl#holiday@group.v.calendar.google.comग्रीनलैंडGL
I
)hi.gm#holiday@group.v.calendar.google.comगाम्बियाGM
=
)hi.gn#holiday@group.v.calendar.google.comगिनीGN
_
)hi.gq#holiday@group.v.calendar.google.com.इक्वेटोरियल गिनीGQ
C
,hi.greek#holiday@group.v.calendar.google.comयूनानGR
O
)hi.gt#holiday@group.v.calendar.google.comग्वाटेमालाGT
=
)hi.gu#holiday@group.v.calendar.google.comगुआमGU
M
)hi.gw#holiday@group.v.calendar.google.comगिनी-बिसाउGW
Q
0hi.hong_kong#holiday@group.v.calendar.google.comहाँग काँगHK
I
)hi.hn#holiday@group.v.calendar.google.comहोंडूरासHN
R
/hi.croatian#holiday@group.v.calendar.google.comक्रोएशियाHR
=
)hi.ht#holiday@group.v.calendar.google.comहैतीHT
G
0hi.hungarian#holiday@group.v.calendar.google.comहंगरीHU
W
1hi.indonesian#holiday@group.v.calendar.google.comइंडोनेशियाID
I
,hi.irish#holiday@group.v.calendar.google.comआयरलैंडIE
J
-hi.jewish#holiday@group.v.calendar.google.comइज़राइलIL
A
-hi.indian#holiday@group.v.calendar.google.comभारतIN
=
)hi.iq#holiday@group.v.calendar.google.comइराकIQ
=
)hi.ir#holiday@group.v.calendar.google.comईरानIR
F
)hi.is#holiday@group.v.calendar.google.comआइसलैंडIS
B
.hi.italian#holiday@group.v.calendar.google.comइटलीIT
@
)hi.jm#holiday@group.v.calendar.google.comजमैकाJM
C
)hi.jo#holiday@group.v.calendar.google.comजॉर्डनJO
F
/hi.japanese#holiday@group.v.calendar.google.comजापानJP
C
)hi.ke#holiday@group.v.calendar.google.comकेन्याKE
X
)hi.kg#holiday@group.v.calendar.google.com'किर्गिज़स्तानKG
I
)hi.kh#holiday@group.v.calendar.google.comकंबोडियाKH
F
)hi.km#holiday@group.v.calendar.google.comकोमोरोसKM
S
)hi.kp#holiday@group.v.calendar.google.com"उत्तर कोरियाKP
_
2hi.south_korea#holiday@group.v.calendar.google.com%दक्षिण कोरियाKR
@
)hi.kw#holiday@group.v.calendar.google.comकुवैतKW
\
)hi.ky#holiday@group.v.calendar.google.com+केमैन द्वीपसमूहKY
O
)hi.kz#holiday@group.v.calendar.google.comकज़ाखस्तानKZ
C
)hi.lb#holiday@group.v.calendar.google.comलेबनानLB
O
)hi.li#holiday@group.v.calendar.google.comलिचेंस्टीनLI
I
)hi.lk#holiday@group.v.calendar.google.comश्रीलंकाLK
L
)hi.lr#holiday@group.v.calendar.google.comलाइबेरियाLR
C
)hi.ls#holiday@group.v.calendar.google.comलेसोथोLS
T
1hi.lithuanian#holiday@group.v.calendar.google.comलिथुआनियाLT
O
)hi.lu#holiday@group.v.calendar.google.comलग्ज़मबर्गLU
K
.hi.latvian#holiday@group.v.calendar.google.comलातवियाLV
C
)hi.ly#holiday@group.v.calendar.google.comलीबियाLY
F
)hi.ma#holiday@group.v.calendar.google.comमोरक्कोMA
C
)hi.mc#holiday@group.v.calendar.google.comमोनाकोMC
I
)hi.md#holiday@group.v.calendar.google.comमॉल्डोवाMD
R
)hi.me#holiday@group.v.calendar.google.com!मोंटेनेग्रोME
O
)hi.mg#holiday@group.v.calendar.google.comमेडागास्करMG
O
)hi.mk#holiday@group.v.calendar.google.comमैसिडोनियाMK
=
)hi.ml#holiday@group.v.calendar.google.comमालीML
I
)hi.mn#holiday@group.v.calendar.google.comमंगोलियाMN
=
)hi.mo#holiday@group.v.calendar.google.comमकाऊMO
L
)hi.mq#holiday@group.v.calendar.google.comमार्टीनिकMQ
C
)hi.mt#holiday@group.v.calendar.google.comमाल्टाMT
C
)hi.mu#holiday@group.v.calendar.google.comमॉरिशसMU
@
)hi.mw#holiday@group.v.calendar.google.comमलावीMW
N
.hi.mexican#holiday@group.v.calendar.google.comमैक्सिकोMX
L
/hi.malaysia#holiday@group.v.calendar.google.comमलेशियाMY
L
)hi.mz#holiday@group.v.calendar.google.comमोज़ांबिकMZ
I
)hi.na#holiday@group.v.calendar.google.comनामीबियाNA
@
)hi.ne#holiday@group.v.calendar.google.comनाइजरNE
L
)hi.ng#holiday@group.v.calendar.google.comनाइजीरियाNG
L
)hi.ni#holiday@group.v.calendar.google.comनिकारागुआNI
L
,hi.dutch#holiday@group.v.calendar.google.comनीदरलैंडNL
J
0hi.norwegian#holiday@group.v.calendar.google.comनॉर्वेNO
@
)hi.np#holiday@group.v.calendar.google.comनेपालNP
[
2hi.new_zealand#holiday@group.v.calendar.google.com!न्यूज़ीलैंडNZ
=
)hi.om#holiday@group.v.calendar.google.comओमानOM
@
)hi.pa#holiday@group.v.calendar.google.comपनामाPA
=
)hi.pe#holiday@group.v.calendar.google.comपेरूPE
U
2hi.philippines#holiday@group.v.calendar.google.comफ़िलिपींसPH
L
)hi.pk#holiday@group.v.calendar.google.comपाकिस्तानPK
G
-hi.polish#holiday@group.v.calendar.google.comपोलैंडPL
P
)hi.pr#holiday@group.v.calendar.google.comपोर्टो रिकोPR
Q
1hi.portuguese#holiday@group.v.calendar.google.comपुर्तगालPT
I
)hi.py#holiday@group.v.calendar.google.comपेराग्वेPY
=
)hi.qa#holiday@group.v.calendar.google.comक़तरQA
I
)hi.re#holiday@group.v.calendar.google.comरियूनियनRE
O
/hi.romanian#holiday@group.v.calendar.google.comरोमानियाRO
F
)hi.rs#holiday@group.v.calendar.google.comसर्बियाRS
?
.hi.russian#holiday@group.v.calendar.google.com	रूसRU
C
)hi.rw#holiday@group.v.calendar.google.comरवांडाRW
Q
3hi.saudiarabian#holiday@group.v.calendar.google.comसऊदी अरबSA
F
)hi.sc#holiday@group.v.calendar.google.comसेशेल्सSC
@
)hi.sd#holiday@group.v.calendar.google.comसूडानSD
H
.hi.swedish#holiday@group.v.calendar.google.comस्वीडनSE
P
0hi.singapore#holiday@group.v.calendar.google.comसिंगापुरSG
P
)hi.sh#holiday@group.v.calendar.google.comसेंट हेलेनाSH
V
0hi.slovenian#holiday@group.v.calendar.google.comस्लोवेनियाSI
S
-hi.slovak#holiday@group.v.calendar.google.comस्लोवाकियाSK
P
)hi.sl#holiday@group.v.calendar.google.comसिएरा लियोनSL
M
)hi.sm#holiday@group.v.calendar.google.comसैन मेरीनोSM
C
)hi.sn#holiday@group.v.calendar.google.comसेनेगलSN
I
)hi.so#holiday@group.v.calendar.google.comसोमालियाSO
F
)hi.sr#holiday@group.v.calendar.google.comसूरीनामSR
S
)hi.ss#holiday@group.v.calendar.google.com"दक्षिण सूडानSS
g
)hi.st#holiday@group.v.calendar.google.com6साओ टोम और प्रिंसिपेST
P
)hi.sv#holiday@group.v.calendar.google.comअल सल्वाडोरSV
C
)hi.sy#holiday@group.v.calendar.google.comसीरियाSY
R
)hi.sz#holiday@group.v.calendar.google.com!स्वाज़ीलैंडSZ
:
)hi.td#holiday@group.v.calendar.google.com	चाडTD
=
)hi.tg#holiday@group.v.calendar.google.comटोगोTG
F
)hi.th#holiday@group.v.calendar.google.comथाईलैंडTH
O
)hi.tn#holiday@group.v.calendar.google.comट्यूनीशियाTN
H
.hi.turkish#holiday@group.v.calendar.google.comतुर्कीTR
f
)hi.tt#holiday@group.v.calendar.google.com5त्रिनिदाद और टोबैगोTT
G
-hi.taiwan#holiday@group.v.calendar.google.comताइवानTW
L
)hi.tz#holiday@group.v.calendar.google.comतंज़ानियाTZ
M
0hi.ukrainian#holiday@group.v.calendar.google.comयूक्रेनUA
F
)hi.ug#holiday@group.v.calendar.google.comयुगांडाUG
W
*hi.usa#holiday@group.v.calendar.google.com%संयुक्त राज्यUS
F
)hi.uy#holiday@group.v.calendar.google.comउरूग्वेUY
X
)hi.uz#holiday@group.v.calendar.google.com'उज़्बेकिस्तानUZ
P
)hi.va#holiday@group.v.calendar.google.comवेटिकन सिटीVA
O
)hi.ve#holiday@group.v.calendar.google.comवेनेज़ुएलाVE
n
)hi.vi#holiday@group.v.calendar.google.com=यू.एस. वर्जिन द्वीपसमूहVI
N
1hi.vietnamese#holiday@group.v.calendar.google.comवियतनामVN
:
)hi.ye#holiday@group.v.calendar.google.com	यमनYE
C
)hi.yt#holiday@group.v.calendar.google.comमायोतेYT
\
)hi.sa#holiday@group.v.calendar.google.com+दक्षिण अफ़्रीकाZA
L
)hi.zm#holiday@group.v.calendar.google.comज़ाम्बियाZM
R
)hi.zw#holiday@group.v.calendar.google.com!ज़िम्बाब्वेZWd
0hi.christian#holiday@group.v.calendar.google.com0ईसाई धर्म के अवकाशe
.hi.judaism#holiday@group.v.calendar.google.com3यहूदी धर्म के अवकाशh
.hi.islamic#holiday@group.v.calendar.google.com6इस्लाम धर्म के अवकाश�
<hi.orthodox_christianity#holiday@group.v.calendar.google.comOऑर्थोडॉक्स ईसाई धर्म के अवकाशhi