
8
)da.ad#holiday@group.v.calendar.google.comAndorraAD
N
)da.ae#holiday@group.v.calendar.google.comDe Forenede Arabiske EmiraterAE
<
)da.af#holiday@group.v.calendar.google.comAfghanistanAF
9
)da.al#holiday@group.v.calendar.google.comAlbanienAL
9
)da.am#holiday@group.v.calendar.google.comArmenienAM
7
)da.ao#holiday@group.v.calendar.google.comAngolaAO
:
)da.ar#holiday@group.v.calendar.google.com	ArgentinaAR
>
/da.austrian#holiday@group.v.calendar.google.comØstrigAT
C
1da.australian#holiday@group.v.calendar.google.com
AustralienAU
6
)da.aw#holiday@group.v.calendar.google.comArubaAW
=
)da.az#holiday@group.v.calendar.google.comAserbajdsjanAZ
D
)da.ba#holiday@group.v.calendar.google.comBosnien-HercegovinaBA
9
)da.bb#holiday@group.v.calendar.google.comBarbadosBB
;
)da.bd#holiday@group.v.calendar.google.com
BangladeshBD
8
)da.be#holiday@group.v.calendar.google.comBelgienBE
=
)da.bf#holiday@group.v.calendar.google.comBurkina FasoBF
A
0da.bulgarian#holiday@group.v.calendar.google.com	BulgarienBG
8
)da.bh#holiday@group.v.calendar.google.comBahrainBH
8
)da.bi#holiday@group.v.calendar.google.comBurundiBI
6
)da.bj#holiday@group.v.calendar.google.comBeninBJ
8
)da.bm#holiday@group.v.calendar.google.comBermudaBM
8
)da.bo#holiday@group.v.calendar.google.comBoliviaBO
A
0da.brazilian#holiday@group.v.calendar.google.com	BrasilienBR
8
)da.bs#holiday@group.v.calendar.google.comBahamasBS
9
)da.bw#holiday@group.v.calendar.google.comBotswanaBW
=
)da.by#holiday@group.v.calendar.google.comHvideruslandBY
=
/da.canadian#holiday@group.v.calendar.google.comCanadaCA
?
)da.cd#holiday@group.v.calendar.google.comCongo-KinshasaCD
O
)da.cf#holiday@group.v.calendar.google.comDen Centralafrikanske RepublikCF
B
)da.cg#holiday@group.v.calendar.google.comCongo-BrazzavilleCG
8
)da.ch#holiday@group.v.calendar.google.comSchweizCH
@
)da.ci#holiday@group.v.calendar.google.comElfenbenskystenCI
6
)da.cl#holiday@group.v.calendar.google.comChileCL
9
)da.cm#holiday@group.v.calendar.google.comCamerounCM
8
,da.china#holiday@group.v.calendar.google.comKinaCN
9
)da.co#holiday@group.v.calendar.google.comColombiaCO
;
)da.cr#holiday@group.v.calendar.google.com
Costa RicaCR
5
)da.cu#holiday@group.v.calendar.google.comCubaCU
:
)da.cv#holiday@group.v.calendar.google.com	Kap VerdeCV
7
)da.cy#holiday@group.v.calendar.google.comCypernCY
<
,da.czech#holiday@group.v.calendar.google.comTjekkietCZ
=
-da.german#holiday@group.v.calendar.google.comTysklandDE
<
-da.danish#holiday@group.v.calendar.google.comDanmarkDK
J
)da.do#holiday@group.v.calendar.google.comDen Dominikanske RepublikDO
9
)da.dz#holiday@group.v.calendar.google.comAlgerietDZ
8
)da.ec#holiday@group.v.calendar.google.comEcuadorEC
8
)da.ee#holiday@group.v.calendar.google.comEstlandEE
8
)da.eg#holiday@group.v.calendar.google.comEgyptenEG
8
)da.er#holiday@group.v.calendar.google.comEritreaER
;
,da.spain#holiday@group.v.calendar.google.comSpanienES
9
)da.et#holiday@group.v.calendar.google.comEtiopienET
=
.da.finnish#holiday@group.v.calendar.google.comFinlandFI
5
)da.fj#holiday@group.v.calendar.google.comFijiFJ
;
)da.fo#holiday@group.v.calendar.google.com
FærøerneFO
=
-da.french#holiday@group.v.calendar.google.comFrankrigFR
6
)da.ga#holiday@group.v.calendar.google.comGabonGA
?
)da.uk#holiday@group.v.calendar.google.comStorbritannienGB
8
)da.gd#holiday@group.v.calendar.google.comGrenadaGD
9
)da.ge#holiday@group.v.calendar.google.comGeorgienGE
6
)da.gh#holiday@group.v.calendar.google.comGhanaGH
:
)da.gi#holiday@group.v.calendar.google.com	GibraltarGI
:
)da.gl#holiday@group.v.calendar.google.com	GrønlandGL
7
)da.gm#holiday@group.v.calendar.google.comGambiaGM
7
)da.gn#holiday@group.v.calendar.google.comGuineaGN
B
)da.gq#holiday@group.v.calendar.google.comÆkvatorialguineaGQ
?
,da.greek#holiday@group.v.calendar.google.comGrækenlandGR
:
)da.gt#holiday@group.v.calendar.google.com	GuatemalaGT
5
)da.gu#holiday@group.v.calendar.google.comGuamGU
>
)da.gw#holiday@group.v.calendar.google.comGuinea-BissauGW
@
0da.hong_kong#holiday@group.v.calendar.google.comHongkongHK
9
)da.hn#holiday@group.v.calendar.google.comHondurasHN
?
/da.croatian#holiday@group.v.calendar.google.comKroatienHR
6
)da.ht#holiday@group.v.calendar.google.comHaitiHT
>
0da.hungarian#holiday@group.v.calendar.google.comUngarnHU
C
1da.indonesian#holiday@group.v.calendar.google.com
IndonesienID
:
,da.irish#holiday@group.v.calendar.google.comIrlandIE
;
-da.jewish#holiday@group.v.calendar.google.comIsraelIL
;
-da.indian#holiday@group.v.calendar.google.comIndienIN
5
)da.iq#holiday@group.v.calendar.google.comIrakIQ
5
)da.ir#holiday@group.v.calendar.google.comIranIR
7
)da.is#holiday@group.v.calendar.google.comIslandIS
=
.da.italian#holiday@group.v.calendar.google.comItalienIT
8
)da.jm#holiday@group.v.calendar.google.comJamaicaJM
7
)da.jo#holiday@group.v.calendar.google.comJordanJO
<
/da.japanese#holiday@group.v.calendar.google.comJapanJP
6
)da.ke#holiday@group.v.calendar.google.comKenyaKE
<
)da.kg#holiday@group.v.calendar.google.comKirgisistanKG
9
)da.kh#holiday@group.v.calendar.google.comCambodjaKH
:
)da.km#holiday@group.v.calendar.google.com	ComorerneKM
:
)da.kp#holiday@group.v.calendar.google.com	NordkoreaKP
B
2da.south_korea#holiday@group.v.calendar.google.comSydkoreaKR
7
)da.kw#holiday@group.v.calendar.google.comKuwaitKW
=
)da.ky#holiday@group.v.calendar.google.comCaymanøerneKY
;
)da.kz#holiday@group.v.calendar.google.com
KasakhstanKZ
8
)da.lb#holiday@group.v.calendar.google.comLibanonLB
>
)da.li#holiday@group.v.calendar.google.comLiechtensteinLI
:
)da.lk#holiday@group.v.calendar.google.com	Sri LankaLK
8
)da.lr#holiday@group.v.calendar.google.comLiberiaLR
8
)da.ls#holiday@group.v.calendar.google.comLesothoLS
@
1da.lithuanian#holiday@group.v.calendar.google.comLitauenLT
;
)da.lu#holiday@group.v.calendar.google.com
LuxembourgLU
=
.da.latvian#holiday@group.v.calendar.google.comLetlandLV
7
)da.ly#holiday@group.v.calendar.google.comLibyenLY
8
)da.ma#holiday@group.v.calendar.google.comMarokkoMA
7
)da.mc#holiday@group.v.calendar.google.comMonacoMC
8
)da.md#holiday@group.v.calendar.google.comMoldovaMD
;
)da.me#holiday@group.v.calendar.google.com
MontenegroME
;
)da.mg#holiday@group.v.calendar.google.com
MadagaskarMG
;
)da.mk#holiday@group.v.calendar.google.com
MakedonienMK
5
)da.ml#holiday@group.v.calendar.google.comMaliML
:
)da.mn#holiday@group.v.calendar.google.com	MongolietMN
6
)da.mo#holiday@group.v.calendar.google.comMacaoMO
;
)da.mq#holiday@group.v.calendar.google.com
MartiniqueMQ
6
)da.mt#holiday@group.v.calendar.google.comMaltaMT
:
)da.mu#holiday@group.v.calendar.google.com	MauritiusMU
7
)da.mw#holiday@group.v.calendar.google.comMalawiMW
<
.da.mexican#holiday@group.v.calendar.google.comMexicoMX
?
/da.malaysia#holiday@group.v.calendar.google.comMalaysiaMY
;
)da.mz#holiday@group.v.calendar.google.com
MozambiqueMZ
8
)da.na#holiday@group.v.calendar.google.comNamibiaNA
6
)da.ne#holiday@group.v.calendar.google.comNigerNE
8
)da.ng#holiday@group.v.calendar.google.comNigeriaNG
:
)da.ni#holiday@group.v.calendar.google.com	NicaraguaNI
;
,da.dutch#holiday@group.v.calendar.google.comHollandNL
=
0da.norwegian#holiday@group.v.calendar.google.comNorgeNO
6
)da.np#holiday@group.v.calendar.google.comNepalNP
E
2da.new_zealand#holiday@group.v.calendar.google.comNew ZealandNZ
5
)da.om#holiday@group.v.calendar.google.comOmanOM
7
)da.pa#holiday@group.v.calendar.google.comPanamaPA
5
)da.pe#holiday@group.v.calendar.google.comPeruPE
F
2da.philippines#holiday@group.v.calendar.google.comFilippinernePH
9
)da.pk#holiday@group.v.calendar.google.comPakistanPK
:
-da.polish#holiday@group.v.calendar.google.comPolenPL
<
)da.pr#holiday@group.v.calendar.google.comPuerto RicoPR
A
1da.portuguese#holiday@group.v.calendar.google.comPortugalPT
9
)da.py#holiday@group.v.calendar.google.comParaguayPY
6
)da.qa#holiday@group.v.calendar.google.comQatarQA
9
)da.re#holiday@group.v.calendar.google.comRéunionRE
@
/da.romanian#holiday@group.v.calendar.google.com	RumænienRO
8
)da.rs#holiday@group.v.calendar.google.comSerbienRS
=
.da.russian#holiday@group.v.calendar.google.comRuslandRU
7
)da.rw#holiday@group.v.calendar.google.comRwandaRW
H
3da.saudiarabian#holiday@group.v.calendar.google.comSaudi-ArabienSA
=
)da.sc#holiday@group.v.calendar.google.comSeychellerneSC
6
)da.sd#holiday@group.v.calendar.google.comSudanSD
=
.da.swedish#holiday@group.v.calendar.google.comSverigeSE
A
0da.singapore#holiday@group.v.calendar.google.com	SingaporeSG
;
)da.sh#holiday@group.v.calendar.google.com
St. HelenaSH
A
0da.slovenian#holiday@group.v.calendar.google.com	SlovenienSI
>
-da.slovak#holiday@group.v.calendar.google.com	SlovakietSK
=
)da.sl#holiday@group.v.calendar.google.comSierra LeoneSL
;
)da.sm#holiday@group.v.calendar.google.com
San MarinoSM
8
)da.sn#holiday@group.v.calendar.google.comSenegalSN
8
)da.so#holiday@group.v.calendar.google.comSomaliaSO
8
)da.sr#holiday@group.v.calendar.google.comSurinamSR
9
)da.ss#holiday@group.v.calendar.google.comSydsudanSS
H
)da.st#holiday@group.v.calendar.google.comSão Tomé og PríncipeST
<
)da.sv#holiday@group.v.calendar.google.comEl SalvadorSV
7
)da.sy#holiday@group.v.calendar.google.comSyrienSY
:
)da.sz#holiday@group.v.calendar.google.com	SwazilandSZ
6
)da.td#holiday@group.v.calendar.google.comTchadTD
5
)da.tg#holiday@group.v.calendar.google.comTogoTG
9
)da.th#holiday@group.v.calendar.google.comThailandTH
9
)da.tn#holiday@group.v.calendar.google.comTunesienTN
=
.da.turkish#holiday@group.v.calendar.google.comTyrkietTR
C
)da.tt#holiday@group.v.calendar.google.comTrinidad og TobagoTT
;
-da.taiwan#holiday@group.v.calendar.google.comTaiwanTW
9
)da.tz#holiday@group.v.calendar.google.comTanzaniaTZ
?
0da.ukrainian#holiday@group.v.calendar.google.comUkraineUA
7
)da.ug#holiday@group.v.calendar.google.comUgandaUG
5
*da.usa#holiday@group.v.calendar.google.comUSAUS
8
)da.uy#holiday@group.v.calendar.google.comUruguayUY
;
)da.uz#holiday@group.v.calendar.google.com
UsbekistanUZ
>
)da.va#holiday@group.v.calendar.google.comVatikanstatenVA
:
)da.ve#holiday@group.v.calendar.google.com	VenezuelaVE
J
)da.vi#holiday@group.v.calendar.google.comDe Amerikanske JomfruøerVI
@
1da.vietnamese#holiday@group.v.calendar.google.comVietnamVN
6
)da.ye#holiday@group.v.calendar.google.comYemenYE
8
)da.yt#holiday@group.v.calendar.google.comMayotteYT
:
)da.sa#holiday@group.v.calendar.google.com	SydafrikaZA
7
)da.zm#holiday@group.v.calendar.google.comZambiaZM
9
)da.zw#holiday@group.v.calendar.google.comZimbabweZWF
0da.christian#holiday@group.v.calendar.google.comKristne helligdageE
.da.judaism#holiday@group.v.calendar.google.comJødiske helligdageF
.da.islamic#holiday@group.v.calendar.google.comMuslimske helligdageT
<da.orthodox_christianity#holiday@group.v.calendar.google.comOrtodokse helligdageda