
=
)be.ad#holiday@group.v.calendar.google.comАндораAD
f
)be.ae#holiday@group.v.calendar.google.com5Аб’яднаныя Арабскія ЭміратыAE
E
)be.af#holiday@group.v.calendar.google.comАфганістанAF
?
)be.al#holiday@group.v.calendar.google.comАлбаніяAL
?
)be.am#holiday@group.v.calendar.google.comАрменіяAM
=
)be.ao#holiday@group.v.calendar.google.comАнголаAO
C
)be.ar#holiday@group.v.calendar.google.comАргенцінаAR
E
/be.austrian#holiday@group.v.calendar.google.comАўстрыяAT
K
1be.australian#holiday@group.v.calendar.google.comАўстраліяAU
;
)be.aw#holiday@group.v.calendar.google.com
АрубаAW
G
)be.az#holiday@group.v.calendar.google.comАзербайджанAZ
W
)be.ba#holiday@group.v.calendar.google.com&Боснія і ГерцагавінаBA
A
)be.bb#holiday@group.v.calendar.google.comБарбадасBB
C
)be.bd#holiday@group.v.calendar.google.comБангладэшBD
?
)be.be#holiday@group.v.calendar.google.comБельгіяBE
H
)be.bf#holiday@group.v.calendar.google.comБуркіна-ФасоBF
H
0be.bulgarian#holiday@group.v.calendar.google.comБалгарыяBG
?
)be.bh#holiday@group.v.calendar.google.comБахрэйнBH
A
)be.bi#holiday@group.v.calendar.google.comБурундзіBI
;
)be.bj#holiday@group.v.calendar.google.com
БенінBJ
T
)be.bm#holiday@group.v.calendar.google.com#Бермудскія астравыBM
?
)be.bo#holiday@group.v.calendar.google.comБалівіяBO
H
0be.brazilian#holiday@group.v.calendar.google.comБразіліяBR
=
)be.bs#holiday@group.v.calendar.google.comБагамыBS
A
)be.bw#holiday@group.v.calendar.google.comБатсванаBW
A
)be.by#holiday@group.v.calendar.google.comБеларусьBY
C
/be.canadian#holiday@group.v.calendar.google.comКанадаCA
L
)be.cd#holiday@group.v.calendar.google.comКонга (Кіншаса)CD
p
)be.cf#holiday@group.v.calendar.google.com?Цэнтральнаафрыканская РэспублікаCF
P
)be.cg#holiday@group.v.calendar.google.comКонга - БразавільCG
C
)be.ch#holiday@group.v.calendar.google.comШвейцарыяCH
G
)be.ci#holiday@group.v.calendar.google.comКот-д’ІвуарCI
9
)be.cl#holiday@group.v.calendar.google.comЧыліCL
?
)be.cm#holiday@group.v.calendar.google.comКамерунCM
>
,be.china#holiday@group.v.calendar.google.com
КітайCN
A
)be.co#holiday@group.v.calendar.google.comКалумбіяCO
D
)be.cr#holiday@group.v.calendar.google.comКоста-РыкаCR
9
)be.cu#holiday@group.v.calendar.google.comКубаCU
D
)be.cv#holiday@group.v.calendar.google.comКаба-ВердэCV
9
)be.cy#holiday@group.v.calendar.google.comКіпрCY
>
,be.czech#holiday@group.v.calendar.google.com
ЧэхіяCZ
E
-be.german#holiday@group.v.calendar.google.comГерманіяDE
?
-be.danish#holiday@group.v.calendar.google.com
ДаніяDK
`
)be.do#holiday@group.v.calendar.google.com/Дамініканская РэспублікаDO
;
)be.dz#holiday@group.v.calendar.google.com
АлжырDZ
?
)be.ec#holiday@group.v.calendar.google.comЭквадорEC
?
)be.ee#holiday@group.v.calendar.google.comЭстоніяEE
=
)be.eg#holiday@group.v.calendar.google.comЕгіпетEG
?
)be.er#holiday@group.v.calendar.google.comЭрытрэяER
B
,be.spain#holiday@group.v.calendar.google.comІспаніяES
?
)be.et#holiday@group.v.calendar.google.comЭфіопіяET
H
.be.finnish#holiday@group.v.calendar.google.comФінляндыяFI
;
)be.fj#holiday@group.v.calendar.google.com
ФіджыFJ
R
)be.fo#holiday@group.v.calendar.google.com!Фарэрскія астравыFO
C
-be.french#holiday@group.v.calendar.google.comФранцыяFR
;
)be.ga#holiday@group.v.calendar.google.com
ГабонGA
M
)be.uk#holiday@group.v.calendar.google.comВялікабрытаніяGB
?
)be.gd#holiday@group.v.calendar.google.comГрэнадаGD
=
)be.ge#holiday@group.v.calendar.google.comГрузіяGE
9
)be.gh#holiday@group.v.calendar.google.comГанаGH
C
)be.gi#holiday@group.v.calendar.google.comГібралтарGI
E
)be.gl#holiday@group.v.calendar.google.comГрэнландыяGL
=
)be.gm#holiday@group.v.calendar.google.comГамбіяGM
=
)be.gn#holiday@group.v.calendar.google.comГвінеяGN
Z
)be.gq#holiday@group.v.calendar.google.com)Экватарыяльная ГвінеяGQ
@
,be.greek#holiday@group.v.calendar.google.comГрэцыяGR
C
)be.gt#holiday@group.v.calendar.google.comГватэмалаGT
9
)be.gu#holiday@group.v.calendar.google.comГуамGU
H
)be.gw#holiday@group.v.calendar.google.comГвінея-БісауGW
F
0be.hong_kong#holiday@group.v.calendar.google.comГанконгHK
A
)be.hn#holiday@group.v.calendar.google.comГандурасHN
G
/be.croatian#holiday@group.v.calendar.google.comХарватыяHR
;
)be.ht#holiday@group.v.calendar.google.com
ГаіціHT
F
0be.hungarian#holiday@group.v.calendar.google.comВенгрыяHU
K
1be.indonesian#holiday@group.v.calendar.google.comІнданезіяID
D
,be.irish#holiday@group.v.calendar.google.comІрландыяIE
C
-be.jewish#holiday@group.v.calendar.google.comІзраільIL
?
-be.indian#holiday@group.v.calendar.google.com
ІндыяIN
9
)be.iq#holiday@group.v.calendar.google.comІракIQ
9
)be.ir#holiday@group.v.calendar.google.comІранIR
A
)be.is#holiday@group.v.calendar.google.comІсландыяIS
B
.be.italian#holiday@group.v.calendar.google.comІталіяIT
=
)be.jm#holiday@group.v.calendar.google.comЯмайкаJM
A
)be.jo#holiday@group.v.calendar.google.comІарданіяJO
C
/be.japanese#holiday@group.v.calendar.google.comЯпоніяJP
;
)be.ke#holiday@group.v.calendar.google.com
КеніяKE
E
)be.kg#holiday@group.v.calendar.google.comКыргызстанKG
A
)be.kh#holiday@group.v.calendar.google.comКамбоджаKH
R
)be.km#holiday@group.v.calendar.google.com!Каморскія АстравыKM
N
)be.kp#holiday@group.v.calendar.google.comПаўночная КарэяKP
W
2be.south_korea#holiday@group.v.calendar.google.comПаўднёвая КарэяKR
=
)be.kw#holiday@group.v.calendar.google.comКувейтKW
R
)be.ky#holiday@group.v.calendar.google.com!Кайманавы астравыKY
C
)be.kz#holiday@group.v.calendar.google.comКазахстанKZ
;
)be.lb#holiday@group.v.calendar.google.com
ЛіванLB
G
)be.li#holiday@group.v.calendar.google.comЛіхтэнштэйнLI
B
)be.lk#holiday@group.v.calendar.google.comШры-ЛанкаLK
?
)be.lr#holiday@group.v.calendar.google.comЛіберыяLR
=
)be.ls#holiday@group.v.calendar.google.comЛесотаLS
C
1be.lithuanian#holiday@group.v.calendar.google.com
ЛітваLT
E
)be.lu#holiday@group.v.calendar.google.comЛюксембургLU
B
.be.latvian#holiday@group.v.calendar.google.comЛатвіяLV
;
)be.ly#holiday@group.v.calendar.google.com
ЛівіяLY
=
)be.ma#holiday@group.v.calendar.google.comМарокаMA
=
)be.mc#holiday@group.v.calendar.google.comМанакаMC
?
)be.md#holiday@group.v.calendar.google.comМалдоваMD
E
)be.me#holiday@group.v.calendar.google.comЧарнагорыяME
E
)be.mg#holiday@group.v.calendar.google.comМадагаскарMG
C
)be.mk#holiday@group.v.calendar.google.comМакедоніяMK
9
)be.ml#holiday@group.v.calendar.google.comМаліML
A
)be.mn#holiday@group.v.calendar.google.comМанголіяMN
;
)be.mo#holiday@group.v.calendar.google.com
МакааMO
C
)be.mq#holiday@group.v.calendar.google.comМарцінікаMQ
=
)be.mt#holiday@group.v.calendar.google.comМальтаMT
A
)be.mu#holiday@group.v.calendar.google.comМаўрыкійMU
=
)be.mw#holiday@group.v.calendar.google.comМалавіMW
D
.be.mexican#holiday@group.v.calendar.google.comМексікаMX
G
/be.malaysia#holiday@group.v.calendar.google.comМалайзіяMY
A
)be.mz#holiday@group.v.calendar.google.comМазамбікMZ
?
)be.na#holiday@group.v.calendar.google.comНамібіяNA
;
)be.ne#holiday@group.v.calendar.google.com
НігерNE
?
)be.ng#holiday@group.v.calendar.google.comНігерыяNG
C
)be.ni#holiday@group.v.calendar.google.comНікарагуаNI
H
,be.dutch#holiday@group.v.calendar.google.comНідэрландыNL
H
0be.norwegian#holiday@group.v.calendar.google.comНарвегіяNO
;
)be.np#holiday@group.v.calendar.google.com
НепалNP
U
2be.new_zealand#holiday@group.v.calendar.google.comНовая ЗеландыяNZ
9
)be.om#holiday@group.v.calendar.google.comАманOM
=
)be.pa#holiday@group.v.calendar.google.comПанамаPA
9
)be.pe#holiday@group.v.calendar.google.comПеруPE
J
2be.philippines#holiday@group.v.calendar.google.comФіліпіныPH
A
)be.pk#holiday@group.v.calendar.google.comПакістанPK
C
-be.polish#holiday@group.v.calendar.google.comПольшчаPL
F
)be.pr#holiday@group.v.calendar.google.comПуэрта-РыкаPR
M
1be.portuguese#holiday@group.v.calendar.google.comПартугаліяPT
A
)be.py#holiday@group.v.calendar.google.comПарагвайPY
;
)be.qa#holiday@group.v.calendar.google.com
КатарQA
?
)be.re#holiday@group.v.calendar.google.comРэюньёнRE
E
/be.romanian#holiday@group.v.calendar.google.comРумыніяRO
=
)be.rs#holiday@group.v.calendar.google.comСербіяRS
@
.be.russian#holiday@group.v.calendar.google.com
РасіяRU
=
)be.rw#holiday@group.v.calendar.google.comРуандаRW
\
3be.saudiarabian#holiday@group.v.calendar.google.com!Саудаўская АравіяSA
V
)be.sc#holiday@group.v.calendar.google.com%Сейшэльскія АстравыSC
;
)be.sd#holiday@group.v.calendar.google.com
СуданSD
B
.be.swedish#holiday@group.v.calendar.google.comШвецыяSE
H
0be.singapore#holiday@group.v.calendar.google.comСінгапурSG
W
)be.sh#holiday@group.v.calendar.google.com&Востраў Святой АленыSH
H
0be.slovenian#holiday@group.v.calendar.google.comСлавеніяSI
E
-be.slovak#holiday@group.v.calendar.google.comСлавакіяSK
F
)be.sl#holiday@group.v.calendar.google.comСьера-ЛеонэSL
D
)be.sm#holiday@group.v.calendar.google.comСан-МарынаSM
?
)be.sn#holiday@group.v.calendar.google.comСенегалSN
=
)be.so#holiday@group.v.calendar.google.comСамаліSO
?
)be.sr#holiday@group.v.calendar.google.comСурынамSR
L
)be.ss#holiday@group.v.calendar.google.comПаўднёвы СуданSS
T
)be.st#holiday@group.v.calendar.google.com#Сан-Тамэ і ПрынсіпіST
C
)be.sv#holiday@group.v.calendar.google.comСальвадорSV
;
)be.sy#holiday@group.v.calendar.google.com
СірыяSY
C
)be.sz#holiday@group.v.calendar.google.comСвазілендSZ
7
)be.td#holiday@group.v.calendar.google.comЧадTD
9
)be.tg#holiday@group.v.calendar.google.comТогаTG
?
)be.th#holiday@group.v.calendar.google.comТайландTH
;
)be.tn#holiday@group.v.calendar.google.com
ТунісTN
B
.be.turkish#holiday@group.v.calendar.google.comТурцыяTR
Q
)be.tt#holiday@group.v.calendar.google.com Трынідад і ТабагаTT
C
-be.taiwan#holiday@group.v.calendar.google.comТайваньTW
A
)be.tz#holiday@group.v.calendar.google.comТанзаніяTZ
F
0be.ukrainian#holiday@group.v.calendar.google.comУкраінаUA
=
)be.ug#holiday@group.v.calendar.google.comУгандаUG
\
*be.usa#holiday@group.v.calendar.google.com*Злучаныя Штаты АмерыкіUS
?
)be.uy#holiday@group.v.calendar.google.comУругвайUY
E
)be.uz#holiday@group.v.calendar.google.comУзбекістанUZ
?
)be.va#holiday@group.v.calendar.google.comВатыканVA
C
)be.ve#holiday@group.v.calendar.google.comВенесуэлаVE
m
)be.vi#holiday@group.v.calendar.google.com<Амерыканскія Віргінскія астравыVI
H
1be.vietnamese#holiday@group.v.calendar.google.comВ’етнамVN
9
)be.ye#holiday@group.v.calendar.google.comЕменYE
;
)be.yt#holiday@group.v.calendar.google.com
МаётаYT
l
)be.sa#holiday@group.v.calendar.google.com;Паўднёваафрыканская РэспублікаZA
=
)be.zm#holiday@group.v.calendar.google.comЗамбіяZM
A
)be.zw#holiday@group.v.calendar.google.comЗімбабвэZWF
0be.christian#holiday@group.v.calendar.google.comChristian HolidaysA
.be.judaism#holiday@group.v.calendar.google.comJewish HolidaysA
.be.islamic#holiday@group.v.calendar.google.comMuslim HolidaysQ
<be.orthodox_christianity#holiday@group.v.calendar.google.comOrthodox Holidaysbe