
8
)no.ad#holiday@group.v.calendar.google.comAndorraAD
M
)no.ae#holiday@group.v.calendar.google.comDe forente arabiske emiraterAE
<
)no.af#holiday@group.v.calendar.google.comAfghanistanAF
8
)no.al#holiday@group.v.calendar.google.comAlbaniaAL
8
)no.am#holiday@group.v.calendar.google.comArmeniaAM
7
)no.ao#holiday@group.v.calendar.google.comAngolaAO
:
)no.ar#holiday@group.v.calendar.google.com	ArgentinaAR
A
/no.austrian#holiday@group.v.calendar.google.com
ØsterrikeAT
B
1no.australian#holiday@group.v.calendar.google.com	AustraliaAU
6
)no.aw#holiday@group.v.calendar.google.comArubaAW
=
)no.az#holiday@group.v.calendar.google.comAserbajdsjanAZ
C
)no.ba#holiday@group.v.calendar.google.comBosnia-HercegovinaBA
9
)no.bb#holiday@group.v.calendar.google.comBarbadosBB
;
)no.bd#holiday@group.v.calendar.google.com
BangladeshBD
7
)no.be#holiday@group.v.calendar.google.comBelgiaBE
=
)no.bf#holiday@group.v.calendar.google.comBurkina FasoBF
@
0no.bulgarian#holiday@group.v.calendar.google.comBulgariaBG
8
)no.bh#holiday@group.v.calendar.google.comBahrainBH
8
)no.bi#holiday@group.v.calendar.google.comBurundiBI
6
)no.bj#holiday@group.v.calendar.google.comBeninBJ
8
)no.bm#holiday@group.v.calendar.google.comBermudaBM
8
)no.bo#holiday@group.v.calendar.google.comBoliviaBO
>
0no.brazilian#holiday@group.v.calendar.google.comBrasilBR
8
)no.bs#holiday@group.v.calendar.google.comBahamasBS
9
)no.bw#holiday@group.v.calendar.google.comBotswanaBW
>
)no.by#holiday@group.v.calendar.google.comHviterusslandBY
=
/no.canadian#holiday@group.v.calendar.google.comCanadaCA
?
)no.cd#holiday@group.v.calendar.google.comKongo-KinshasaCD
P
)no.cf#holiday@group.v.calendar.google.comDen sentralafrikanske republikkCF
B
)no.cg#holiday@group.v.calendar.google.comKongo-BrazzavilleCG
7
)no.ch#holiday@group.v.calendar.google.comSveitsCH
@
)no.ci#holiday@group.v.calendar.google.comElfenbenskystenCI
6
)no.cl#holiday@group.v.calendar.google.comChileCL
8
)no.cm#holiday@group.v.calendar.google.comKamerunCM
8
,no.china#holiday@group.v.calendar.google.comKinaCN
9
)no.co#holiday@group.v.calendar.google.comColombiaCO
;
)no.cr#holiday@group.v.calendar.google.com
Costa RicaCR
5
)no.cu#holiday@group.v.calendar.google.comCubaCU
;
)no.cv#holiday@group.v.calendar.google.com
Kapp VerdeCV
7
)no.cy#holiday@group.v.calendar.google.comKyprosCY
L
,no.czech#holiday@group.v.calendar.google.comDen tsjekkiske republikkCZ
=
-no.german#holiday@group.v.calendar.google.comTysklandDE
<
-no.danish#holiday@group.v.calendar.google.comDanmarkDK
K
)no.do#holiday@group.v.calendar.google.comDen dominikanske republikkDO
8
)no.dz#holiday@group.v.calendar.google.comAlgerieDZ
8
)no.ec#holiday@group.v.calendar.google.comEcuadorEC
8
)no.ee#holiday@group.v.calendar.google.comEstlandEE
6
)no.eg#holiday@group.v.calendar.google.comEgyptEG
8
)no.er#holiday@group.v.calendar.google.comEritreaER
:
,no.spain#holiday@group.v.calendar.google.comSpaniaES
8
)no.et#holiday@group.v.calendar.google.comEtiopiaET
=
.no.finnish#holiday@group.v.calendar.google.comFinlandFI
5
)no.fj#holiday@group.v.calendar.google.comFijiFJ
;
)no.fo#holiday@group.v.calendar.google.com
FærøyeneFO
>
-no.french#holiday@group.v.calendar.google.com	FrankrikeFR
6
)no.ga#holiday@group.v.calendar.google.comGabonGA
>
)no.uk#holiday@group.v.calendar.google.comStorbritanniaGB
8
)no.gd#holiday@group.v.calendar.google.comGrenadaGD
8
)no.ge#holiday@group.v.calendar.google.comGeorgiaGE
6
)no.gh#holiday@group.v.calendar.google.comGhanaGH
:
)no.gi#holiday@group.v.calendar.google.com	GibraltarGI
:
)no.gl#holiday@group.v.calendar.google.com	GrønlandGL
7
)no.gm#holiday@group.v.calendar.google.comGambiaGM
7
)no.gn#holiday@group.v.calendar.google.comGuineaGN
B
)no.gq#holiday@group.v.calendar.google.comEkvatorial-GuineaGQ
:
,no.greek#holiday@group.v.calendar.google.comHellasGR
:
)no.gt#holiday@group.v.calendar.google.com	GuatemalaGT
5
)no.gu#holiday@group.v.calendar.google.comGuamGU
>
)no.gw#holiday@group.v.calendar.google.comGuinea-BissauGW
@
0no.hong_kong#holiday@group.v.calendar.google.comHongkongHK
9
)no.hn#holiday@group.v.calendar.google.comHondurasHN
>
/no.croatian#holiday@group.v.calendar.google.comKroatiaHR
6
)no.ht#holiday@group.v.calendar.google.comHaitiHT
>
0no.hungarian#holiday@group.v.calendar.google.comUngarnHU
B
1no.indonesian#holiday@group.v.calendar.google.com	IndonesiaID
:
,no.irish#holiday@group.v.calendar.google.comIrlandIE
;
-no.jewish#holiday@group.v.calendar.google.comIsraelIL
:
-no.indian#holiday@group.v.calendar.google.comIndiaIN
5
)no.iq#holiday@group.v.calendar.google.comIrakIQ
5
)no.ir#holiday@group.v.calendar.google.comIranIR
7
)no.is#holiday@group.v.calendar.google.comIslandIS
<
.no.italian#holiday@group.v.calendar.google.comItaliaIT
8
)no.jm#holiday@group.v.calendar.google.comJamaicaJM
7
)no.jo#holiday@group.v.calendar.google.comJordanJO
<
/no.japanese#holiday@group.v.calendar.google.comJapanJP
6
)no.ke#holiday@group.v.calendar.google.comKenyaKE
<
)no.kg#holiday@group.v.calendar.google.comKirgisistanKG
:
)no.kh#holiday@group.v.calendar.google.com	KambodsjaKH
9
)no.km#holiday@group.v.calendar.google.comKomoreneKM
;
)no.kp#holiday@group.v.calendar.google.com
Nord-KoreaKP
D
2no.south_korea#holiday@group.v.calendar.google.com
Sør-KoreaKR
7
)no.kw#holiday@group.v.calendar.google.comKuwaitKW
=
)no.ky#holiday@group.v.calendar.google.comCaymanøyeneKY
;
)no.kz#holiday@group.v.calendar.google.com
KasakhstanKZ
8
)no.lb#holiday@group.v.calendar.google.comLibanonLB
>
)no.li#holiday@group.v.calendar.google.comLiechtensteinLI
:
)no.lk#holiday@group.v.calendar.google.com	Sri LankaLK
8
)no.lr#holiday@group.v.calendar.google.comLiberiaLR
8
)no.ls#holiday@group.v.calendar.google.comLesothoLS
@
1no.lithuanian#holiday@group.v.calendar.google.comLitauenLT
:
)no.lu#holiday@group.v.calendar.google.com	LuxemburgLU
<
.no.latvian#holiday@group.v.calendar.google.comLatviaLV
6
)no.ly#holiday@group.v.calendar.google.comLibyaLY
8
)no.ma#holiday@group.v.calendar.google.comMarokkoMA
7
)no.mc#holiday@group.v.calendar.google.comMonacoMC
8
)no.md#holiday@group.v.calendar.google.comMoldovaMD
;
)no.me#holiday@group.v.calendar.google.com
MontenegroME
;
)no.mg#holiday@group.v.calendar.google.com
MadagaskarMG
:
)no.mk#holiday@group.v.calendar.google.com	MakedoniaMK
5
)no.ml#holiday@group.v.calendar.google.comMaliML
9
)no.mn#holiday@group.v.calendar.google.comMongoliaMN
6
)no.mo#holiday@group.v.calendar.google.comMacaoMO
;
)no.mq#holiday@group.v.calendar.google.com
MartiniqueMQ
6
)no.mt#holiday@group.v.calendar.google.comMaltaMT
:
)no.mu#holiday@group.v.calendar.google.com	MauritiusMU
7
)no.mw#holiday@group.v.calendar.google.comMalawiMW
<
.no.mexican#holiday@group.v.calendar.google.comMexicoMX
?
/no.malaysia#holiday@group.v.calendar.google.comMalaysiaMY
9
)no.mz#holiday@group.v.calendar.google.comMosambikMZ
8
)no.na#holiday@group.v.calendar.google.comNamibiaNA
6
)no.ne#holiday@group.v.calendar.google.comNigerNE
8
)no.ng#holiday@group.v.calendar.google.comNigeriaNG
:
)no.ni#holiday@group.v.calendar.google.com	NicaraguaNI
=
,no.dutch#holiday@group.v.calendar.google.com	NederlandNL
=
0no.norwegian#holiday@group.v.calendar.google.comNorgeNO
6
)no.np#holiday@group.v.calendar.google.comNepalNP
E
2no.new_zealand#holiday@group.v.calendar.google.comNew ZealandNZ
5
)no.om#holiday@group.v.calendar.google.comOmanOM
7
)no.pa#holiday@group.v.calendar.google.comPanamaPA
5
)no.pe#holiday@group.v.calendar.google.comPeruPE
E
2no.philippines#holiday@group.v.calendar.google.comFilippinenePH
9
)no.pk#holiday@group.v.calendar.google.comPakistanPK
:
-no.polish#holiday@group.v.calendar.google.comPolenPL
<
)no.pr#holiday@group.v.calendar.google.comPuerto RicoPR
A
1no.portuguese#holiday@group.v.calendar.google.comPortugalPT
9
)no.py#holiday@group.v.calendar.google.comParaguayPY
6
)no.qa#holiday@group.v.calendar.google.comQatarQA
9
)no.re#holiday@group.v.calendar.google.comRéunionRE
>
/no.romanian#holiday@group.v.calendar.google.comRomaniaRO
7
)no.rs#holiday@group.v.calendar.google.comSerbiaRS
>
.no.russian#holiday@group.v.calendar.google.comRusslandRU
7
)no.rw#holiday@group.v.calendar.google.comRwandaRW
G
3no.saudiarabian#holiday@group.v.calendar.google.comSaudi-ArabiaSA
<
)no.sc#holiday@group.v.calendar.google.comSeychelleneSC
6
)no.sd#holiday@group.v.calendar.google.comSudanSD
=
.no.swedish#holiday@group.v.calendar.google.comSverigeSE
A
0no.singapore#holiday@group.v.calendar.google.com	SingaporeSG
;
)no.sh#holiday@group.v.calendar.google.com
St. HelenaSH
@
0no.slovenian#holiday@group.v.calendar.google.comSloveniaSI
=
-no.slovak#holiday@group.v.calendar.google.comSlovakiaSK
=
)no.sl#holiday@group.v.calendar.google.comSierra LeoneSL
;
)no.sm#holiday@group.v.calendar.google.com
San MarinoSM
8
)no.sn#holiday@group.v.calendar.google.comSenegalSN
8
)no.so#holiday@group.v.calendar.google.comSomaliaSO
8
)no.sr#holiday@group.v.calendar.google.comSurinamSR
;
)no.ss#holiday@group.v.calendar.google.com
Sør-SudanSS
H
)no.st#holiday@group.v.calendar.google.comSão Tomé og PríncipeST
<
)no.sv#holiday@group.v.calendar.google.comEl SalvadorSV
6
)no.sy#holiday@group.v.calendar.google.comSyriaSY
:
)no.sz#holiday@group.v.calendar.google.com	SwazilandSZ
6
)no.td#holiday@group.v.calendar.google.comTsjadTD
5
)no.tg#holiday@group.v.calendar.google.comTogoTG
9
)no.th#holiday@group.v.calendar.google.comThailandTH
8
)no.tn#holiday@group.v.calendar.google.comTunisiaTN
<
.no.turkish#holiday@group.v.calendar.google.comTyrkiaTR
C
)no.tt#holiday@group.v.calendar.google.comTrinidad og TobagoTT
;
-no.taiwan#holiday@group.v.calendar.google.comTaiwanTW
9
)no.tz#holiday@group.v.calendar.google.comTanzaniaTZ
?
0no.ukrainian#holiday@group.v.calendar.google.comUkrainaUA
7
)no.ug#holiday@group.v.calendar.google.comUgandaUG
5
*no.usa#holiday@group.v.calendar.google.comUSAUS
8
)no.uy#holiday@group.v.calendar.google.comUruguayUY
;
)no.uz#holiday@group.v.calendar.google.com
UsbekistanUZ
>
)no.va#holiday@group.v.calendar.google.comVatikanstatenVA
:
)no.ve#holiday@group.v.calendar.google.com	VenezuelaVE
L
)no.vi#holiday@group.v.calendar.google.comDe amerikanske jomfruøyeneVI
@
1no.vietnamese#holiday@group.v.calendar.google.comVietnamVN
6
)no.ye#holiday@group.v.calendar.google.comJemenYE
8
)no.yt#holiday@group.v.calendar.google.comMayotteYT
<
)no.sa#holiday@group.v.calendar.google.comSør-AfrikaZA
7
)no.zm#holiday@group.v.calendar.google.comZambiaZM
9
)no.zw#holiday@group.v.calendar.google.comZimbabweZWG
0no.christian#holiday@group.v.calendar.google.comKristne helligdagerF
.no.judaism#holiday@group.v.calendar.google.comJødiske helligdagerG
.no.islamic#holiday@group.v.calendar.google.comMuslimske helligdagerU
<no.orthodox_christianity#holiday@group.v.calendar.google.comOrtodokse helligdagernb