
=
)ar.ad#holiday@group.v.calendar.google.comأندوراAD
_
)ar.ae#holiday@group.v.calendar.google.com.الإمارات العربية المتحدةAE
C
)ar.af#holiday@group.v.calendar.google.comأفغانستانAF
?
)ar.al#holiday@group.v.calendar.google.comألبانياAL
?
)ar.am#holiday@group.v.calendar.google.comأرمينياAM
=
)ar.ao#holiday@group.v.calendar.google.comأنغولاAO
C
)ar.ar#holiday@group.v.calendar.google.comالأرجنتينAR
C
/ar.austrian#holiday@group.v.calendar.google.comالنمساAT
I
1ar.australian#holiday@group.v.calendar.google.comأسترالياAU
;
)ar.aw#holiday@group.v.calendar.google.com
أروباAW
A
)ar.az#holiday@group.v.calendar.google.comأذربيجانAZ
N
)ar.ba#holiday@group.v.calendar.google.comالبوسنة والهرسكBA
?
)ar.bb#holiday@group.v.calendar.google.comبربادوسBB
A
)ar.bd#holiday@group.v.calendar.google.comبنغلاديشBD
=
)ar.be#holiday@group.v.calendar.google.comبلجيكاBE
H
)ar.bf#holiday@group.v.calendar.google.comبوركينا فاسوBF
F
0ar.bulgarian#holiday@group.v.calendar.google.comبلغارياBG
?
)ar.bh#holiday@group.v.calendar.google.comالبحرينBH
?
)ar.bi#holiday@group.v.calendar.google.comبورونديBI
9
)ar.bj#holiday@group.v.calendar.google.comبنينBJ
=
)ar.bm#holiday@group.v.calendar.google.comبرموداBM
?
)ar.bo#holiday@group.v.calendar.google.comبوليفياBO
H
0ar.brazilian#holiday@group.v.calendar.google.comالبرازيلBR
?
)ar.bs#holiday@group.v.calendar.google.comالبهاماBS
?
)ar.bw#holiday@group.v.calendar.google.comبتسواناBW
?
)ar.by#holiday@group.v.calendar.google.comبيلاروسBY
?
/ar.canadian#holiday@group.v.calendar.google.comكنداCA
P
)ar.cd#holiday@group.v.calendar.google.comالكونغو - كينشاساCD
[
)ar.cf#holiday@group.v.calendar.google.com*جمهورية أفريقيا الوسطىCF
R
)ar.cg#holiday@group.v.calendar.google.com!الكونغو - برازافيلCG
=
)ar.ch#holiday@group.v.calendar.google.comسويسراCH
D
)ar.ci#holiday@group.v.calendar.google.comساحل العاجCI
;
)ar.cl#holiday@group.v.calendar.google.com
تشيليCL
C
)ar.cm#holiday@group.v.calendar.google.comالكاميرونCM
>
,ar.china#holiday@group.v.calendar.google.com
الصينCN
A
)ar.co#holiday@group.v.calendar.google.comكولومبياCO
C
)ar.cr#holiday@group.v.calendar.google.comكوستاريكاCR
9
)ar.cu#holiday@group.v.calendar.google.comكوباCU
H
)ar.cv#holiday@group.v.calendar.google.comالرأس الأخضرCV
9
)ar.cy#holiday@group.v.calendar.google.comقبرصCY
O
,ar.czech#holiday@group.v.calendar.google.comجمهورية التشيكCZ
C
-ar.german#holiday@group.v.calendar.google.comألمانياDE
E
-ar.danish#holiday@group.v.calendar.google.comالدانمركDK
V
)ar.do#holiday@group.v.calendar.google.com%جمهورية الدومينيكانDO
?
)ar.dz#holiday@group.v.calendar.google.comالجزائرDZ
C
)ar.ec#holiday@group.v.calendar.google.comالإكوادورEC
?
)ar.ee#holiday@group.v.calendar.google.comإستونياEE
7
)ar.eg#holiday@group.v.calendar.google.comمصرEG
?
)ar.er#holiday@group.v.calendar.google.comإريترياER
B
,ar.spain#holiday@group.v.calendar.google.comإسبانياES
?
)ar.et#holiday@group.v.calendar.google.comإثيوبياET
B
.ar.finnish#holiday@group.v.calendar.google.comفنلنداFI
9
)ar.fj#holiday@group.v.calendar.google.comفيجيFJ
@
)ar.fo#holiday@group.v.calendar.google.comجزر فاروFO
?
-ar.french#holiday@group.v.calendar.google.com
فرنساFR
?
)ar.ga#holiday@group.v.calendar.google.comالغابونGA
N
)ar.uk#holiday@group.v.calendar.google.comالمملكة المتحدةGB
?
)ar.gd#holiday@group.v.calendar.google.comغريناداGD
=
)ar.ge#holiday@group.v.calendar.google.comجورجياGE
9
)ar.gh#holiday@group.v.calendar.google.comغاناGH
@
)ar.gi#holiday@group.v.calendar.google.comجبل طارقGI
A
)ar.gl#holiday@group.v.calendar.google.comغرينلاندGL
=
)ar.gm#holiday@group.v.calendar.google.comغامبياGM
;
)ar.gn#holiday@group.v.calendar.google.com
غينياGN
P
)ar.gq#holiday@group.v.calendar.google.comغينيا الاستوائيةGQ
B
,ar.greek#holiday@group.v.calendar.google.comاليونانGR
C
)ar.gt#holiday@group.v.calendar.google.comغواتيمالاGT
9
)ar.gu#holiday@group.v.calendar.google.comغوامGU
F
)ar.gw#holiday@group.v.calendar.google.comغينيا بيساوGW
I
0ar.hong_kong#holiday@group.v.calendar.google.comهونغ كونغHK
?
)ar.hn#holiday@group.v.calendar.google.comهندوراسHN
E
/ar.croatian#holiday@group.v.calendar.google.comكرواتياHR
;
)ar.ht#holiday@group.v.calendar.google.com
هايتيHT
F
0ar.hungarian#holiday@group.v.calendar.google.comهنغارياHU
K
1ar.indonesian#holiday@group.v.calendar.google.comإندونيسياID
B
,ar.irish#holiday@group.v.calendar.google.comأيرلنداIE
C
-ar.jewish#holiday@group.v.calendar.google.comإسرائيلIL
?
-ar.indian#holiday@group.v.calendar.google.com
الهندIN
=
)ar.iq#holiday@group.v.calendar.google.comالعراقIQ
;
)ar.ir#holiday@group.v.calendar.google.com
إيرانIR
?
)ar.is#holiday@group.v.calendar.google.comأيسلنداIS
D
.ar.italian#holiday@group.v.calendar.google.comإيطالياIT
?
)ar.jm#holiday@group.v.calendar.google.comجامايكاJM
=
)ar.jo#holiday@group.v.calendar.google.comالأردنJO
E
/ar.japanese#holiday@group.v.calendar.google.comاليابانJP
;
)ar.ke#holiday@group.v.calendar.google.com
كينياKE
E
)ar.kg#holiday@group.v.calendar.google.comقيرغيزستانKG
?
)ar.kh#holiday@group.v.calendar.google.comكمبودياKH
B
)ar.km#holiday@group.v.calendar.google.comجزر القمرKM
L
)ar.kp#holiday@group.v.calendar.google.comكوريا الشماليةKP
U
2ar.south_korea#holiday@group.v.calendar.google.comكوريا الجنوبيةKR
=
)ar.kw#holiday@group.v.calendar.google.comالكويتKW
D
)ar.ky#holiday@group.v.calendar.google.comجزر كايمانKY
C
)ar.kz#holiday@group.v.calendar.google.comكازاخستانKZ
;
)ar.lb#holiday@group.v.calendar.google.com
لبنانLB
E
)ar.li#holiday@group.v.calendar.google.comليختنشتاينLI
A
)ar.lk#holiday@group.v.calendar.google.comسريلانكاLK
?
)ar.lr#holiday@group.v.calendar.google.comليبيرياLR
=
)ar.ls#holiday@group.v.calendar.google.comليسوتوLS
I
1ar.lithuanian#holiday@group.v.calendar.google.comليتوانياLT
C
)ar.lu#holiday@group.v.calendar.google.comلوكسمبورغLU
B
.ar.latvian#holiday@group.v.calendar.google.comلاتفياLV
;
)ar.ly#holiday@group.v.calendar.google.com
ليبياLY
=
)ar.ma#holiday@group.v.calendar.google.comالمغربMA
=
)ar.mc#holiday@group.v.calendar.google.comموناكوMC
?
)ar.md#holiday@group.v.calendar.google.comمولدوفاMD
H
)ar.me#holiday@group.v.calendar.google.comالجبل الأسودME
=
)ar.mg#holiday@group.v.calendar.google.comمدغشقرMG
?
)ar.mk#holiday@group.v.calendar.google.comمقدونياMK
9
)ar.ml#holiday@group.v.calendar.google.comماليML
?
)ar.mn#holiday@group.v.calendar.google.comمنغولياMN
9
)ar.mo#holiday@group.v.calendar.google.comمكاوMO
L
)ar.mq#holiday@group.v.calendar.google.comجزر المارتينيكMQ
;
)ar.mt#holiday@group.v.calendar.google.com
مالطاMT
A
)ar.mu#holiday@group.v.calendar.google.comموريشيوسMU
;
)ar.mw#holiday@group.v.calendar.google.com
ملاويMW
D
.ar.mexican#holiday@group.v.calendar.google.comالمكسيكMX
E
/ar.malaysia#holiday@group.v.calendar.google.comماليزياMY
?
)ar.mz#holiday@group.v.calendar.google.comموزمبيقMZ
?
)ar.na#holiday@group.v.calendar.google.comناميبياNA
=
)ar.ne#holiday@group.v.calendar.google.comالنيجرNE
?
)ar.ng#holiday@group.v.calendar.google.comنيجيرياNG
C
)ar.ni#holiday@group.v.calendar.google.comنيكاراغواNI
@
,ar.dutch#holiday@group.v.calendar.google.comهولنداNL
F
0ar.norwegian#holiday@group.v.calendar.google.comالنرويجNO
;
)ar.np#holiday@group.v.calendar.google.com
نيبالNP
L
2ar.new_zealand#holiday@group.v.calendar.google.comنيوزيلنداNZ
;
)ar.om#holiday@group.v.calendar.google.com
عُمانOM
9
)ar.pa#holiday@group.v.calendar.google.comبنماPA
9
)ar.pe#holiday@group.v.calendar.google.comبيروPE
H
2ar.philippines#holiday@group.v.calendar.google.comالفلبينPH
?
)ar.pk#holiday@group.v.calendar.google.comباكستانPK
A
-ar.polish#holiday@group.v.calendar.google.comبولنداPL
C
)ar.pr#holiday@group.v.calendar.google.comبورتوريكوPR
I
1ar.portuguese#holiday@group.v.calendar.google.comالبرتغالPT
A
)ar.py#holiday@group.v.calendar.google.comباراغوايPY
7
)ar.qa#holiday@group.v.calendar.google.comقطرQA
?
)ar.re#holiday@group.v.calendar.google.comروينيونRE
E
/ar.romanian#holiday@group.v.calendar.google.comرومانياRO
;
)ar.rs#holiday@group.v.calendar.google.com
صربياRS
@
.ar.russian#holiday@group.v.calendar.google.com
روسياRU
=
)ar.rw#holiday@group.v.calendar.google.comروانداRW
i
3ar.saudiarabian#holiday@group.v.calendar.google.com.المملكة العربية السعوديةSA
9
)ar.sc#holiday@group.v.calendar.google.comسيشلSC
?
)ar.sd#holiday@group.v.calendar.google.comالسودانSD
B
.ar.swedish#holiday@group.v.calendar.google.comالسويدSE
H
0ar.singapore#holiday@group.v.calendar.google.comسنغافورةSG
F
)ar.sh#holiday@group.v.calendar.google.comسانت هيلانةSH
H
0ar.slovenian#holiday@group.v.calendar.google.comسلوفينياSI
E
-ar.slovak#holiday@group.v.calendar.google.comسلوفاكياSK
A
)ar.sl#holiday@group.v.calendar.google.comسيراليونSL
D
)ar.sm#holiday@group.v.calendar.google.comسان مارينوSM
?
)ar.sn#holiday@group.v.calendar.google.comالسنغالSN
?
)ar.so#holiday@group.v.calendar.google.comالصومالSO
?
)ar.sr#holiday@group.v.calendar.google.comسورينامSR
H
)ar.ss#holiday@group.v.calendar.google.comجنوب السودانSS
S
)ar.st#holiday@group.v.calendar.google.com"ساو تومي وبرينسيبيST
C
)ar.sv#holiday@group.v.calendar.google.comالسلفادورSV
;
)ar.sy#holiday@group.v.calendar.google.com
سورياSY
C
)ar.sz#holiday@group.v.calendar.google.comسوازيلاندSZ
9
)ar.td#holiday@group.v.calendar.google.comتشادTD
9
)ar.tg#holiday@group.v.calendar.google.comتوغوTG
?
)ar.th#holiday@group.v.calendar.google.comتايلاندTH
9
)ar.tn#holiday@group.v.calendar.google.comتونسTN
@
.ar.turkish#holiday@group.v.calendar.google.com
تركياTR
P
)ar.tt#holiday@group.v.calendar.google.comترينيداد وتوباغوTT
A
-ar.taiwan#holiday@group.v.calendar.google.comتايوانTW
?
)ar.tz#holiday@group.v.calendar.google.comتنزانياTZ
H
0ar.ukrainian#holiday@group.v.calendar.google.comأوكرانياUA
=
)ar.ug#holiday@group.v.calendar.google.comأوغنداUG
Q
*ar.usa#holiday@group.v.calendar.google.comالولايات المتحدةUS
?
)ar.uy#holiday@group.v.calendar.google.comأورغوايUY
C
)ar.uz#holiday@group.v.calendar.google.comأوزبكستانUZ
C
)ar.va#holiday@group.v.calendar.google.comالفاتيكانVA
?
)ar.ve#holiday@group.v.calendar.google.comفنزويلاVE
q
)ar.vi#holiday@group.v.calendar.google.com@جزر فيرجن التابعة للولايات المتحدةVI
E
1ar.vietnamese#holiday@group.v.calendar.google.comفيتنامVN
;
)ar.ye#holiday@group.v.calendar.google.com
اليمنYE
;
)ar.yt#holiday@group.v.calendar.google.com
مايوتYT
H
)ar.sa#holiday@group.v.calendar.google.comجنوب أفريقياZA
=
)ar.zm#holiday@group.v.calendar.google.comزامبياZM
A
)ar.zw#holiday@group.v.calendar.google.comزيمبابويZWS
0ar.christian#holiday@group.v.calendar.google.comالأعياد المسيحيةQ
.ar.judaism#holiday@group.v.calendar.google.comالأعياد اليهوديةS
.ar.islamic#holiday@group.v.calendar.google.com!الأعياد الإسلاميةe
<ar.orthodox_christianity#holiday@group.v.calendar.google.com%الأعياد الأرثوذكسيةar