
?
)uk.ad#holiday@group.v.calendar.google.comАндорраAD
c
)uk.ae#holiday@group.v.calendar.google.com2Обʼєднані Арабські ЕміратиAE
E
)uk.af#holiday@group.v.calendar.google.comАфганістанAF
?
)uk.al#holiday@group.v.calendar.google.comАлбаніяAL
A
)uk.am#holiday@group.v.calendar.google.comВірменіяAM
=
)uk.ao#holiday@group.v.calendar.google.comАнголаAO
C
)uk.ar#holiday@group.v.calendar.google.comАргентинаAR
E
/uk.austrian#holiday@group.v.calendar.google.comАвстріяAT
K
1uk.australian#holiday@group.v.calendar.google.comАвстраліяAU
;
)uk.aw#holiday@group.v.calendar.google.com
АрубаAW
G
)uk.az#holiday@group.v.calendar.google.comАзербайджанAZ
W
)uk.ba#holiday@group.v.calendar.google.com&Боснія і ГерцоговинаBA
A
)uk.bb#holiday@group.v.calendar.google.comБарбадосBB
C
)uk.bd#holiday@group.v.calendar.google.comБангладешBD
?
)uk.be#holiday@group.v.calendar.google.comБельгіяBE
H
)uk.bf#holiday@group.v.calendar.google.comБуркіна-ФасоBF
H
0uk.bulgarian#holiday@group.v.calendar.google.comБолгаріяBG
?
)uk.bh#holiday@group.v.calendar.google.comБахрейнBH
?
)uk.bi#holiday@group.v.calendar.google.comБурундіBI
;
)uk.bj#holiday@group.v.calendar.google.com
БенінBJ
T
)uk.bm#holiday@group.v.calendar.google.com#Бермудські островиBM
?
)uk.bo#holiday@group.v.calendar.google.comБолівіяBO
H
0uk.brazilian#holiday@group.v.calendar.google.comБразиліяBR
R
)uk.bs#holiday@group.v.calendar.google.com!Багамські ОстровиBS
A
)uk.bw#holiday@group.v.calendar.google.comБотсванаBW
A
)uk.by#holiday@group.v.calendar.google.comБілорусьBY
C
/uk.canadian#holiday@group.v.calendar.google.comКанадаCA
N
)uk.cd#holiday@group.v.calendar.google.comКонго – КіншасаCD
p
)uk.cf#holiday@group.v.calendar.google.com?Центральноафриканська РеспублікаCF
T
)uk.cg#holiday@group.v.calendar.google.com#Конго – БраззавільCG
C
)uk.ch#holiday@group.v.calendar.google.comШвейцаріяCH
G
)uk.ci#holiday@group.v.calendar.google.comКот-д’ІвуарCI
9
)uk.cl#holiday@group.v.calendar.google.comЧиліCL
?
)uk.cm#holiday@group.v.calendar.google.comКамерунCM
>
,uk.china#holiday@group.v.calendar.google.com
КитайCN
A
)uk.co#holiday@group.v.calendar.google.comКолумбіяCO
D
)uk.cr#holiday@group.v.calendar.google.comКоста-РикаCR
9
)uk.cu#holiday@group.v.calendar.google.comКубаCU
D
)uk.cv#holiday@group.v.calendar.google.comКабо-ВердеCV
9
)uk.cy#holiday@group.v.calendar.google.comКіпрCY
U
,uk.czech#holiday@group.v.calendar.google.com!Чеська РеспублікаCZ
G
-uk.german#holiday@group.v.calendar.google.comНімеччинаDE
?
-uk.danish#holiday@group.v.calendar.google.com
ДаніяDK
`
)uk.do#holiday@group.v.calendar.google.com/Домініканська РеспублікаDO
;
)uk.dz#holiday@group.v.calendar.google.com
АлжирDZ
?
)uk.ec#holiday@group.v.calendar.google.comЕквадорEC
?
)uk.ee#holiday@group.v.calendar.google.comЕстоніяEE
=
)uk.eg#holiday@group.v.calendar.google.comЄгипетEG
?
)uk.er#holiday@group.v.calendar.google.comЕритреяER
B
,uk.spain#holiday@group.v.calendar.google.comІспаніяES
?
)uk.et#holiday@group.v.calendar.google.comЕфіопіяET
H
.uk.finnish#holiday@group.v.calendar.google.comФінляндіяFI
;
)uk.fj#holiday@group.v.calendar.google.com
ФіджіFJ
R
)uk.fo#holiday@group.v.calendar.google.com!Фарерські ОстровиFO
C
-uk.french#holiday@group.v.calendar.google.comФранціяFR
;
)uk.ga#holiday@group.v.calendar.google.com
ГабонGA
N
)uk.uk#holiday@group.v.calendar.google.comВелика БританіяGB
?
)uk.gd#holiday@group.v.calendar.google.comГренадаGD
=
)uk.ge#holiday@group.v.calendar.google.comГрузіяGE
9
)uk.gh#holiday@group.v.calendar.google.comГанаGH
C
)uk.gi#holiday@group.v.calendar.google.comГібралтарGI
E
)uk.gl#holiday@group.v.calendar.google.comГренландіяGL
=
)uk.gm#holiday@group.v.calendar.google.comГамбіяGM
=
)uk.gn#holiday@group.v.calendar.google.comГвінеяGN
X
)uk.gq#holiday@group.v.calendar.google.com'Екваторіальна ГвінеяGQ
@
,uk.greek#holiday@group.v.calendar.google.comГреціяGR
C
)uk.gt#holiday@group.v.calendar.google.comГватемалаGT
9
)uk.gu#holiday@group.v.calendar.google.comГуамGU
H
)uk.gw#holiday@group.v.calendar.google.comГвінея-БісауGW
F
0uk.hong_kong#holiday@group.v.calendar.google.comГонконгHK
A
)uk.hn#holiday@group.v.calendar.google.comГондурасHN
G
/uk.croatian#holiday@group.v.calendar.google.comХорватіяHR
;
)uk.ht#holiday@group.v.calendar.google.com
ГаїтіHT
H
0uk.hungarian#holiday@group.v.calendar.google.comУгорщинаHU
K
1uk.indonesian#holiday@group.v.calendar.google.comІндонезіяID
D
,uk.irish#holiday@group.v.calendar.google.comІрландіяIE
C
-uk.jewish#holiday@group.v.calendar.google.comІзраїльIL
?
-uk.indian#holiday@group.v.calendar.google.com
ІндіяIN
9
)uk.iq#holiday@group.v.calendar.google.comІракIQ
9
)uk.ir#holiday@group.v.calendar.google.comІранIR
A
)uk.is#holiday@group.v.calendar.google.comІсландіяIS
B
.uk.italian#holiday@group.v.calendar.google.comІталіяIT
=
)uk.jm#holiday@group.v.calendar.google.comЯмайкаJM
A
)uk.jo#holiday@group.v.calendar.google.comЙорданіяJO
C
/uk.japanese#holiday@group.v.calendar.google.comЯпоніяJP
;
)uk.ke#holiday@group.v.calendar.google.com
КеніяKE
E
)uk.kg#holiday@group.v.calendar.google.comКиргизстанKG
A
)uk.kh#holiday@group.v.calendar.google.comКамбоджаKH
R
)uk.km#holiday@group.v.calendar.google.com!Коморські островиKM
L
)uk.kp#holiday@group.v.calendar.google.comПівнічна КореяKP
U
2uk.south_korea#holiday@group.v.calendar.google.comПівденна КореяKR
=
)uk.kw#holiday@group.v.calendar.google.comКувейтKW
R
)uk.ky#holiday@group.v.calendar.google.com!Кайманові островиKY
C
)uk.kz#holiday@group.v.calendar.google.comКазахстанKZ
;
)uk.lb#holiday@group.v.calendar.google.com
ЛіванLB
G
)uk.li#holiday@group.v.calendar.google.comЛіхтенштейнLI
B
)uk.lk#holiday@group.v.calendar.google.comШрі-ЛанкаLK
?
)uk.lr#holiday@group.v.calendar.google.comЛіберіяLR
=
)uk.ls#holiday@group.v.calendar.google.comЛесотоLS
C
1uk.lithuanian#holiday@group.v.calendar.google.com
ЛитваLT
E
)uk.lu#holiday@group.v.calendar.google.comЛюксембургLU
B
.uk.latvian#holiday@group.v.calendar.google.comЛатвіяLV
;
)uk.ly#holiday@group.v.calendar.google.com
ЛівіяLY
?
)uk.ma#holiday@group.v.calendar.google.comМароккоMA
=
)uk.mc#holiday@group.v.calendar.google.comМонакоMC
?
)uk.md#holiday@group.v.calendar.google.comМолдоваMD
E
)uk.me#holiday@group.v.calendar.google.comЧорногоріяME
E
)uk.mg#holiday@group.v.calendar.google.comМадагаскарMG
C
)uk.mk#holiday@group.v.calendar.google.comМакедоніяMK
9
)uk.ml#holiday@group.v.calendar.google.comМаліML
A
)uk.mn#holiday@group.v.calendar.google.comМонголіяMN
;
)uk.mo#holiday@group.v.calendar.google.com
МакаоMO
C
)uk.mq#holiday@group.v.calendar.google.comМартинікаMQ
=
)uk.mt#holiday@group.v.calendar.google.comМальтаMT
A
)uk.mu#holiday@group.v.calendar.google.comМаврикійMU
=
)uk.mw#holiday@group.v.calendar.google.comМалавіMW
D
.uk.mexican#holiday@group.v.calendar.google.comМексикаMX
G
/uk.malaysia#holiday@group.v.calendar.google.comМалайзіяMY
A
)uk.mz#holiday@group.v.calendar.google.comМозамбікMZ
?
)uk.na#holiday@group.v.calendar.google.comНамібіяNA
;
)uk.ne#holiday@group.v.calendar.google.com
НігерNE
?
)uk.ng#holiday@group.v.calendar.google.comНігеріяNG
C
)uk.ni#holiday@group.v.calendar.google.comНікарагуаNI
H
,uk.dutch#holiday@group.v.calendar.google.comНідерландиNL
H
0uk.norwegian#holiday@group.v.calendar.google.comНорвегіяNO
;
)uk.np#holiday@group.v.calendar.google.com
НепалNP
S
2uk.new_zealand#holiday@group.v.calendar.google.comНова ЗеландіяNZ
9
)uk.om#holiday@group.v.calendar.google.comОманOM
=
)uk.pa#holiday@group.v.calendar.google.comПанамаPA
9
)uk.pe#holiday@group.v.calendar.google.comПеруPE
L
2uk.philippines#holiday@group.v.calendar.google.comФіліппіниPH
A
)uk.pk#holiday@group.v.calendar.google.comПакистанPK
A
-uk.polish#holiday@group.v.calendar.google.comПольщаPL
F
)uk.pr#holiday@group.v.calendar.google.comПуерто-РикоPR
M
1uk.portuguese#holiday@group.v.calendar.google.comПортугаліяPT
A
)uk.py#holiday@group.v.calendar.google.comПарагвайPY
;
)uk.qa#holiday@group.v.calendar.google.com
КатарQA
A
)uk.re#holiday@group.v.calendar.google.comРеюньйонRE
E
/uk.romanian#holiday@group.v.calendar.google.comРумуніяRO
=
)uk.rs#holiday@group.v.calendar.google.comСербіяRS
@
.uk.russian#holiday@group.v.calendar.google.com
РосіяRU
=
)uk.rw#holiday@group.v.calendar.google.comРуандаRW
\
3uk.saudiarabian#holiday@group.v.calendar.google.com!Саудівська АравіяSA
V
)uk.sc#holiday@group.v.calendar.google.com%Сейшельські ОстровиSC
;
)uk.sd#holiday@group.v.calendar.google.com
СуданSD
B
.uk.swedish#holiday@group.v.calendar.google.comШвеціяSE
H
0uk.singapore#holiday@group.v.calendar.google.comСінгапурSG
U
)uk.sh#holiday@group.v.calendar.google.com$Острів Святої ЄлениSH
H
0uk.slovenian#holiday@group.v.calendar.google.comСловеніяSI
I
-uk.slovak#holiday@group.v.calendar.google.comСловаччинаSK
H
)uk.sl#holiday@group.v.calendar.google.comСьєрра-ЛеонеSL
D
)uk.sm#holiday@group.v.calendar.google.comСан-МариноSM
?
)uk.sn#holiday@group.v.calendar.google.comСенегалSN
=
)uk.so#holiday@group.v.calendar.google.comСомаліSO
?
)uk.sr#holiday@group.v.calendar.google.comСуринамSR
N
)uk.ss#holiday@group.v.calendar.google.comПівденний СуданSS
T
)uk.st#holiday@group.v.calendar.google.com#Сан-Томе і ПрінсіпіST
C
)uk.sv#holiday@group.v.calendar.google.comСальвадорSV
;
)uk.sy#holiday@group.v.calendar.google.com
СиріяSY
C
)uk.sz#holiday@group.v.calendar.google.comСвазілендSZ
7
)uk.td#holiday@group.v.calendar.google.comЧадTD
9
)uk.tg#holiday@group.v.calendar.google.comТогоTG
?
)uk.th#holiday@group.v.calendar.google.comТаїландTH
;
)uk.tn#holiday@group.v.calendar.google.com
ТунісTN
H
.uk.turkish#holiday@group.v.calendar.google.comТуреччинаTR
Q
)uk.tt#holiday@group.v.calendar.google.com Тринідад і ТобагоTT
C
-uk.taiwan#holiday@group.v.calendar.google.comТайваньTW
A
)uk.tz#holiday@group.v.calendar.google.comТанзаніяTZ
F
0uk.ukrainian#holiday@group.v.calendar.google.comУкраїнаUA
=
)uk.ug#holiday@group.v.calendar.google.comУгандаUG
8
*uk.usa#holiday@group.v.calendar.google.comСШАUS
?
)uk.uy#holiday@group.v.calendar.google.comУругвайUY
E
)uk.uz#holiday@group.v.calendar.google.comУзбекистанUZ
?
)uk.va#holiday@group.v.calendar.google.comВатиканVA
C
)uk.ve#holiday@group.v.calendar.google.comВенесуелаVE
\
)uk.vi#holiday@group.v.calendar.google.com+Віргінські острови, СШАVI
G
1uk.vietnamese#holiday@group.v.calendar.google.comВʼєтнамVN
9
)uk.ye#holiday@group.v.calendar.google.comЄменYE
?
)uk.yt#holiday@group.v.calendar.google.comМайоттаYT
m
)uk.sa#holiday@group.v.calendar.google.com<Південно-Африканська РеспублікаZA
=
)uk.zm#holiday@group.v.calendar.google.comЗамбіяZM
A
)uk.zw#holiday@group.v.calendar.google.comЗімбабвеZWW
0uk.christian#holiday@group.v.calendar.google.com#Християнські святаO
.uk.judaism#holiday@group.v.calendar.google.comЄврейські святаW
.uk.islamic#holiday@group.v.calendar.google.com%Мусульманські свята]
<uk.orthodox_christianity#holiday@group.v.calendar.google.comКанонічні святаuk