
F
)lo.ad#holiday@group.v.calendar.google.comອັນດໍຣາAD
j
)lo.ae#holiday@group.v.calendar.google.com9ສະຫະລັດອາຣັບເອມິເຣດAE
X
)lo.af#holiday@group.v.calendar.google.com'ອາຟການິດສະຖານAF
I
)lo.al#holiday@group.v.calendar.google.comແອວເບເນຍAL
F
)lo.am#holiday@group.v.calendar.google.comອາເມເນຍAM
F
)lo.ao#holiday@group.v.calendar.google.comແອງໂກລາAO
L
)lo.ar#holiday@group.v.calendar.google.comອາເຈນທິນາAR
L
/lo.austrian#holiday@group.v.calendar.google.comອອສເທຣຍAT
T
1lo.australian#holiday@group.v.calendar.google.comອອສເຕຣເລຍAU
C
)lo.aw#holiday@group.v.calendar.google.comອາຣູບາAW
O
)lo.az#holiday@group.v.calendar.google.comອາເຊີໄບຈານAZ
o
)lo.ba#holiday@group.v.calendar.google.com>ບອດສະເນຍ ແລະ ແຮສໂກວີນາBA
F
)lo.bb#holiday@group.v.calendar.google.comບາບາໂດສBB
O
)lo.bd#holiday@group.v.calendar.google.comບັງກະລາເທດBD
C
)lo.be#holiday@group.v.calendar.google.comເບວຢຽມBE
S
)lo.bf#holiday@group.v.calendar.google.com"ເບີກິນາ ຟາໂຊBF
P
0lo.bulgarian#holiday@group.v.calendar.google.comບັງກາເຣຍBG
@
)lo.bh#holiday@group.v.calendar.google.comບາເຣນBH
F
)lo.bi#holiday@group.v.calendar.google.comບູຣຸນດິBI
@
)lo.bj#holiday@group.v.calendar.google.comເບນິນBJ
I
)lo.bm#holiday@group.v.calendar.google.comເບີມິວດາBM
F
)lo.bo#holiday@group.v.calendar.google.comໂບລິເວຍBO
M
0lo.brazilian#holiday@group.v.calendar.google.comບະເລຊີນBR
F
)lo.bs#holiday@group.v.calendar.google.comບາຮາມາສBS
L
)lo.bw#holiday@group.v.calendar.google.comບອດສະວານາBW
I
)lo.by#holiday@group.v.calendar.google.comເບວບາຣຸສBY
I
/lo.canadian#holiday@group.v.calendar.google.comແຄນາດາCA
X
)lo.cd#holiday@group.v.calendar.google.com'ຄອງໂກ - ຄິນຊາຊາCD
p
)lo.cf#holiday@group.v.calendar.google.com?ສາທາລະນະລັດອາຟຣິກາກາງCF
[
)lo.cg#holiday@group.v.calendar.google.com*ຄອງໂກ - ບຣາຊາວິວCG
R
)lo.ch#holiday@group.v.calendar.google.com!ສະວິດເຊີແລນCH
G
)lo.ci#holiday@group.v.calendar.google.comໂຄຕີ ວົວCI
=
)lo.cl#holiday@group.v.calendar.google.comຈີເລCL
F
)lo.cm#holiday@group.v.calendar.google.comຄາເມຣູນCM
=
,lo.china#holiday@group.v.calendar.google.com	ຈີນCN
I
)lo.co#holiday@group.v.calendar.google.comໂຄລົມເບຍCO
M
)lo.cr#holiday@group.v.calendar.google.comໂຄສຕາ ຣິກາCR
@
)lo.cu#holiday@group.v.calendar.google.comຄິວບາCU
G
)lo.cv#holiday@group.v.calendar.google.comເຄບ ເວີດCV
C
)lo.cy#holiday@group.v.calendar.google.comໄຊປຣັສCY
a
,lo.czech#holiday@group.v.calendar.google.com-ສາທາລະນະລັດເຊັກCZ
M
-lo.german#holiday@group.v.calendar.google.comເຢຍລະມັນDE
G
-lo.danish#holiday@group.v.calendar.google.comເດນມາກDK
n
)lo.do#holiday@group.v.calendar.google.com=ສາທາລະນະລັດ ໂດມິນິກັນDO
I
)lo.dz#holiday@group.v.calendar.google.comອັລຈິເຣຍDZ
F
)lo.ec#holiday@group.v.calendar.google.comເອກວາດໍEC
I
)lo.ee#holiday@group.v.calendar.google.comເອສໂຕເນຍEE
@
)lo.eg#holiday@group.v.calendar.google.comອີຢິບEG
I
)lo.er#holiday@group.v.calendar.google.comເອຣິເທຣຍER
C
,lo.spain#holiday@group.v.calendar.google.comສະເປນES
L
)lo.et#holiday@group.v.calendar.google.comອີທິໂອເປຍET
H
.lo.finnish#holiday@group.v.calendar.google.comຟິນແລນFI
=
)lo.fj#holiday@group.v.calendar.google.comຟິຈິFJ
U
)lo.fo#holiday@group.v.calendar.google.com$ຫມູ່ເກາະແຟໂຣFO
D
-lo.french#holiday@group.v.calendar.google.comຝຣັ່ງFR
@
)lo.ga#holiday@group.v.calendar.google.comກາບອນGA
a
)lo.uk#holiday@group.v.calendar.google.com0ສະຫະລາດຊະອະນາຈັກGB
F
)lo.gd#holiday@group.v.calendar.google.comເກຣເນດາGD
@
)lo.ge#holiday@group.v.calendar.google.comຈໍເຈຍGE
=
)lo.gh#holiday@group.v.calendar.google.comການາGH
L
)lo.gi#holiday@group.v.calendar.google.comຈິບບຣອນທາGI
F
)lo.gl#holiday@group.v.calendar.google.comກຣີນແລນGL
d
)lo.gm#holiday@group.v.calendar.google.com3ສາທາລະນະລັດແກມເບຍGM
=
)lo.gn#holiday@group.v.calendar.google.comກິນີGN
\
)lo.gq#holiday@group.v.calendar.google.com+ເອຄົວໂທຣຽວ ກີນີGQ
@
,lo.greek#holiday@group.v.calendar.google.comກຣີຊGR
L
)lo.gt#holiday@group.v.calendar.google.comກົວເທມາລາGT
=
)lo.gu#holiday@group.v.calendar.google.comກວາມGU
S
)lo.gw#holiday@group.v.calendar.google.com"ກິນີ-ບິສເຊົາGW
J
0lo.hong_kong#holiday@group.v.calendar.google.comຮອງກົງHK
I
)lo.hn#holiday@group.v.calendar.google.comຮອນດູຣັສHN
O
/lo.croatian#holiday@group.v.calendar.google.comໂຄຣເອເທຍHR
=
)lo.ht#holiday@group.v.calendar.google.comໄຮຕິHT
M
0lo.hungarian#holiday@group.v.calendar.google.comຮັງກາຣີHU
W
1lo.indonesian#holiday@group.v.calendar.google.comອິນໂດເນເຊຍID
I
,lo.irish#holiday@group.v.calendar.google.comໄອຣ໌ແລນIE
M
-lo.jewish#holiday@group.v.calendar.google.comອິສຣາເອວIL
G
-lo.indian#holiday@group.v.calendar.google.comອິນເດຍIN
@
)lo.iq#holiday@group.v.calendar.google.comອີຣັກIQ
@
)lo.ir#holiday@group.v.calendar.google.comອີຣານIR
C
)lo.is#holiday@group.v.calendar.google.comໄອສແລນIS
H
.lo.italian#holiday@group.v.calendar.google.comອິຕາລີIT
C
)lo.jm#holiday@group.v.calendar.google.comຈາໄມຄາJM
@
)lo.jo#holiday@group.v.calendar.google.comຈໍແດນJO
L
/lo.japanese#holiday@group.v.calendar.google.comຍີ່ປຸ່ນJP
@
)lo.ke#holiday@group.v.calendar.google.comເຄນຢາKE
I
)lo.kg#holiday@group.v.calendar.google.comຄີກິສຖານKG
F
)lo.kh#holiday@group.v.calendar.google.comກຳປູເຈຍKH
F
)lo.km#holiday@group.v.calendar.google.comໂຄໂມໂຣສKM
R
)lo.kp#holiday@group.v.calendar.google.com!ເກົາຫລີເໜືອKP
X
2lo.south_korea#holiday@group.v.calendar.google.comເກົາຫລີໃຕ້KR
@
)lo.kw#holiday@group.v.calendar.google.comກູເວດKW
V
)lo.ky#holiday@group.v.calendar.google.com%ໝູ່ເກາະ ເຄແມນKY
O
)lo.kz#holiday@group.v.calendar.google.comຄາຊັກສະຖານKZ
F
)lo.lb#holiday@group.v.calendar.google.comເລບານອນLB
R
)lo.li#holiday@group.v.calendar.google.com!ລິດເທນສະຕາຍLI
F
)lo.lk#holiday@group.v.calendar.google.comສີລັງກາLK
I
)lo.lr#holiday@group.v.calendar.google.comລິເບີເຣຍLR
C
)lo.ls#holiday@group.v.calendar.google.comເລໂຊໂທLS
Q
1lo.lithuanian#holiday@group.v.calendar.google.comລິທົວເນຍLT
I
)lo.lu#holiday@group.v.calendar.google.comລຸກຊຳບົວLU
H
.lo.latvian#holiday@group.v.calendar.google.comລັດເວຍLV
@
)lo.ly#holiday@group.v.calendar.google.comລິເບຍLY
I
)lo.ma#holiday@group.v.calendar.google.comໂມຣັອກໂຄMA
C
)lo.mc#holiday@group.v.calendar.google.comໂມນາໂຄMC
F
)lo.md#holiday@group.v.calendar.google.comໂມນໂດວາMD
O
)lo.me#holiday@group.v.calendar.google.comມອນເຕເນໂກຣME
L
)lo.mg#holiday@group.v.calendar.google.comມາດາກາສກາMG
L
)lo.mk#holiday@group.v.calendar.google.comແມຊິໂດເນຍMK
=
)lo.ml#holiday@group.v.calendar.google.comມາລີML
I
)lo.mn#holiday@group.v.calendar.google.comມອງໂກເລຍMN
F
)lo.mo#holiday@group.v.calendar.google.comມາເກົ້າMO
F
)lo.mq#holiday@group.v.calendar.google.comມາຕິນີກMQ
@
)lo.mt#holiday@group.v.calendar.google.comມອນທາMT
I
)lo.mu#holiday@group.v.calendar.google.comມົວຣິຊຽສMU
C
)lo.mw#holiday@group.v.calendar.google.comມາລາວີMW
N
.lo.mexican#holiday@group.v.calendar.google.comເມັກຊິໂກMX
L
/lo.malaysia#holiday@group.v.calendar.google.comມາເລເຊຍMY
I
)lo.mz#holiday@group.v.calendar.google.comໂມແຊມບິກMZ
F
)lo.na#holiday@group.v.calendar.google.comນາມີເບຍNA
@
)lo.ne#holiday@group.v.calendar.google.comນິເຈີNE
F
)lo.ng#holiday@group.v.calendar.google.comໄນຈີເຣຍNG
O
)lo.ni#holiday@group.v.calendar.google.comນິກຄາຣາກົວNI
L
,lo.dutch#holiday@group.v.calendar.google.comເນເທີແລນNL
D
0lo.norwegian#holiday@group.v.calendar.google.comນໍເວNO
@
)lo.np#holiday@group.v.calendar.google.comເນປານNP
R
2lo.new_zealand#holiday@group.v.calendar.google.comນິວຊີແລນNZ
@
)lo.om#holiday@group.v.calendar.google.comໂອມານOM
C
)lo.pa#holiday@group.v.calendar.google.comພານາມາPA
=
)lo.pe#holiday@group.v.calendar.google.comເປຣູPE
R
2lo.philippines#holiday@group.v.calendar.google.comຟິລິບປິນPH
O
)lo.pk#holiday@group.v.calendar.google.comປາກິດສະຖານPK
D
-lo.polish#holiday@group.v.calendar.google.comໂປແລນPL
P
)lo.pr#holiday@group.v.calendar.google.comເພືອໂຕ ຣິໂກPR
N
1lo.portuguese#holiday@group.v.calendar.google.comພອລທູໂກPT
F
)lo.py#holiday@group.v.calendar.google.comພາຣາກວຍPY
=
)lo.qa#holiday@group.v.calendar.google.comກາຕາQA
L
)lo.re#holiday@group.v.calendar.google.comເຣອູນິຍົງRE
L
/lo.romanian#holiday@group.v.calendar.google.comໂຣແມເນຍRO
C
)lo.rs#holiday@group.v.calendar.google.comເຊີເບຍRS
H
.lo.russian#holiday@group.v.calendar.google.comຣັດເຊຍRU
C
)lo.rw#holiday@group.v.calendar.google.comຣວັນດາRW
c
3lo.saudiarabian#holiday@group.v.calendar.google.com(ຊາອຸດິ ອາຣາເບຍSA
I
)lo.sc#holiday@group.v.calendar.google.comເຊເຊວເລສSC
@
)lo.sd#holiday@group.v.calendar.google.comຊູດານSD
N
.lo.swedish#holiday@group.v.calendar.google.comສະວີເດັນSE
M
0lo.singapore#holiday@group.v.calendar.google.comສິງກະໂປSG
M
)lo.sh#holiday@group.v.calendar.google.comເຊນ ເຮເລນາSH
S
0lo.slovenian#holiday@group.v.calendar.google.comສະໂລເວເນຍSI
P
-lo.slovak#holiday@group.v.calendar.google.comສະໂລວາເກຍSK
P
)lo.sl#holiday@group.v.calendar.google.comເຊຍຣາ ລີໂອນSL
M
)lo.sm#holiday@group.v.calendar.google.comແຊນ ມາຣິໂນSM
F
)lo.sn#holiday@group.v.calendar.google.comເຊນີໂກລSN
C
)lo.so#holiday@group.v.calendar.google.comໂຊມາລີSO
F
)lo.sr#holiday@group.v.calendar.google.comຊູຣິນາມSR
I
)lo.ss#holiday@group.v.calendar.google.comຊູດານໃຕ້SS
i
)lo.st#holiday@group.v.calendar.google.com8ເຊົາທູເມ ແລະ ພຣິນຊິບST
M
)lo.sv#holiday@group.v.calendar.google.comເອວ ຊໍວາດໍSV
@
)lo.sy#holiday@group.v.calendar.google.comຊີເຣຍSY
L
)lo.sz#holiday@group.v.calendar.google.comສະວາຊິແລນSZ
:
)lo.td#holiday@group.v.calendar.google.com	ຊາດTD
=
)lo.tg#holiday@group.v.calendar.google.comໂຕໂກTG
7
)lo.th#holiday@group.v.calendar.google.comໄທTH
F
)lo.tn#holiday@group.v.calendar.google.comຕູນິເຊຍTN
E
.lo.turkish#holiday@group.v.calendar.google.comເທີຄີTR
f
)lo.tt#holiday@group.v.calendar.google.com5ທຣິນິແດດ ແລະ ໂທແບໂກTT
J
-lo.taiwan#holiday@group.v.calendar.google.comໄຕ້ຫວັນTW
I
)lo.tz#holiday@group.v.calendar.google.comທານຊາເນຍTZ
J
0lo.ukrainian#holiday@group.v.calendar.google.comຢູເຄຣນUA
F
)lo.ug#holiday@group.v.calendar.google.comອູການດາUG
G
*lo.usa#holiday@group.v.calendar.google.comສະຫະລັດUS
F
)lo.uy#holiday@group.v.calendar.google.comອູຣຸກວຍUY
U
)lo.uz#holiday@group.v.calendar.google.com$ອຸສເບກິສະຖານUZ
V
)lo.va#holiday@group.v.calendar.google.com%ນະຄອນ ວາຕິກັນVA
O
)lo.ve#holiday@group.v.calendar.google.comເວເນຊູເອລາVE
i
)lo.vi#holiday@group.v.calendar.google.com8ໝູ່ເກາະ ຢູເອສ ເວີຈິນVI
N
1lo.vietnamese#holiday@group.v.calendar.google.comຫວຽດນາມVN
@
)lo.ye#holiday@group.v.calendar.google.comເຢເມນYE
C
)lo.yt#holiday@group.v.calendar.google.comມາຢັອດYT
O
)lo.sa#holiday@group.v.calendar.google.comອາຟຣິກາໃຕ້ZA
C
)lo.zm#holiday@group.v.calendar.google.comແຊມເບຍZM
I
)lo.zw#holiday@group.v.calendar.google.comຊິມບັບເວZWF
0lo.christian#holiday@group.v.calendar.google.comChristian HolidaysA
.lo.judaism#holiday@group.v.calendar.google.comJewish HolidaysA
.lo.islamic#holiday@group.v.calendar.google.comMuslim HolidaysQ
<lo.orthodox_christianity#holiday@group.v.calendar.google.comOrthodox Holidayslo_LA