
8
)fi.ad#holiday@group.v.calendar.google.comAndorraAD
B
)fi.ae#holiday@group.v.calendar.google.comArabiemiirikunnatAE
;
)fi.af#holiday@group.v.calendar.google.com
AfganistanAF
8
)fi.al#holiday@group.v.calendar.google.comAlbaniaAL
8
)fi.am#holiday@group.v.calendar.google.comArmeniaAM
7
)fi.ao#holiday@group.v.calendar.google.comAngolaAO
;
)fi.ar#holiday@group.v.calendar.google.com
ArgentiinaAR
@
/fi.austrian#holiday@group.v.calendar.google.com	ItävaltaAT
B
1fi.australian#holiday@group.v.calendar.google.com	AustraliaAU
6
)fi.aw#holiday@group.v.calendar.google.comArubaAW
=
)fi.az#holiday@group.v.calendar.google.comAzerbaidžanAZ
G
)fi.ba#holiday@group.v.calendar.google.comBosnia ja HertsegovinaBA
9
)fi.bb#holiday@group.v.calendar.google.comBarbadosBB
;
)fi.bd#holiday@group.v.calendar.google.com
BangladeshBD
7
)fi.be#holiday@group.v.calendar.google.comBelgiaBE
=
)fi.bf#holiday@group.v.calendar.google.comBurkina FasoBF
@
0fi.bulgarian#holiday@group.v.calendar.google.comBulgariaBG
8
)fi.bh#holiday@group.v.calendar.google.comBahrainBH
8
)fi.bi#holiday@group.v.calendar.google.comBurundiBI
6
)fi.bj#holiday@group.v.calendar.google.comBeninBJ
8
)fi.bm#holiday@group.v.calendar.google.comBermudaBM
8
)fi.bo#holiday@group.v.calendar.google.comBoliviaBO
@
0fi.brazilian#holiday@group.v.calendar.google.comBrasiliaBR
7
)fi.bs#holiday@group.v.calendar.google.comBahamaBS
9
)fi.bw#holiday@group.v.calendar.google.comBotswanaBW
?
)fi.by#holiday@group.v.calendar.google.comValko-VenäjäBY
=
/fi.canadian#holiday@group.v.calendar.google.comKanadaCA
P
)fi.cd#holiday@group.v.calendar.google.comKongon demokraattinen tasavaltaCD
H
)fi.cf#holiday@group.v.calendar.google.comKeski-Afrikan tasavaltaCF
A
)fi.cg#holiday@group.v.calendar.google.comKongon tasavaltaCG
8
)fi.ch#holiday@group.v.calendar.google.comSveitsiCH
B
)fi.ci#holiday@group.v.calendar.google.comNorsunluurannikkoCI
6
)fi.cl#holiday@group.v.calendar.google.comChileCL
8
)fi.cm#holiday@group.v.calendar.google.comKamerunCM
9
,fi.china#holiday@group.v.calendar.google.comKiinaCN
9
)fi.co#holiday@group.v.calendar.google.comKolumbiaCO
;
)fi.cr#holiday@group.v.calendar.google.com
Costa RicaCR
6
)fi.cu#holiday@group.v.calendar.google.comKuubaCU
:
)fi.cv#holiday@group.v.calendar.google.com	Kap VerdeCV
7
)fi.cy#holiday@group.v.calendar.google.comKyprosCY
;
,fi.czech#holiday@group.v.calendar.google.comTšekkiCZ
:
-fi.german#holiday@group.v.calendar.google.comSaksaDE
;
-fi.danish#holiday@group.v.calendar.google.comTanskaDK
I
)fi.do#holiday@group.v.calendar.google.comDominikaaninen tasavaltaDO
8
)fi.dz#holiday@group.v.calendar.google.comAlgeriaDZ
8
)fi.ec#holiday@group.v.calendar.google.comEcuadorEC
5
)fi.ee#holiday@group.v.calendar.google.comViroEE
7
)fi.eg#holiday@group.v.calendar.google.comEgyptiEG
8
)fi.er#holiday@group.v.calendar.google.comEritreaER
;
,fi.spain#holiday@group.v.calendar.google.comEspanjaES
8
)fi.et#holiday@group.v.calendar.google.comEtiopiaET
;
.fi.finnish#holiday@group.v.calendar.google.comSuomiFI
7
)fi.fj#holiday@group.v.calendar.google.comFidžiFJ
;
)fi.fo#holiday@group.v.calendar.google.com
FärsaaretFO
;
-fi.french#holiday@group.v.calendar.google.comRanskaFR
6
)fi.ga#holiday@group.v.calendar.google.comGabonGA
>
)fi.uk#holiday@group.v.calendar.google.comIso-BritanniaGB
8
)fi.gd#holiday@group.v.calendar.google.comGrenadaGD
8
)fi.ge#holiday@group.v.calendar.google.comGeorgiaGE
6
)fi.gh#holiday@group.v.calendar.google.comGhanaGH
:
)fi.gi#holiday@group.v.calendar.google.com	GibraltarGI
;
)fi.gl#holiday@group.v.calendar.google.com
GrönlantiGL
7
)fi.gm#holiday@group.v.calendar.google.comGambiaGM
7
)fi.gn#holiday@group.v.calendar.google.comGuineaGN
H
)fi.gq#holiday@group.v.calendar.google.comPäiväntasaajan GuineaGQ
;
,fi.greek#holiday@group.v.calendar.google.comKreikkaGR
:
)fi.gt#holiday@group.v.calendar.google.com	GuatemalaGT
5
)fi.gu#holiday@group.v.calendar.google.comGuamGU
>
)fi.gw#holiday@group.v.calendar.google.comGuinea-BissauGW
@
0fi.hong_kong#holiday@group.v.calendar.google.comHongkongHK
9
)fi.hn#holiday@group.v.calendar.google.comHondurasHN
>
/fi.croatian#holiday@group.v.calendar.google.comKroatiaHR
6
)fi.ht#holiday@group.v.calendar.google.comHaitiHT
>
0fi.hungarian#holiday@group.v.calendar.google.comUnkariHU
B
1fi.indonesian#holiday@group.v.calendar.google.com	IndonesiaID
;
,fi.irish#holiday@group.v.calendar.google.comIrlantiIE
;
-fi.jewish#holiday@group.v.calendar.google.comIsraelIL
:
-fi.indian#holiday@group.v.calendar.google.comIntiaIN
5
)fi.iq#holiday@group.v.calendar.google.comIrakIQ
5
)fi.ir#holiday@group.v.calendar.google.comIranIR
8
)fi.is#holiday@group.v.calendar.google.comIslantiIS
<
.fi.italian#holiday@group.v.calendar.google.comItaliaIT
8
)fi.jm#holiday@group.v.calendar.google.comJamaikaJM
9
)fi.jo#holiday@group.v.calendar.google.comJordaniaJO
=
/fi.japanese#holiday@group.v.calendar.google.comJapaniJP
6
)fi.ke#holiday@group.v.calendar.google.comKeniaKE
9
)fi.kg#holiday@group.v.calendar.google.comKirgisiaKG
:
)fi.kh#holiday@group.v.calendar.google.com	KambodžaKH
8
)fi.km#holiday@group.v.calendar.google.comKomoritKM
>
)fi.kp#holiday@group.v.calendar.google.comPohjois-KoreaKP
F
2fi.south_korea#holiday@group.v.calendar.google.comEtelä-KoreaKR
7
)fi.kw#holiday@group.v.calendar.google.comKuwaitKW
=
)fi.ky#holiday@group.v.calendar.google.comCaymansaaretKY
:
)fi.kz#holiday@group.v.calendar.google.com	KazakstanKZ
8
)fi.lb#holiday@group.v.calendar.google.comLibanonLB
>
)fi.li#holiday@group.v.calendar.google.comLiechtensteinLI
:
)fi.lk#holiday@group.v.calendar.google.com	Sri LankaLK
8
)fi.lr#holiday@group.v.calendar.google.comLiberiaLR
8
)fi.ls#holiday@group.v.calendar.google.comLesothoLS
@
1fi.lithuanian#holiday@group.v.calendar.google.comLiettuaLT
:
)fi.lu#holiday@group.v.calendar.google.com	LuxemburgLU
<
.fi.latvian#holiday@group.v.calendar.google.comLatviaLV
6
)fi.ly#holiday@group.v.calendar.google.comLibyaLY
8
)fi.ma#holiday@group.v.calendar.google.comMarokkoMA
7
)fi.mc#holiday@group.v.calendar.google.comMonacoMC
8
)fi.md#holiday@group.v.calendar.google.comMoldovaMD
;
)fi.me#holiday@group.v.calendar.google.com
MontenegroME
;
)fi.mg#holiday@group.v.calendar.google.com
MadagaskarMG
:
)fi.mk#holiday@group.v.calendar.google.com	MakedoniaMK
5
)fi.ml#holiday@group.v.calendar.google.comMaliML
9
)fi.mn#holiday@group.v.calendar.google.comMongoliaMN
6
)fi.mo#holiday@group.v.calendar.google.comMacaoMO
;
)fi.mq#holiday@group.v.calendar.google.com
MartiniqueMQ
6
)fi.mt#holiday@group.v.calendar.google.comMaltaMT
:
)fi.mu#holiday@group.v.calendar.google.com	MauritiusMU
7
)fi.mw#holiday@group.v.calendar.google.comMalawiMW
=
.fi.mexican#holiday@group.v.calendar.google.comMeksikoMX
>
/fi.malaysia#holiday@group.v.calendar.google.comMalesiaMY
9
)fi.mz#holiday@group.v.calendar.google.comMosambikMZ
8
)fi.na#holiday@group.v.calendar.google.comNamibiaNA
6
)fi.ne#holiday@group.v.calendar.google.comNigerNE
8
)fi.ng#holiday@group.v.calendar.google.comNigeriaNG
:
)fi.ni#holiday@group.v.calendar.google.com	NicaraguaNI
>
,fi.dutch#holiday@group.v.calendar.google.com
AlankomaatNL
=
0fi.norwegian#holiday@group.v.calendar.google.comNorjaNO
6
)fi.np#holiday@group.v.calendar.google.comNepalNP
G
2fi.new_zealand#holiday@group.v.calendar.google.comUusi-SeelantiNZ
5
)fi.om#holiday@group.v.calendar.google.comOmanOM
7
)fi.pa#holiday@group.v.calendar.google.comPanamaPA
5
)fi.pe#holiday@group.v.calendar.google.comPeruPE
E
2fi.philippines#holiday@group.v.calendar.google.comFilippiinitPH
9
)fi.pk#holiday@group.v.calendar.google.comPakistanPK
:
-fi.polish#holiday@group.v.calendar.google.comPuolaPL
<
)fi.pr#holiday@group.v.calendar.google.comPuerto RicoPR
B
1fi.portuguese#holiday@group.v.calendar.google.com	PortugaliPT
9
)fi.py#holiday@group.v.calendar.google.comParaguayPY
6
)fi.qa#holiday@group.v.calendar.google.comQatarQA
9
)fi.re#holiday@group.v.calendar.google.comRéunionRE
>
/fi.romanian#holiday@group.v.calendar.google.comRomaniaRO
7
)fi.rs#holiday@group.v.calendar.google.comSerbiaRS
>
.fi.russian#holiday@group.v.calendar.google.comVenäjäRU
7
)fi.rw#holiday@group.v.calendar.google.comRuandaRW
G
3fi.saudiarabian#holiday@group.v.calendar.google.comSaudi-ArabiaSA
;
)fi.sc#holiday@group.v.calendar.google.com
SeychellitSC
6
)fi.sd#holiday@group.v.calendar.google.comSudanSD
<
.fi.swedish#holiday@group.v.calendar.google.comRuotsiSE
A
0fi.singapore#holiday@group.v.calendar.google.com	SingaporeSG
=
)fi.sh#holiday@group.v.calendar.google.comSaint HelenaSH
@
0fi.slovenian#holiday@group.v.calendar.google.comSloveniaSI
=
-fi.slovak#holiday@group.v.calendar.google.comSlovakiaSK
=
)fi.sl#holiday@group.v.calendar.google.comSierra LeoneSL
;
)fi.sm#holiday@group.v.calendar.google.com
San MarinoSM
8
)fi.sn#holiday@group.v.calendar.google.comSenegalSN
8
)fi.so#holiday@group.v.calendar.google.comSomaliaSO
9
)fi.sr#holiday@group.v.calendar.google.comSurinameSR
=
)fi.ss#holiday@group.v.calendar.google.comEtelä-SudanSS
H
)fi.st#holiday@group.v.calendar.google.comSão Tomé ja PríncipeST
<
)fi.sv#holiday@group.v.calendar.google.comEl SalvadorSV
7
)fi.sy#holiday@group.v.calendar.google.comSyyriaSY
9
)fi.sz#holiday@group.v.calendar.google.comSwazimaaSZ
6
)fi.td#holiday@group.v.calendar.google.comTšadTD
5
)fi.tg#holiday@group.v.calendar.google.comTogoTG
8
)fi.th#holiday@group.v.calendar.google.comThaimaaTH
8
)fi.tn#holiday@group.v.calendar.google.comTunisiaTN
<
.fi.turkish#holiday@group.v.calendar.google.comTurkkiTR
C
)fi.tt#holiday@group.v.calendar.google.comTrinidad ja TobagoTT
;
-fi.taiwan#holiday@group.v.calendar.google.comTaiwanTW
9
)fi.tz#holiday@group.v.calendar.google.comTansaniaTZ
?
0fi.ukrainian#holiday@group.v.calendar.google.comUkrainaUA
7
)fi.ug#holiday@group.v.calendar.google.comUgandaUG
=
*fi.usa#holiday@group.v.calendar.google.comYhdysvallatUS
8
)fi.uy#holiday@group.v.calendar.google.comUruguayUY
;
)fi.uz#holiday@group.v.calendar.google.com
UzbekistanUZ
:
)fi.va#holiday@group.v.calendar.google.com	VatikaaniVA
:
)fi.ve#holiday@group.v.calendar.google.com	VenezuelaVE
K
)fi.vi#holiday@group.v.calendar.google.comYhdysvaltain NeitsytsaaretVI
@
1fi.vietnamese#holiday@group.v.calendar.google.comVietnamVN
6
)fi.ye#holiday@group.v.calendar.google.comJemenYE
8
)fi.yt#holiday@group.v.calendar.google.comMayotteYT
?
)fi.sa#holiday@group.v.calendar.google.comEtelä-AfrikkaZA
7
)fi.zm#holiday@group.v.calendar.google.comSambiaZM
9
)fi.zw#holiday@group.v.calendar.google.comZimbabweZWL
0fi.christian#holiday@group.v.calendar.google.comKristilliset juhlapyhätI
.fi.judaism#holiday@group.v.calendar.google.comJuutalaiset juhlapyhätJ
.fi.islamic#holiday@group.v.calendar.google.comIslamilaiset juhlapyhätX
<fi.orthodox_christianity#holiday@group.v.calendar.google.comOrtodoksiset juhlapyhätfi