
=
)ja.ad#holiday@group.v.calendar.google.comアンドラAD
I
)ja.ae#holiday@group.v.calendar.google.comアラブ首長国連邦AE
F
)ja.af#holiday@group.v.calendar.google.comアフガニスタンAF
@
)ja.al#holiday@group.v.calendar.google.comアルバニアAL
@
)ja.am#holiday@group.v.calendar.google.comアルメニアAM
=
)ja.ao#holiday@group.v.calendar.google.comアンゴラAO
C
)ja.ar#holiday@group.v.calendar.google.comアルゼンチンAR
I
/ja.austrian#holiday@group.v.calendar.google.comオーストリアAT
N
1ja.australian#holiday@group.v.calendar.google.comオーストラリアAU
:
)ja.aw#holiday@group.v.calendar.google.com	アルバAW
I
)ja.az#holiday@group.v.calendar.google.comアゼルバイジャンAZ
U
)ja.ba#holiday@group.v.calendar.google.com$ボスニア・ヘルツェゴビナBA
@
)ja.bb#holiday@group.v.calendar.google.comバルバドスBB
F
)ja.bd#holiday@group.v.calendar.google.comバングラデシュBD
=
)ja.be#holiday@group.v.calendar.google.comベルギーBE
F
)ja.bf#holiday@group.v.calendar.google.comブルキナファソBF
G
0ja.bulgarian#holiday@group.v.calendar.google.comブルガリアBG
@
)ja.bh#holiday@group.v.calendar.google.comバーレーンBH
=
)ja.bi#holiday@group.v.calendar.google.comブルンジBI
:
)ja.bj#holiday@group.v.calendar.google.com	ベナンBJ
@
)ja.bm#holiday@group.v.calendar.google.comバミューダBM
=
)ja.bo#holiday@group.v.calendar.google.comボリビアBO
D
0ja.brazilian#holiday@group.v.calendar.google.comブラジルBR
:
)ja.bs#holiday@group.v.calendar.google.com	バハマBS
=
)ja.bw#holiday@group.v.calendar.google.comボツワナBW
@
)ja.by#holiday@group.v.calendar.google.comベラルーシBY
@
/ja.canadian#holiday@group.v.calendar.google.com	カナダCA
Z
)ja.cd#holiday@group.v.calendar.google.com)コンゴ民主共和国(キンシャサ)CD
L
)ja.cf#holiday@group.v.calendar.google.com中央アフリカ共和国CF
T
)ja.cg#holiday@group.v.calendar.google.com#コンゴ共和国(ブラザビル)CG
:
)ja.ch#holiday@group.v.calendar.google.com	スイスCH
I
)ja.ci#holiday@group.v.calendar.google.comコートジボワールCI
7
)ja.cl#holiday@group.v.calendar.google.comチリCL
@
)ja.cm#holiday@group.v.calendar.google.comカメルーンCM
:
,ja.china#holiday@group.v.calendar.google.com中国CN
@
)ja.co#holiday@group.v.calendar.google.comコロンビアCO
@
)ja.cr#holiday@group.v.calendar.google.comコスタリカCR
=
)ja.cu#holiday@group.v.calendar.google.comキューバCU
C
)ja.cv#holiday@group.v.calendar.google.comカーボベルデCV
=
)ja.cy#holiday@group.v.calendar.google.comキプロスCY
F
,ja.czech#holiday@group.v.calendar.google.comチェコ共和国CZ
>
-ja.german#holiday@group.v.calendar.google.com	ドイツDE
D
-ja.danish#holiday@group.v.calendar.google.comデンマークDK
F
)ja.do#holiday@group.v.calendar.google.comドミニカ共和国DO
C
)ja.dz#holiday@group.v.calendar.google.comアルジェリアDZ
@
)ja.ec#holiday@group.v.calendar.google.comエクアドルEC
@
)ja.ee#holiday@group.v.calendar.google.comエストニアEE
=
)ja.eg#holiday@group.v.calendar.google.comエジプトEG
@
)ja.er#holiday@group.v.calendar.google.comエリトリアER
@
,ja.spain#holiday@group.v.calendar.google.comスペインES
@
)ja.et#holiday@group.v.calendar.google.comエチオピアET
H
.ja.finnish#holiday@group.v.calendar.google.comフィンランドFI
=
)ja.fj#holiday@group.v.calendar.google.comフィジーFJ
C
)ja.fo#holiday@group.v.calendar.google.comフェロー諸島FO
A
-ja.french#holiday@group.v.calendar.google.comフランスFR
:
)ja.ga#holiday@group.v.calendar.google.com	ガボンGA
=
)ja.uk#holiday@group.v.calendar.google.comイギリスGB
=
)ja.gd#holiday@group.v.calendar.google.comグレナダGD
@
)ja.ge#holiday@group.v.calendar.google.comジョージアGE
:
)ja.gh#holiday@group.v.calendar.google.com	ガーナGH
C
)ja.gi#holiday@group.v.calendar.google.comジブラルタルGI
F
)ja.gl#holiday@group.v.calendar.google.comグリーンランドGL
=
)ja.gm#holiday@group.v.calendar.google.comガンビアGM
:
)ja.gn#holiday@group.v.calendar.google.com	ギニアGN
@
)ja.gq#holiday@group.v.calendar.google.com赤道ギニアGQ
@
,ja.greek#holiday@group.v.calendar.google.comギリシャGR
@
)ja.gt#holiday@group.v.calendar.google.comグアテマラGT
:
)ja.gu#holiday@group.v.calendar.google.com	グアムGU
C
)ja.gw#holiday@group.v.calendar.google.comギニアビサウGW
>
0ja.hong_kong#holiday@group.v.calendar.google.com香港HK
C
)ja.hn#holiday@group.v.calendar.google.comホンジュラスHN
F
/ja.croatian#holiday@group.v.calendar.google.comクロアチアHR
:
)ja.ht#holiday@group.v.calendar.google.com	ハイチHT
G
0ja.hungarian#holiday@group.v.calendar.google.comハンガリーHU
K
1ja.indonesian#holiday@group.v.calendar.google.comインドネシアID
F
,ja.irish#holiday@group.v.calendar.google.comアイルランドIE
D
-ja.jewish#holiday@group.v.calendar.google.comイスラエルIL
>
-ja.indian#holiday@group.v.calendar.google.com	インドIN
:
)ja.iq#holiday@group.v.calendar.google.com	イラクIQ
:
)ja.ir#holiday@group.v.calendar.google.com	イランIR
C
)ja.is#holiday@group.v.calendar.google.comアイスランドIS
B
.ja.italian#holiday@group.v.calendar.google.comイタリアIT
@
)ja.jm#holiday@group.v.calendar.google.comジャマイカJM
=
)ja.jo#holiday@group.v.calendar.google.comヨルダンJO
=
/ja.japanese#holiday@group.v.calendar.google.com日本JP
:
)ja.ke#holiday@group.v.calendar.google.com	ケニアKE
=
)ja.kg#holiday@group.v.calendar.google.comキルギスKG
@
)ja.kh#holiday@group.v.calendar.google.comカンボジアKH
:
)ja.km#holiday@group.v.calendar.google.com	コモロKM
R
)ja.kp#holiday@group.v.calendar.google.com!朝鮮民主主義人民共和国KP
F
2ja.south_korea#holiday@group.v.calendar.google.com大韓民国KR
@
)ja.kw#holiday@group.v.calendar.google.comクウェートKW
C
)ja.ky#holiday@group.v.calendar.google.comケイマン諸島KY
C
)ja.kz#holiday@group.v.calendar.google.comカザフスタンKZ
=
)ja.lb#holiday@group.v.calendar.google.comレバノンLB
L
)ja.li#holiday@group.v.calendar.google.comリヒテンシュタインLI
@
)ja.lk#holiday@group.v.calendar.google.comスリランカLK
=
)ja.lr#holiday@group.v.calendar.google.comリベリアLR
:
)ja.ls#holiday@group.v.calendar.google.com	レソトLS
H
1ja.lithuanian#holiday@group.v.calendar.google.comリトアニアLT
F
)ja.lu#holiday@group.v.calendar.google.comルクセンブルクLU
B
.ja.latvian#holiday@group.v.calendar.google.comラトビアLV
:
)ja.ly#holiday@group.v.calendar.google.com	リビアLY
=
)ja.ma#holiday@group.v.calendar.google.comモロッコMA
:
)ja.mc#holiday@group.v.calendar.google.com	モナコMC
=
)ja.md#holiday@group.v.calendar.google.comモルドバMD
C
)ja.me#holiday@group.v.calendar.google.comモンテネグロME
C
)ja.mg#holiday@group.v.calendar.google.comマダガスカルMG
@
)ja.mk#holiday@group.v.calendar.google.comマケドニアMK
7
)ja.ml#holiday@group.v.calendar.google.comマリML
=
)ja.mn#holiday@group.v.calendar.google.comモンゴルMN
:
)ja.mo#holiday@group.v.calendar.google.com	マカオMO
F
)ja.mq#holiday@group.v.calendar.google.comマルティニークMQ
:
)ja.mt#holiday@group.v.calendar.google.com	マルタMT
C
)ja.mu#holiday@group.v.calendar.google.comモーリシャスMU
=
)ja.mw#holiday@group.v.calendar.google.comマラウイMW
B
.ja.mexican#holiday@group.v.calendar.google.comメキシコMX
F
/ja.malaysia#holiday@group.v.calendar.google.comマレーシアMY
C
)ja.mz#holiday@group.v.calendar.google.comモザンビークMZ
=
)ja.na#holiday@group.v.calendar.google.comナミビアNA
@
)ja.ne#holiday@group.v.calendar.google.comニジェールNE
C
)ja.ng#holiday@group.v.calendar.google.comナイジェリアNG
@
)ja.ni#holiday@group.v.calendar.google.comニカラグアNI
@
,ja.dutch#holiday@group.v.calendar.google.comオランダNL
G
0ja.norwegian#holiday@group.v.calendar.google.comノルウェーNO
=
)ja.np#holiday@group.v.calendar.google.comネパールNP
R
2ja.new_zealand#holiday@group.v.calendar.google.comニュージーランドNZ
=
)ja.om#holiday@group.v.calendar.google.comオマーンOM
:
)ja.pa#holiday@group.v.calendar.google.com	パナマPA
:
)ja.pe#holiday@group.v.calendar.google.com	ペルーPE
I
2ja.philippines#holiday@group.v.calendar.google.comフィリピンPH
@
)ja.pk#holiday@group.v.calendar.google.comパキスタンPK
D
-ja.polish#holiday@group.v.calendar.google.comポーランドPL
C
)ja.pr#holiday@group.v.calendar.google.comプエルトリコPR
H
1ja.portuguese#holiday@group.v.calendar.google.comポルトガルPT
@
)ja.py#holiday@group.v.calendar.google.comパラグアイPY
=
)ja.qa#holiday@group.v.calendar.google.comカタールQA
C
)ja.re#holiday@group.v.calendar.google.comレユニオン島RE
F
/ja.romanian#holiday@group.v.calendar.google.comルーマニアRO
=
)ja.rs#holiday@group.v.calendar.google.comセルビアRS
?
.ja.russian#holiday@group.v.calendar.google.com	ロシアRU
=
)ja.rw#holiday@group.v.calendar.google.comルワンダRW
P
3ja.saudiarabian#holiday@group.v.calendar.google.comサウジアラビアSA
@
)ja.sc#holiday@group.v.calendar.google.comセーシェルSC
=
)ja.sd#holiday@group.v.calendar.google.comスーダンSD
H
.ja.swedish#holiday@group.v.calendar.google.comスウェーデンSE
J
0ja.singapore#holiday@group.v.calendar.google.comシンガポールSG
C
)ja.sh#holiday@group.v.calendar.google.comセントヘレナSH
G
0ja.slovenian#holiday@group.v.calendar.google.comスロベニアSI
D
-ja.slovak#holiday@group.v.calendar.google.comスロバキアSK
C
)ja.sl#holiday@group.v.calendar.google.comシエラレオネSL
@
)ja.sm#holiday@group.v.calendar.google.comサンマリノSM
=
)ja.sn#holiday@group.v.calendar.google.comセネガルSN
=
)ja.so#holiday@group.v.calendar.google.comソマリアSO
=
)ja.sr#holiday@group.v.calendar.google.comスリナムSR
@
)ja.ss#holiday@group.v.calendar.google.com南スーダンSS
O
)ja.st#holiday@group.v.calendar.google.comサントメ・プリンシペST
F
)ja.sv#holiday@group.v.calendar.google.comエルサルバドルSV
:
)ja.sy#holiday@group.v.calendar.google.com	シリアSY
C
)ja.sz#holiday@group.v.calendar.google.comスワジランドSZ
:
)ja.td#holiday@group.v.calendar.google.com	チャドTD
:
)ja.tg#holiday@group.v.calendar.google.com	トーゴTG
7
)ja.th#holiday@group.v.calendar.google.comタイTH
@
)ja.tn#holiday@group.v.calendar.google.comチュニジアTN
?
.ja.turkish#holiday@group.v.calendar.google.com	トルコTR
O
)ja.tt#holiday@group.v.calendar.google.comトリニダード・トバゴTT
;
-ja.taiwan#holiday@group.v.calendar.google.com台湾TW
@
)ja.tz#holiday@group.v.calendar.google.comタンザニアTZ
G
0ja.ukrainian#holiday@group.v.calendar.google.comウクライナUA
=
)ja.ug#holiday@group.v.calendar.google.comウガンダUG
G
*ja.usa#holiday@group.v.calendar.google.comアメリカ合衆国US
@
)ja.uy#holiday@group.v.calendar.google.comウルグアイUY
F
)ja.uz#holiday@group.v.calendar.google.comウズベキスタンUZ
C
)ja.va#holiday@group.v.calendar.google.comバチカン市国VA
@
)ja.ve#holiday@group.v.calendar.google.comベネズエラVE
L
)ja.vi#holiday@group.v.calendar.google.com米領ヴァージン諸島VI
E
1ja.vietnamese#holiday@group.v.calendar.google.comベトナムVN
=
)ja.ye#holiday@group.v.calendar.google.comイエメンYE
@
)ja.yt#holiday@group.v.calendar.google.comマヨット島YT
@
)ja.sa#holiday@group.v.calendar.google.com南アフリカZA
=
)ja.zm#holiday@group.v.calendar.google.comザンビアZM
@
)ja.zw#holiday@group.v.calendar.google.comジンバブエZWL
0ja.christian#holiday@group.v.calendar.google.comキリスト教の祝日G
.ja.judaism#holiday@group.v.calendar.google.comユダヤ教の祝日J
.ja.islamic#holiday@group.v.calendar.google.comイスラム教の祝日R
<ja.orthodox_christianity#holiday@group.v.calendar.google.com正教会の祝日ja