
=
)sr.ad#holiday@group.v.calendar.google.comАндораAD
a
)sr.ae#holiday@group.v.calendar.google.com0Уједињени Арапски ЕмиратиAE
E
)sr.af#holiday@group.v.calendar.google.comАвганистанAF
A
)sr.al#holiday@group.v.calendar.google.comАлбанијаAL
C
)sr.am#holiday@group.v.calendar.google.comЈерменијаAM
=
)sr.ao#holiday@group.v.calendar.google.comАнголаAO
C
)sr.ar#holiday@group.v.calendar.google.comАргентинаAR
G
/sr.austrian#holiday@group.v.calendar.google.comАустријаAT
M
1sr.australian#holiday@group.v.calendar.google.comАустралијаAU
;
)sr.aw#holiday@group.v.calendar.google.com
АрубаAW
E
)sr.az#holiday@group.v.calendar.google.comАзербејџанAZ
U
)sr.ba#holiday@group.v.calendar.google.com$Босна и ХерцеговинаBA
A
)sr.bb#holiday@group.v.calendar.google.comБарбадосBB
C
)sr.bd#holiday@group.v.calendar.google.comБангладешBD
?
)sr.be#holiday@group.v.calendar.google.comБелгијаBE
H
)sr.bf#holiday@group.v.calendar.google.comБуркина ФасоBF
H
0sr.bulgarian#holiday@group.v.calendar.google.comБугарскаBG
?
)sr.bh#holiday@group.v.calendar.google.comБахреинBH
?
)sr.bi#holiday@group.v.calendar.google.comБурундиBI
;
)sr.bj#holiday@group.v.calendar.google.com
БенинBJ
?
)sr.bm#holiday@group.v.calendar.google.comБермудаBM
A
)sr.bo#holiday@group.v.calendar.google.comБоливијаBO
D
0sr.brazilian#holiday@group.v.calendar.google.comБразилBR
=
)sr.bs#holiday@group.v.calendar.google.comБахамиBS
?
)sr.bw#holiday@group.v.calendar.google.comБоцванаBW
E
)sr.by#holiday@group.v.calendar.google.comБелорусијаBY
C
/sr.canadian#holiday@group.v.calendar.google.comКанадаCA
L
)sr.cd#holiday@group.v.calendar.google.comКонго - КиншасаCD
d
)sr.cf#holiday@group.v.calendar.google.com3Централноафричка РепубликаCF
N
)sr.cg#holiday@group.v.calendar.google.comКонго - БразавилCG
E
)sr.ch#holiday@group.v.calendar.google.comШвајцарскаCH
N
)sr.ci#holiday@group.v.calendar.google.comОбала СлоновачеCI
9
)sr.cl#holiday@group.v.calendar.google.comЧилеCL
?
)sr.cm#holiday@group.v.calendar.google.comКамерунCM
<
,sr.china#holiday@group.v.calendar.google.comКинаCN
C
)sr.co#holiday@group.v.calendar.google.comКолумбијаCO
C
)sr.cr#holiday@group.v.calendar.google.comКостарикаCR
9
)sr.cu#holiday@group.v.calendar.google.comКубаCU
T
)sr.cv#holiday@group.v.calendar.google.com#Зеленортска ОстрваCV
;
)sr.cy#holiday@group.v.calendar.google.com
КипарCY
>
,sr.czech#holiday@group.v.calendar.google.com
ЧешкаCZ
C
-sr.german#holiday@group.v.calendar.google.comНемачкаDE
A
-sr.danish#holiday@group.v.calendar.google.comДанскаDK
\
)sr.do#holiday@group.v.calendar.google.com+Доминиканска РепубликаDO
;
)sr.dz#holiday@group.v.calendar.google.com
АлжирDZ
?
)sr.ec#holiday@group.v.calendar.google.comЕквадорEC
A
)sr.ee#holiday@group.v.calendar.google.comЕстонијаEE
=
)sr.eg#holiday@group.v.calendar.google.comЕгипатEG
A
)sr.er#holiday@group.v.calendar.google.comЕритрејаER
B
,sr.spain#holiday@group.v.calendar.google.comШпанијаES
A
)sr.et#holiday@group.v.calendar.google.comЕтиопијаET
B
.sr.finnish#holiday@group.v.calendar.google.comФинскаFI
9
)sr.fj#holiday@group.v.calendar.google.comФиџиFJ
J
)sr.fo#holiday@group.v.calendar.google.comФарска ОстрваFO
G
-sr.french#holiday@group.v.calendar.google.comФранцускаFR
;
)sr.ga#holiday@group.v.calendar.google.com
ГабонGA
X
)sr.uk#holiday@group.v.calendar.google.com'Уједињено КраљевствоGB
?
)sr.gd#holiday@group.v.calendar.google.comГренадаGD
?
)sr.ge#holiday@group.v.calendar.google.comГрузијаGE
9
)sr.gh#holiday@group.v.calendar.google.comГанаGH
C
)sr.gi#holiday@group.v.calendar.google.comГибралтарGI
A
)sr.gl#holiday@group.v.calendar.google.comГренландGL
?
)sr.gm#holiday@group.v.calendar.google.comГамбијаGM
?
)sr.gn#holiday@group.v.calendar.google.comГвинејаGN
Z
)sr.gq#holiday@group.v.calendar.google.com)Екваторијална ГвинејаGQ
>
,sr.greek#holiday@group.v.calendar.google.com
ГрчкаGR
C
)sr.gt#holiday@group.v.calendar.google.comГватемалаGT
9
)sr.gu#holiday@group.v.calendar.google.comГуамGU
J
)sr.gw#holiday@group.v.calendar.google.comГвинеја-БисаоGW
H
0sr.hong_kong#holiday@group.v.calendar.google.comХонгконгHK
A
)sr.hn#holiday@group.v.calendar.google.comХондурасHN
G
/sr.croatian#holiday@group.v.calendar.google.comХрватскаHR
;
)sr.ht#holiday@group.v.calendar.google.com
ХаитиHT
H
0sr.hungarian#holiday@group.v.calendar.google.comМађарскаHU
M
1sr.indonesian#holiday@group.v.calendar.google.comИндонезијаID
>
,sr.irish#holiday@group.v.calendar.google.com
ИрскаIE
A
-sr.jewish#holiday@group.v.calendar.google.comИзраелIL
A
-sr.indian#holiday@group.v.calendar.google.comИндијаIN
9
)sr.iq#holiday@group.v.calendar.google.comИракIQ
9
)sr.ir#holiday@group.v.calendar.google.comИранIR
=
)sr.is#holiday@group.v.calendar.google.comИсландIS
D
.sr.italian#holiday@group.v.calendar.google.comИталијаIT
?
)sr.jm#holiday@group.v.calendar.google.comЈамајкаJM
=
)sr.jo#holiday@group.v.calendar.google.comЈорданJO
A
/sr.japanese#holiday@group.v.calendar.google.com
ЈапанJP
=
)sr.ke#holiday@group.v.calendar.google.comКенијаKE
C
)sr.kg#holiday@group.v.calendar.google.comКиргистанKG
?
)sr.kh#holiday@group.v.calendar.google.comКамбоџаKH
N
)sr.km#holiday@group.v.calendar.google.comКоморска ОстрваKM
L
)sr.kp#holiday@group.v.calendar.google.comСеверна КорејаKP
Q
2sr.south_korea#holiday@group.v.calendar.google.comЈужна КорејаKR
=
)sr.kw#holiday@group.v.calendar.google.comКувајтKW
P
)sr.ky#holiday@group.v.calendar.google.comКајманска ОстрваKY
C
)sr.kz#holiday@group.v.calendar.google.comКазахстанKZ
;
)sr.lb#holiday@group.v.calendar.google.com
ЛибанLB
G
)sr.li#holiday@group.v.calendar.google.comЛихтенштајнLI
B
)sr.lk#holiday@group.v.calendar.google.comШри ЛанкаLK
A
)sr.lr#holiday@group.v.calendar.google.comЛиберијаLR
=
)sr.ls#holiday@group.v.calendar.google.comЛесотоLS
K
1sr.lithuanian#holiday@group.v.calendar.google.comЛитванијаLT
E
)sr.lu#holiday@group.v.calendar.google.comЛуксембургLU
F
.sr.latvian#holiday@group.v.calendar.google.comЛетонијаLV
=
)sr.ly#holiday@group.v.calendar.google.comЛибијаLY
=
)sr.ma#holiday@group.v.calendar.google.comМарокоMA
=
)sr.mc#holiday@group.v.calendar.google.comМонакоMC
C
)sr.md#holiday@group.v.calendar.google.comМолдавијаMD
B
)sr.me#holiday@group.v.calendar.google.comЦрна ГораME
E
)sr.mg#holiday@group.v.calendar.google.comМадагаскарMG
E
)sr.mk#holiday@group.v.calendar.google.comМакедонијаMK
9
)sr.ml#holiday@group.v.calendar.google.comМалиML
C
)sr.mn#holiday@group.v.calendar.google.comМонголијаMN
;
)sr.mo#holiday@group.v.calendar.google.com
МакаоMO
A
)sr.mq#holiday@group.v.calendar.google.comМартиникMQ
;
)sr.mt#holiday@group.v.calendar.google.com
МалтаMT
E
)sr.mu#holiday@group.v.calendar.google.comМаурицијусMU
=
)sr.mw#holiday@group.v.calendar.google.comМалавиMW
D
.sr.mexican#holiday@group.v.calendar.google.comМексикоMX
G
/sr.malaysia#holiday@group.v.calendar.google.comМалезијаMY
A
)sr.mz#holiday@group.v.calendar.google.comМозамбикMZ
A
)sr.na#holiday@group.v.calendar.google.comНамибијаNA
;
)sr.ne#holiday@group.v.calendar.google.com
НигерNE
A
)sr.ng#holiday@group.v.calendar.google.comНигеријаNG
C
)sr.ni#holiday@group.v.calendar.google.comНикарагваNI
F
,sr.dutch#holiday@group.v.calendar.google.comХоландијаNL
H
0sr.norwegian#holiday@group.v.calendar.google.comНорвешкаNO
;
)sr.np#holiday@group.v.calendar.google.com
НепалNP
O
2sr.new_zealand#holiday@group.v.calendar.google.comНови ЗеландNZ
9
)sr.om#holiday@group.v.calendar.google.comОманOM
=
)sr.pa#holiday@group.v.calendar.google.comПанамаPA
9
)sr.pe#holiday@group.v.calendar.google.comПеруPE
J
2sr.philippines#holiday@group.v.calendar.google.comФилипиниPH
A
)sr.pk#holiday@group.v.calendar.google.comПакистанPK
A
-sr.polish#holiday@group.v.calendar.google.comПољскаPL
C
)sr.pr#holiday@group.v.calendar.google.comПорторикоPR
O
1sr.portuguese#holiday@group.v.calendar.google.comПортугалијаPT
A
)sr.py#holiday@group.v.calendar.google.comПарагвајPY
;
)sr.qa#holiday@group.v.calendar.google.com
КатарQA
?
)sr.re#holiday@group.v.calendar.google.comРеинионRE
G
/sr.romanian#holiday@group.v.calendar.google.comРумунијаRO
=
)sr.rs#holiday@group.v.calendar.google.comСрбијаRS
B
.sr.russian#holiday@group.v.calendar.google.comРусијаRU
=
)sr.rw#holiday@group.v.calendar.google.comРуандаRW
\
3sr.saudiarabian#holiday@group.v.calendar.google.com!Саудијска АрабијаSA
?
)sr.sc#holiday@group.v.calendar.google.comСејшелиSC
;
)sr.sd#holiday@group.v.calendar.google.com
СуданSD
D
.sr.swedish#holiday@group.v.calendar.google.comШведскаSE
H
0sr.singapore#holiday@group.v.calendar.google.comСингапурSG
H
)sr.sh#holiday@group.v.calendar.google.comСвета ЈеленаSH
J
0sr.slovenian#holiday@group.v.calendar.google.comСловенијаSI
E
-sr.slovak#holiday@group.v.calendar.google.comСловачкаSK
H
)sr.sl#holiday@group.v.calendar.google.comСијера ЛеонеSL
D
)sr.sm#holiday@group.v.calendar.google.comСан МариноSM
?
)sr.sn#holiday@group.v.calendar.google.comСенегалSN
A
)sr.so#holiday@group.v.calendar.google.comСомалијаSO
?
)sr.sr#holiday@group.v.calendar.google.comСуринамSR
F
)sr.ss#holiday@group.v.calendar.google.comЈужни СуданSS
T
)sr.st#holiday@group.v.calendar.google.com#Сао Томе и ПринципеST
A
)sr.sv#holiday@group.v.calendar.google.comСалвадорSV
=
)sr.sy#holiday@group.v.calendar.google.comСиријаSY
C
)sr.sz#holiday@group.v.calendar.google.comСвазилендSZ
7
)sr.td#holiday@group.v.calendar.google.comЧадTD
9
)sr.tg#holiday@group.v.calendar.google.comТогоTG
?
)sr.th#holiday@group.v.calendar.google.comТајландTH
;
)sr.tn#holiday@group.v.calendar.google.com
ТунисTN
B
.sr.turkish#holiday@group.v.calendar.google.comТурскаTR
Q
)sr.tt#holiday@group.v.calendar.google.com Тринидад и ТобагоTT
A
-sr.taiwan#holiday@group.v.calendar.google.comТајванTW
C
)sr.tz#holiday@group.v.calendar.google.comТанзанијаTZ
H
0sr.ukrainian#holiday@group.v.calendar.google.comУкрајинаUA
=
)sr.ug#holiday@group.v.calendar.google.comУгандаUG
Q
*sr.usa#holiday@group.v.calendar.google.comСједињене ДржавеUS
?
)sr.uy#holiday@group.v.calendar.google.comУругвајUY
E
)sr.uz#holiday@group.v.calendar.google.comУзбекистанUZ
?
)sr.va#holiday@group.v.calendar.google.comВатиканVA
C
)sr.ve#holiday@group.v.calendar.google.comВенецуелаVE
c
)sr.vi#holiday@group.v.calendar.google.com2Америчка Девичанска ОстрваVI
I
1sr.vietnamese#holiday@group.v.calendar.google.comВијетнамVN
;
)sr.ye#holiday@group.v.calendar.google.com
ЈеменYE
;
)sr.yt#holiday@group.v.calendar.google.com
МајотYT
\
)sr.sa#holiday@group.v.calendar.google.com+Јужноафричка РепубликаZA
?
)sr.zm#holiday@group.v.calendar.google.comЗамбијаZM
A
)sr.zw#holiday@group.v.calendar.google.comЗимбабвеZWl
0sr.christian#holiday@group.v.calendar.google.com8Католички хришћански празнициU
.sr.judaism#holiday@group.v.calendar.google.com#Јеврејски празнициY
.sr.islamic#holiday@group.v.calendar.google.com'Муслимански празници|
<sr.orthodox_christianity#holiday@group.v.calendar.google.com<Православни хришћански празнициsr