
L
)th.ad#holiday@group.v.calendar.google.comอันดอร์ราAD
m
)th.ae#holiday@group.v.calendar.google.com<สหรัฐอาหรับเอมิเรตส์AE
R
)th.af#holiday@group.v.calendar.google.com!อัฟกานิสถานAF
L
)th.al#holiday@group.v.calendar.google.comแอลเบเนียAL
O
)th.am#holiday@group.v.calendar.google.comอาร์เมเนียAM
F
)th.ao#holiday@group.v.calendar.google.comแองโกลาAO
R
)th.ar#holiday@group.v.calendar.google.com!อาร์เจนตินาAR
O
/th.austrian#holiday@group.v.calendar.google.comออสเตรียAT
W
1th.australian#holiday@group.v.calendar.google.comออสเตรเลียAU
C
)th.aw#holiday@group.v.calendar.google.comอารูบาAW
U
)th.az#holiday@group.v.calendar.google.com$อาเซอร์ไบจานAZ
v
)th.ba#holiday@group.v.calendar.google.comEบอสเนียและเฮอร์เซโกวีนาBA
L
)th.bb#holiday@group.v.calendar.google.comบาร์เบโดสBB
L
)th.bd#holiday@group.v.calendar.google.comบังกลาเทศBD
I
)th.be#holiday@group.v.calendar.google.comเบลเยียมBE
U
)th.bf#holiday@group.v.calendar.google.com$บูร์กินาฟาโซBF
S
0th.bulgarian#holiday@group.v.calendar.google.comบัลแกเรียBG
F
)th.bh#holiday@group.v.calendar.google.comบาห์เรนBH
F
)th.bi#holiday@group.v.calendar.google.comบุรุนดีBI
@
)th.bj#holiday@group.v.calendar.google.comเบนินBJ
O
)th.bm#holiday@group.v.calendar.google.comเบอร์มิวดาBM
I
)th.bo#holiday@group.v.calendar.google.comโบลิเวียBO
J
0th.brazilian#holiday@group.v.calendar.google.comบราซิลBR
F
)th.bs#holiday@group.v.calendar.google.comบาฮามาสBS
I
)th.bw#holiday@group.v.calendar.google.comบอตสวานาBW
F
)th.by#holiday@group.v.calendar.google.comเบลารุสBY
I
/th.canadian#holiday@group.v.calendar.google.comแคนาดาCA
V
)th.cd#holiday@group.v.calendar.google.com%คองโก-กินชาซาCD
m
)th.cf#holiday@group.v.calendar.google.com<สาธารณรัฐแอฟริกากลางCF
\
)th.cg#holiday@group.v.calendar.google.com+คองโก-บราซซาวิลCG
[
)th.ch#holiday@group.v.calendar.google.com*สวิตเซอร์แลนด์CH
O
)th.ci#holiday@group.v.calendar.google.comโกตดิวัวร์CI
=
)th.cl#holiday@group.v.calendar.google.comชิลีCL
I
)th.cm#holiday@group.v.calendar.google.comแคเมอรูนCM
=
,th.china#holiday@group.v.calendar.google.com	จีนCN
L
)th.co#holiday@group.v.calendar.google.comโคลอมเบียCO
L
)th.cr#holiday@group.v.calendar.google.comคอสตาริกาCR
@
)th.cu#holiday@group.v.calendar.google.comคิวบาCU
L
)th.cv#holiday@group.v.calendar.google.comเคปเวิร์ดCV
C
)th.cy#holiday@group.v.calendar.google.comไซปรัสCY
[
,th.czech#holiday@group.v.calendar.google.com'สาธารณรัฐเช็กCZ
J
-th.german#holiday@group.v.calendar.google.comเยอรมนีDE
M
-th.danish#holiday@group.v.calendar.google.comเดนมาร์กDK
g
)th.do#holiday@group.v.calendar.google.com6สาธารณรัฐโดมินิกันDO
L
)th.dz#holiday@group.v.calendar.google.comแอลจีเรียDZ
L
)th.ec#holiday@group.v.calendar.google.comเอกวาดอร์EC
L
)th.ee#holiday@group.v.calendar.google.comเอสโตเนียEE
F
)th.eg#holiday@group.v.calendar.google.comอียิปต์EG
L
)th.er#holiday@group.v.calendar.google.comเอริเทรียER
@
,th.spain#holiday@group.v.calendar.google.comสเปนES
O
)th.et#holiday@group.v.calendar.google.comเอธิโอเปียET
N
.th.finnish#holiday@group.v.calendar.google.comฟินแลนด์FI
=
)th.fj#holiday@group.v.calendar.google.comฟิจิFJ
U
)th.fo#holiday@group.v.calendar.google.com$หมู่เกาะแฟโรFO
M
-th.french#holiday@group.v.calendar.google.comฝรั่งเศสFR
@
)th.ga#holiday@group.v.calendar.google.comกาบองGA
X
)th.uk#holiday@group.v.calendar.google.com'สหราชอาณาจักรGB
F
)th.gd#holiday@group.v.calendar.google.comเกรเนดาGD
I
)th.ge#holiday@group.v.calendar.google.comจอร์เจียGE
=
)th.gh#holiday@group.v.calendar.google.comกานาGH
O
)th.gi#holiday@group.v.calendar.google.comยิบรอลตาร์GI
L
)th.gl#holiday@group.v.calendar.google.comกรีนแลนด์GL
F
)th.gm#holiday@group.v.calendar.google.comแกมเบียGM
=
)th.gn#holiday@group.v.calendar.google.comกินีGN
a
)th.gq#holiday@group.v.calendar.google.com0อิเควทอเรียลกินีGQ
@
,th.greek#holiday@group.v.calendar.google.comกรีซGR
L
)th.gt#holiday@group.v.calendar.google.comกัวเตมาลาGT
:
)th.gu#holiday@group.v.calendar.google.com	กวมGU
P
)th.gw#holiday@group.v.calendar.google.comกินี-บิสเซาGW
J
0th.hong_kong#holiday@group.v.calendar.google.comฮ่องกงHK
I
)th.hn#holiday@group.v.calendar.google.comฮอนดูรัสHN
R
/th.croatian#holiday@group.v.calendar.google.comโครเอเชียHR
=
)th.ht#holiday@group.v.calendar.google.comเฮติHT
M
0th.hungarian#holiday@group.v.calendar.google.comฮังการีHU
Z
1th.indonesian#holiday@group.v.calendar.google.com!อินโดนีเซียID
O
,th.irish#holiday@group.v.calendar.google.comไอร์แลนด์IE
M
-th.jewish#holiday@group.v.calendar.google.comอิสราเอลIL
J
-th.indian#holiday@group.v.calendar.google.comอินเดียIN
@
)th.iq#holiday@group.v.calendar.google.comอิรักIQ
F
)th.ir#holiday@group.v.calendar.google.comอิหร่านIR
L
)th.is#holiday@group.v.calendar.google.comไอซ์แลนด์IS
H
.th.italian#holiday@group.v.calendar.google.comอิตาลีIT
C
)th.jm#holiday@group.v.calendar.google.comจาเมกาJM
F
)th.jo#holiday@group.v.calendar.google.comจอร์แดนJO
L
/th.japanese#holiday@group.v.calendar.google.comญี่ปุ่นJP
@
)th.ke#holiday@group.v.calendar.google.comเคนยาKE
R
)th.kg#holiday@group.v.calendar.google.com!คีร์กีซสถานKG
F
)th.kh#holiday@group.v.calendar.google.comกัมพูชาKH
F
)th.km#holiday@group.v.calendar.google.comคอโมโรสKM
R
)th.kp#holiday@group.v.calendar.google.com!เกาหลีเหนือKP
U
2th.south_korea#holiday@group.v.calendar.google.comเกาหลีใต้KR
@
)th.kw#holiday@group.v.calendar.google.comคูเวตKW
^
)th.ky#holiday@group.v.calendar.google.com-หมู่เกาะเคย์แมนKY
L
)th.kz#holiday@group.v.calendar.google.comคาซัคสถานKZ
F
)th.lb#holiday@group.v.calendar.google.comเลบานอนLB
R
)th.li#holiday@group.v.calendar.google.com!ลิกเตนสไตน์LI
I
)th.lk#holiday@group.v.calendar.google.comศรีลังกาLK
I
)th.lr#holiday@group.v.calendar.google.comไลบีเรียLR
C
)th.ls#holiday@group.v.calendar.google.comเลโซโทLS
T
1th.lithuanian#holiday@group.v.calendar.google.comลิทัวเนียLT
U
)th.lu#holiday@group.v.calendar.google.com$ลักเซมเบิร์กLU
K
.th.latvian#holiday@group.v.calendar.google.comลัตเวียLV
C
)th.ly#holiday@group.v.calendar.google.comลิเบียLY
I
)th.ma#holiday@group.v.calendar.google.comโมร็อกโกMA
C
)th.mc#holiday@group.v.calendar.google.comโมนาโกMC
F
)th.md#holiday@group.v.calendar.google.comมอลโดวาMD
O
)th.me#holiday@group.v.calendar.google.comมอนเตเนโกรME
R
)th.mg#holiday@group.v.calendar.google.com!มาดากัสการ์MG
O
)th.mk#holiday@group.v.calendar.google.comมาซิโดเนียMK
=
)th.ml#holiday@group.v.calendar.google.comมาลีML
L
)th.mn#holiday@group.v.calendar.google.comมองโกเลียMN
C
)th.mo#holiday@group.v.calendar.google.comมาเก๊าMO
L
)th.mq#holiday@group.v.calendar.google.comมาร์ตินีกMQ
@
)th.mt#holiday@group.v.calendar.google.comมอลตาMT
L
)th.mu#holiday@group.v.calendar.google.comมอริเชียสMU
C
)th.mw#holiday@group.v.calendar.google.comมาลาวีMW
N
.th.mexican#holiday@group.v.calendar.google.comเม็กซิโกMX
O
/th.malaysia#holiday@group.v.calendar.google.comมาเลเซียMY
I
)th.mz#holiday@group.v.calendar.google.comโมซัมบิกMZ
I
)th.na#holiday@group.v.calendar.google.comนามิเบียNA
F
)th.ne#holiday@group.v.calendar.google.comไนเจอร์NE
I
)th.ng#holiday@group.v.calendar.google.comไนจีเรียNG
L
)th.ni#holiday@group.v.calendar.google.comนิการากัวNI
X
,th.dutch#holiday@group.v.calendar.google.com$เนเธอร์แลนด์NL
P
0th.norwegian#holiday@group.v.calendar.google.comนอร์เวย์NO
@
)th.np#holiday@group.v.calendar.google.comเนปาลNP
X
2th.new_zealand#holiday@group.v.calendar.google.comนิวซีแลนด์NZ
@
)th.om#holiday@group.v.calendar.google.comโอมานOM
C
)th.pa#holiday@group.v.calendar.google.comปานามาPA
=
)th.pe#holiday@group.v.calendar.google.comเปรูPE
X
2th.philippines#holiday@group.v.calendar.google.comฟิลิปปินส์PH
I
)th.pk#holiday@group.v.calendar.google.comปากีสถานPK
J
-th.polish#holiday@group.v.calendar.google.comโปแลนด์PL
R
)th.pr#holiday@group.v.calendar.google.com!เปอร์โตริโกPR
Q
1th.portuguese#holiday@group.v.calendar.google.comโปรตุเกสPT
I
)th.py#holiday@group.v.calendar.google.comปารากวัยPY
C
)th.qa#holiday@group.v.calendar.google.comกาตาร์QA
I
)th.re#holiday@group.v.calendar.google.comเรอูนียงRE
O
/th.romanian#holiday@group.v.calendar.google.comโรมาเนียRO
L
)th.rs#holiday@group.v.calendar.google.comเซอร์เบียRS
K
.th.russian#holiday@group.v.calendar.google.comรัสเซียRU
C
)th.rw#holiday@group.v.calendar.google.comรวันดาRW
e
3th.saudiarabian#holiday@group.v.calendar.google.com*ซาอุดีอาระเบียSA
F
)th.sc#holiday@group.v.calendar.google.comเซเชลส์SC
@
)th.sd#holiday@group.v.calendar.google.comซูดานSD
H
.th.swedish#holiday@group.v.calendar.google.comสวีเดนSE
P
0th.singapore#holiday@group.v.calendar.google.comสิงคโปร์SG
R
)th.sh#holiday@group.v.calendar.google.com!เซนต์เฮเลนาSH
S
0th.slovenian#holiday@group.v.calendar.google.comสโลวีเนียSI
P
-th.slovak#holiday@group.v.calendar.google.comสโลวะเกียSK
X
)th.sl#holiday@group.v.calendar.google.com'เซียร์ราลีโอนSL
L
)th.sm#holiday@group.v.calendar.google.comซานมารีโนSM
F
)th.sn#holiday@group.v.calendar.google.comเซเนกัลSN
I
)th.so#holiday@group.v.calendar.google.comโซมาเลียSO
I
)th.sr#holiday@group.v.calendar.google.comซูรินาเมSR
I
)th.ss#holiday@group.v.calendar.google.comซูดานใต้SS
g
)th.st#holiday@group.v.calendar.google.com6เซาตูเมและปรินซิปีST
U
)th.sv#holiday@group.v.calendar.google.com$เอลซัลวาดอร์SV
C
)th.sy#holiday@group.v.calendar.google.comซีเรียSY
O
)th.sz#holiday@group.v.calendar.google.comสวาซิแลนด์SZ
:
)th.td#holiday@group.v.calendar.google.com	ชาดTD
=
)th.tg#holiday@group.v.calendar.google.comโตโกTG
:
)th.th#holiday@group.v.calendar.google.com	ไทยTH
I
)th.tn#holiday@group.v.calendar.google.comตูนิเซียTN
E
.th.turkish#holiday@group.v.calendar.google.comตุรกีTR
d
)th.tt#holiday@group.v.calendar.google.com3ตรินิแดดและโตเบโกTT
J
-th.taiwan#holiday@group.v.calendar.google.comไต้หวันTW
L
)th.tz#holiday@group.v.calendar.google.comแทนซาเนียTZ
J
0th.ukrainian#holiday@group.v.calendar.google.comยูเครนUA
F
)th.ug#holiday@group.v.calendar.google.comยูกันดาUG
V
*th.usa#holiday@group.v.calendar.google.com$สหรัฐอเมริกาUS
I
)th.uy#holiday@group.v.calendar.google.comอุรุกวัยUY
R
)th.uz#holiday@group.v.calendar.google.com!อุซเบกิสถานUZ
O
)th.va#holiday@group.v.calendar.google.comนครวาติกันVA
O
)th.ve#holiday@group.v.calendar.google.comเวเนซุเอลาVE
p
)th.vi#holiday@group.v.calendar.google.com?หมู่เกาะยูเอสเวอร์จินVI
Q
1th.vietnamese#holiday@group.v.calendar.google.comเวียดนามVN
@
)th.ye#holiday@group.v.calendar.google.comเยเมนYE
@
)th.yt#holiday@group.v.calendar.google.comมายอตYT
O
)th.sa#holiday@group.v.calendar.google.comแอฟริกาใต้ZA
F
)th.zm#holiday@group.v.calendar.google.comแซมเบียZM
I
)th.zw#holiday@group.v.calendar.google.comซิมบับเวZWj
0th.christian#holiday@group.v.calendar.google.com6วันหยุดศาสนาคริสต์_
.th.judaism#holiday@group.v.calendar.google.com-วันหยุดศาสนายิวh
.th.islamic#holiday@group.v.calendar.google.com6วันหยุดศาสนาอิสลาม�
<th.orthodox_christianity#holiday@group.v.calendar.google.comEวันหยุดนิกายออร์โธดอกซ์th