
?
)mn.ad#holiday@group.v.calendar.google.comАндорраAD
Y
)mn.ae#holiday@group.v.calendar.google.com(Арабын Нэгдсэн ЭмиратAE
E
)mn.af#holiday@group.v.calendar.google.comАфганистанAF
=
)mn.al#holiday@group.v.calendar.google.comАлбаниAL
=
)mn.am#holiday@group.v.calendar.google.comАрмениAM
;
)mn.ao#holiday@group.v.calendar.google.com
АнголAO
A
)mn.ar#holiday@group.v.calendar.google.comАргентинAR
C
/mn.austrian#holiday@group.v.calendar.google.comАвстриAT
I
1mn.australian#holiday@group.v.calendar.google.comАвстралиAU
;
)mn.aw#holiday@group.v.calendar.google.com
АрубаAW
E
)mn.az#holiday@group.v.calendar.google.comАзербайжанAZ
P
)mn.ba#holiday@group.v.calendar.google.comБосни ГерцеговинBA
A
)mn.bb#holiday@group.v.calendar.google.comБарбадосBB
C
)mn.bd#holiday@group.v.calendar.google.comБангладешBD
;
)mn.be#holiday@group.v.calendar.google.com
БелгиBE
H
)mn.bf#holiday@group.v.calendar.google.comБуркина фасоBF
D
0mn.bulgarian#holiday@group.v.calendar.google.comБолгарBG
?
)mn.bh#holiday@group.v.calendar.google.comБахрейнBH
?
)mn.bi#holiday@group.v.calendar.google.comБурундиBI
;
)mn.bj#holiday@group.v.calendar.google.com
БенинBJ
=
)mn.bm#holiday@group.v.calendar.google.comБермудBM
=
)mn.bo#holiday@group.v.calendar.google.comБоливиBO
D
0mn.brazilian#holiday@group.v.calendar.google.comБразилBR
;
)mn.bs#holiday@group.v.calendar.google.com
БагамBS
A
)mn.bw#holiday@group.v.calendar.google.comБотсванаBW
A
)mn.by#holiday@group.v.calendar.google.comБеларусьBY
A
/mn.canadian#holiday@group.v.calendar.google.com
КанадCA
J
)mn.cd#holiday@group.v.calendar.google.comКонго-КиншасаCD
k
)mn.cf#holiday@group.v.calendar.google.com:Төв Африкийн Бүгд Найрамдах УлсCF
P
)mn.cg#holiday@group.v.calendar.google.comКонго БраззавильCG
A
)mn.ch#holiday@group.v.calendar.google.comШвейцариCH
G
)mn.ci#holiday@group.v.calendar.google.comКот д’ИвуарCI
9
)mn.cl#holiday@group.v.calendar.google.comЧилиCL
?
)mn.cm#holiday@group.v.calendar.google.comКамерунCM
>
,mn.china#holiday@group.v.calendar.google.com
ХятадCN
=
)mn.co#holiday@group.v.calendar.google.comКолумбCO
D
)mn.cr#holiday@group.v.calendar.google.comКоста РикаCR
9
)mn.cu#holiday@group.v.calendar.google.comКубаCU
D
)mn.cv#holiday@group.v.calendar.google.comКапе ВердеCV
9
)mn.cy#holiday@group.v.calendar.google.comКипрCY
]
,mn.czech#holiday@group.v.calendar.google.com)Бүгд Найрамдах Чех УлсCZ
A
-mn.german#holiday@group.v.calendar.google.comГерманDE
=
-mn.danish#holiday@group.v.calendar.google.comДаниDK
f
)mn.do#holiday@group.v.calendar.google.com5Бүгд Найрамдах Доминикан УлсDO
;
)mn.dz#holiday@group.v.calendar.google.com
АлжирDZ
?
)mn.ec#holiday@group.v.calendar.google.comЭквадорEC
=
)mn.ee#holiday@group.v.calendar.google.comЭстониEE
=
)mn.eg#holiday@group.v.calendar.google.comЕгипетEG
=
)mn.er#holiday@group.v.calendar.google.comЭритриER
@
,mn.spain#holiday@group.v.calendar.google.comИспаниES
;
)mn.et#holiday@group.v.calendar.google.com
ЭтиопET
D
.mn.finnish#holiday@group.v.calendar.google.comФинландFI
9
)mn.fj#holiday@group.v.calendar.google.comФижиFJ
H
)mn.fo#holiday@group.v.calendar.google.comФароэ АрлуудFO
?
-mn.french#holiday@group.v.calendar.google.com
ФранцFR
;
)mn.ga#holiday@group.v.calendar.google.com
ГабонGA
D
)mn.uk#holiday@group.v.calendar.google.comИх БританиGB
?
)mn.gd#holiday@group.v.calendar.google.comГренадаGD
9
)mn.ge#holiday@group.v.calendar.google.comГүржGE
9
)mn.gh#holiday@group.v.calendar.google.comГанаGH
C
)mn.gi#holiday@group.v.calendar.google.comГибралтарGI
A
)mn.gl#holiday@group.v.calendar.google.comГренландGL
;
)mn.gm#holiday@group.v.calendar.google.com
ГамбиGM
=
)mn.gn#holiday@group.v.calendar.google.comГвинейGN
P
)mn.gq#holiday@group.v.calendar.google.comЭкваторын ГвинейGQ
<
,mn.greek#holiday@group.v.calendar.google.comГрекGR
A
)mn.gt#holiday@group.v.calendar.google.comГватемалGT
9
)mn.gu#holiday@group.v.calendar.google.comГуамGU
H
)mn.gw#holiday@group.v.calendar.google.comГвиней-БисауGW
I
0mn.hong_kong#holiday@group.v.calendar.google.comХонг КонгHK
A
)mn.hn#holiday@group.v.calendar.google.comГондурасHN
C
/mn.croatian#holiday@group.v.calendar.google.comХорватHR
;
)mn.ht#holiday@group.v.calendar.google.com
ГаитиHT
B
0mn.hungarian#holiday@group.v.calendar.google.com
УнгарHU
I
1mn.indonesian#holiday@group.v.calendar.google.comИндонезиID
@
,mn.irish#holiday@group.v.calendar.google.comИрландIE
C
-mn.jewish#holiday@group.v.calendar.google.comИзраильIL
C
-mn.indian#holiday@group.v.calendar.google.comЭнэтхэгIN
9
)mn.iq#holiday@group.v.calendar.google.comИракIQ
9
)mn.ir#holiday@group.v.calendar.google.comИранIR
=
)mn.is#holiday@group.v.calendar.google.comИсландIS
@
.mn.italian#holiday@group.v.calendar.google.com
ИталиIT
;
)mn.jm#holiday@group.v.calendar.google.com
ЯмайкJM
=
)mn.jo#holiday@group.v.calendar.google.comЙорданJO
?
/mn.japanese#holiday@group.v.calendar.google.comЯпонJP
9
)mn.ke#holiday@group.v.calendar.google.comКениKE
E
)mn.kg#holiday@group.v.calendar.google.comКыргызстанKG
=
)mn.kh#holiday@group.v.calendar.google.comКамбожKH
?
)mn.km#holiday@group.v.calendar.google.comКоморосKM
J
)mn.kp#holiday@group.v.calendar.google.comХойд СолонгосKP
U
2mn.south_korea#holiday@group.v.calendar.google.comӨмнөд СолонгосKR
=
)mn.kw#holiday@group.v.calendar.google.comКувейтKW
L
)mn.ky#holiday@group.v.calendar.google.comКайманы АрлуудKY
C
)mn.kz#holiday@group.v.calendar.google.comКазахстанKZ
;
)mn.lb#holiday@group.v.calendar.google.com
ЛиванLB
G
)mn.li#holiday@group.v.calendar.google.comЛихтенштейнLI
B
)mn.lk#holiday@group.v.calendar.google.comШри ЛанкаLK
=
)mn.lr#holiday@group.v.calendar.google.comЛибериLR
=
)mn.ls#holiday@group.v.calendar.google.comЛесотоLS
C
1mn.lithuanian#holiday@group.v.calendar.google.com
ЛитваLT
E
)mn.lu#holiday@group.v.calendar.google.comЛюксембургLU
@
.mn.latvian#holiday@group.v.calendar.google.com
ЛатвиLV
9
)mn.ly#holiday@group.v.calendar.google.comЛивиLY
?
)mn.ma#holiday@group.v.calendar.google.comМароккоMA
=
)mn.mc#holiday@group.v.calendar.google.comМонакоMC
=
)mn.md#holiday@group.v.calendar.google.comМолдавMD
E
)mn.me#holiday@group.v.calendar.google.comМонтенегроME
E
)mn.mg#holiday@group.v.calendar.google.comМадагаскарMG
?
)mn.mk#holiday@group.v.calendar.google.comМакедонMK
9
)mn.ml#holiday@group.v.calendar.google.comМалиML
=
)mn.mn#holiday@group.v.calendar.google.comМонголMN
;
)mn.mo#holiday@group.v.calendar.google.com
МакаоMO
A
)mn.mq#holiday@group.v.calendar.google.comМартиникMQ
=
)mn.mt#holiday@group.v.calendar.google.comМальтаMT
A
)mn.mu#holiday@group.v.calendar.google.comМавритусMU
=
)mn.mw#holiday@group.v.calendar.google.comМалавиMW
B
.mn.mexican#holiday@group.v.calendar.google.comМексикMX
C
/mn.malaysia#holiday@group.v.calendar.google.comМалайзMY
A
)mn.mz#holiday@group.v.calendar.google.comМозамбикMZ
=
)mn.na#holiday@group.v.calendar.google.comНамибиNA
;
)mn.ne#holiday@group.v.calendar.google.com
НигерNE
=
)mn.ng#holiday@group.v.calendar.google.comНигериNG
C
)mn.ni#holiday@group.v.calendar.google.comНикарагуаNI
F
,mn.dutch#holiday@group.v.calendar.google.comНидерландNL
F
0mn.norwegian#holiday@group.v.calendar.google.comНорвегиNO
;
)mn.np#holiday@group.v.calendar.google.com
БалбаNP
O
2mn.new_zealand#holiday@group.v.calendar.google.comШинэ ЗеландNZ
9
)mn.om#holiday@group.v.calendar.google.comОманOM
;
)mn.pa#holiday@group.v.calendar.google.com
ПанамPA
9
)mn.pe#holiday@group.v.calendar.google.comПеруPE
J
2mn.philippines#holiday@group.v.calendar.google.comФилиппинPH
A
)mn.pk#holiday@group.v.calendar.google.comПакистанPK
?
-mn.polish#holiday@group.v.calendar.google.com
ПольшPL
F
)mn.pr#holiday@group.v.calendar.google.comПуэрто РикоPR
K
1mn.portuguese#holiday@group.v.calendar.google.comПортугальPT
A
)mn.py#holiday@group.v.calendar.google.comПарагвайPY
;
)mn.qa#holiday@group.v.calendar.google.com
КатарQA
?
)mn.re#holiday@group.v.calendar.google.comРеюньонRE
A
/mn.romanian#holiday@group.v.calendar.google.com
РумынRO
;
)mn.rs#holiday@group.v.calendar.google.com
СербиRS
>
.mn.russian#holiday@group.v.calendar.google.comОросRU
=
)mn.rw#holiday@group.v.calendar.google.comРуандаRW
P
3mn.saudiarabian#holiday@group.v.calendar.google.comСаудын АрабSA
=
)mn.sc#holiday@group.v.calendar.google.comСейшелSC
;
)mn.sd#holiday@group.v.calendar.google.com
СуданSD
>
.mn.swedish#holiday@group.v.calendar.google.comШведSE
H
0mn.singapore#holiday@group.v.calendar.google.comСингапурSG
F
)mn.sh#holiday@group.v.calendar.google.comСент ХеленаSH
F
0mn.slovenian#holiday@group.v.calendar.google.comСловениSI
A
-mn.slovak#holiday@group.v.calendar.google.comСловакSK
H
)mn.sl#holiday@group.v.calendar.google.comСьерра-ЛеонеSL
D
)mn.sm#holiday@group.v.calendar.google.comСан-МариноSM
?
)mn.sn#holiday@group.v.calendar.google.comСенегалSN
=
)mn.so#holiday@group.v.calendar.google.comСомалиSO
?
)mn.sr#holiday@group.v.calendar.google.comСуринамSR
F
)mn.ss#holiday@group.v.calendar.google.comӨмнөд СуданSS
V
)mn.st#holiday@group.v.calendar.google.com%Сан-Томе ба ПринсипиST
J
)mn.sv#holiday@group.v.calendar.google.comЭль СальвадорSV
9
)mn.sy#holiday@group.v.calendar.google.comСириSY
C
)mn.sz#holiday@group.v.calendar.google.comСвазиландSZ
7
)mn.td#holiday@group.v.calendar.google.comЧадTD
9
)mn.tg#holiday@group.v.calendar.google.comТогоTG
?
)mn.th#holiday@group.v.calendar.google.comТайландTH
;
)mn.tn#holiday@group.v.calendar.google.com
ТунисTN
>
.mn.turkish#holiday@group.v.calendar.google.comТуркTR
N
)mn.tt#holiday@group.v.calendar.google.comТринидад ТобагоTT
C
-mn.taiwan#holiday@group.v.calendar.google.comТайваньTW
?
)mn.tz#holiday@group.v.calendar.google.comТанзаниTZ
D
0mn.ukrainian#holiday@group.v.calendar.google.comУкраинUA
=
)mn.ug#holiday@group.v.calendar.google.comУгандаUG
Z
*mn.usa#holiday@group.v.calendar.google.com(Америкийн Нэгдсэн УлсUS
?
)mn.uy#holiday@group.v.calendar.google.comУругвайUY
E
)mn.uz#holiday@group.v.calendar.google.comУзбекистанUZ
M
)mn.va#holiday@group.v.calendar.google.comВатикан хот улсVA
A
)mn.ve#holiday@group.v.calendar.google.comВенесуэлVE
Z
)mn.vi#holiday@group.v.calendar.google.com)АНУ-ын Виржиний АрлуудVI
G
1mn.vietnamese#holiday@group.v.calendar.google.comВьетнамVN
;
)mn.ye#holiday@group.v.calendar.google.com
ЙеменYE
?
)mn.yt#holiday@group.v.calendar.google.comМайоттеYT
M
)mn.sa#holiday@group.v.calendar.google.comӨмнөд Африк тивZA
;
)mn.zm#holiday@group.v.calendar.google.com
ЗамбиZM
A
)mn.zw#holiday@group.v.calendar.google.comЗимбабвеZWF
0mn.christian#holiday@group.v.calendar.google.comChristian HolidaysA
.mn.judaism#holiday@group.v.calendar.google.comJewish HolidaysA
.mn.islamic#holiday@group.v.calendar.google.comMuslim HolidaysQ
<mn.orthodox_christianity#holiday@group.v.calendar.google.comOrthodox Holidaysmn_MN