
?
)hy.ad#holiday@group.v.calendar.google.comԱնդորրաAD
m
)hy.ae#holiday@group.v.calendar.google.com<Արաբական Միացյալ ԷմիրություններAE
C
)hy.af#holiday@group.v.calendar.google.comԱֆղանստանAF
?
)hy.al#holiday@group.v.calendar.google.comԱլբանիաAL
A
)hy.am#holiday@group.v.calendar.google.comՀայաստանAM
=
)hy.ao#holiday@group.v.calendar.google.comԱնգոլաAO
C
)hy.ar#holiday@group.v.calendar.google.comԱրգենտինաAR
E
/hy.austrian#holiday@group.v.calendar.google.comԱվստրիաAT
K
1hy.australian#holiday@group.v.calendar.google.comԱվստրալիաAU
=
)hy.aw#holiday@group.v.calendar.google.comԱրուբաAW
A
)hy.az#holiday@group.v.calendar.google.comԱդրբեջանAZ
W
)hy.ba#holiday@group.v.calendar.google.com&Բոսնիա և ՀերցեգովինաBA
A
)hy.bb#holiday@group.v.calendar.google.comԲարբադոսBB
C
)hy.bd#holiday@group.v.calendar.google.comԲանգլադեշBD
=
)hy.be#holiday@group.v.calendar.google.comԲելգիաBE
J
)hy.bf#holiday@group.v.calendar.google.comԲուրկինա ՖասոBF
J
0hy.bulgarian#holiday@group.v.calendar.google.comԲուլղարիաBG
?
)hy.bh#holiday@group.v.calendar.google.comԲահրեյնBH
C
)hy.bi#holiday@group.v.calendar.google.comԲուրունդիBI
;
)hy.bj#holiday@group.v.calendar.google.com
ԲենինBJ
E
)hy.bm#holiday@group.v.calendar.google.comԲերմուդներBM
?
)hy.bo#holiday@group.v.calendar.google.comԲոլիվիաBO
H
0hy.brazilian#holiday@group.v.calendar.google.comԲրազիլիաBR
C
)hy.bs#holiday@group.v.calendar.google.comԲահամաներBS
A
)hy.bw#holiday@group.v.calendar.google.comԲոթսվանաBW
A
)hy.by#holiday@group.v.calendar.google.comԲելառուսBY
C
/hy.canadian#holiday@group.v.calendar.google.comԿանադաCA
L
)hy.cd#holiday@group.v.calendar.google.comԿոնգո - ԿինշասաCD
w
)hy.cf#holiday@group.v.calendar.google.comFԿենտրոնական Աֆրիկյան ՀանրապետությունCF
N
)hy.cg#holiday@group.v.calendar.google.comԿոնգո - ԲրազավիլCG
C
)hy.ch#holiday@group.v.calendar.google.comՇվեյցարիաCH
I
)hy.ci#holiday@group.v.calendar.google.comԿոտ դ’ԻվուարCI
9
)hy.cl#holiday@group.v.calendar.google.comՉիլիCL
A
)hy.cm#holiday@group.v.calendar.google.comԿամերունCM
D
,hy.china#holiday@group.v.calendar.google.comՉինաստանCN
C
)hy.co#holiday@group.v.calendar.google.comԿոլումբիաCO
D
)hy.cr#holiday@group.v.calendar.google.comԿոստա ՌիկաCR
;
)hy.cu#holiday@group.v.calendar.google.com
ԿուբաCU
D
)hy.cv#holiday@group.v.calendar.google.comԿաբո ՎերդեCV
=
)hy.cy#holiday@group.v.calendar.google.comԿիպրոսCY
>
,hy.czech#holiday@group.v.calendar.google.com
ՉեխիաCZ
E
-hy.german#holiday@group.v.calendar.google.comԳերմանիաDE
?
-hy.danish#holiday@group.v.calendar.google.com
ԴանիաDK
d
)hy.do#holiday@group.v.calendar.google.com3Դոմինիկյան ՀանրապետությունDO
;
)hy.dz#holiday@group.v.calendar.google.com
ԱլժիրDZ
?
)hy.ec#holiday@group.v.calendar.google.comԷկվադորEC
?
)hy.ee#holiday@group.v.calendar.google.comԷստոնիաEE
?
)hy.eg#holiday@group.v.calendar.google.comԵգիպտոսEG
?
)hy.er#holiday@group.v.calendar.google.comԷրիթրեաER
B
,hy.spain#holiday@group.v.calendar.google.comԻսպանիաES
?
)hy.et#holiday@group.v.calendar.google.comԵթովպիաET
H
.hy.finnish#holiday@group.v.calendar.google.comՖինլանդիաFI
9
)hy.fj#holiday@group.v.calendar.google.comՖիջիFJ
P
)hy.fo#holiday@group.v.calendar.google.comՖարերյան կղզիներFO
C
-hy.french#holiday@group.v.calendar.google.comՖրանսիաFR
;
)hy.ga#holiday@group.v.calendar.google.com
ԳաբոնGA
\
)hy.uk#holiday@group.v.calendar.google.com+Միացյալ ԹագավորությունGB
?
)hy.gd#holiday@group.v.calendar.google.comԳրենադաGD
?
)hy.ge#holiday@group.v.calendar.google.comՎրաստանGE
9
)hy.gh#holiday@group.v.calendar.google.comԳանաGH
C
)hy.gi#holiday@group.v.calendar.google.comՋիբրալթարGI
E
)hy.gl#holiday@group.v.calendar.google.comԳրենլանդիաGL
=
)hy.gm#holiday@group.v.calendar.google.comԳամբիաGM
=
)hy.gn#holiday@group.v.calendar.google.comԳվինեաGN
X
)hy.gq#holiday@group.v.calendar.google.com'Հասարակածային ԳվինեաGQ
F
,hy.greek#holiday@group.v.calendar.google.comՀունաստանGR
C
)hy.gt#holiday@group.v.calendar.google.comԳվատեմալաGT
;
)hy.gu#holiday@group.v.calendar.google.com
ԳուամGU
L
)hy.gw#holiday@group.v.calendar.google.comԳվինեա-ԲիսսաուGW
F
0hy.hong_kong#holiday@group.v.calendar.google.comՀոնկոնգHK
C
)hy.hn#holiday@group.v.calendar.google.comՀոնդուրասHN
G
/hy.croatian#holiday@group.v.calendar.google.comԽորվաթիաHR
=
)hy.ht#holiday@group.v.calendar.google.comՀայիթիHT
J
0hy.hungarian#holiday@group.v.calendar.google.comՀունգարիաHU
K
1hy.indonesian#holiday@group.v.calendar.google.comԻնդոնեզիաID
D
,hy.irish#holiday@group.v.calendar.google.comԻռլանդիաIE
C
-hy.jewish#holiday@group.v.calendar.google.comԻսրայելIL
G
-hy.indian#holiday@group.v.calendar.google.comՀնդկաստանIN
9
)hy.iq#holiday@group.v.calendar.google.comԻրաքIQ
9
)hy.ir#holiday@group.v.calendar.google.comԻրանIR
A
)hy.is#holiday@group.v.calendar.google.comԻսլանդիաIS
B
.hy.italian#holiday@group.v.calendar.google.comԻտալիաIT
?
)hy.jm#holiday@group.v.calendar.google.comՃամայկաJM
A
)hy.jo#holiday@group.v.calendar.google.comՀորդանանJO
E
/hy.japanese#holiday@group.v.calendar.google.comՃապոնիաJP
;
)hy.ke#holiday@group.v.calendar.google.com
ՔենիաKE
A
)hy.kg#holiday@group.v.calendar.google.comՂրղզստանKG
?
)hy.kh#holiday@group.v.calendar.google.comԿամբոջաKH
P
)hy.km#holiday@group.v.calendar.google.comԿոմորյան կղզիներKM
R
)hy.kp#holiday@group.v.calendar.google.com!Հյուսիսային ԿորեաKP
W
2hy.south_korea#holiday@group.v.calendar.google.comՀարավային ԿորեաKR
?
)hy.kw#holiday@group.v.calendar.google.comՔուվեյթKW
R
)hy.ky#holiday@group.v.calendar.google.com!Կայմանյան կղզիներKY
C
)hy.kz#holiday@group.v.calendar.google.comՂազախստանKZ
?
)hy.lb#holiday@group.v.calendar.google.comԼիբանանLB
G
)hy.li#holiday@group.v.calendar.google.comԼիխտենշտեյնLI
B
)hy.lk#holiday@group.v.calendar.google.comՇրի ԼանկաLK
?
)hy.lr#holiday@group.v.calendar.google.comԼիբերիաLR
=
)hy.ls#holiday@group.v.calendar.google.comԼեսոտոLS
C
1hy.lithuanian#holiday@group.v.calendar.google.com
ԼիտվաLT
K
)hy.lu#holiday@group.v.calendar.google.comԼյուքսեմբուրգLU
B
.hy.latvian#holiday@group.v.calendar.google.comԼատվիաLV
;
)hy.ly#holiday@group.v.calendar.google.com
ԼիբիաLY
?
)hy.ma#holiday@group.v.calendar.google.comՄարոկկոMA
=
)hy.mc#holiday@group.v.calendar.google.comՄոնակոMC
?
)hy.md#holiday@group.v.calendar.google.comՄոլդովաMD
E
)hy.me#holiday@group.v.calendar.google.comՉեռնոգորիաME
E
)hy.mg#holiday@group.v.calendar.google.comՄադագասկարMG
C
)hy.mk#holiday@group.v.calendar.google.comՄակեդոնիաMK
9
)hy.ml#holiday@group.v.calendar.google.comՄալիML
A
)hy.mn#holiday@group.v.calendar.google.comՄոնղոլիաMN
;
)hy.mo#holiday@group.v.calendar.google.com
ՄակաոMO
C
)hy.mq#holiday@group.v.calendar.google.comՄարտինիկաMQ
;
)hy.mt#holiday@group.v.calendar.google.com
ՄալթաMT
C
)hy.mu#holiday@group.v.calendar.google.comՄավրիկիոսMU
=
)hy.mw#holiday@group.v.calendar.google.comՄալավիMW
D
.hy.mexican#holiday@group.v.calendar.google.comՄեքսիկաMX
G
/hy.malaysia#holiday@group.v.calendar.google.comՄալայզիաMY
A
)hy.mz#holiday@group.v.calendar.google.comՄոզամբիկMZ
?
)hy.na#holiday@group.v.calendar.google.comՆամիբիաNA
;
)hy.ne#holiday@group.v.calendar.google.com
ՆիգերNE
?
)hy.ng#holiday@group.v.calendar.google.comՆիգերիաNG
E
)hy.ni#holiday@group.v.calendar.google.comՆիկարագուաNI
L
,hy.dutch#holiday@group.v.calendar.google.comՆիդեռլանդներNL
H
0hy.norwegian#holiday@group.v.calendar.google.comՆորվեգիաNO
;
)hy.np#holiday@group.v.calendar.google.com
ՆեպալNP
Q
2hy.new_zealand#holiday@group.v.calendar.google.comՆոր ԶելանդիաNZ
9
)hy.om#holiday@group.v.calendar.google.comՕմանOM
=
)hy.pa#holiday@group.v.calendar.google.comՊանամաPA
;
)hy.pe#holiday@group.v.calendar.google.com
ՊերուPE
N
2hy.philippines#holiday@group.v.calendar.google.comՖիլիպիններPH
A
)hy.pk#holiday@group.v.calendar.google.comՊակիստանPK
E
-hy.polish#holiday@group.v.calendar.google.comԼեհաստանPL
H
)hy.pr#holiday@group.v.calendar.google.comՊուերտո ՌիկոPR
O
1hy.portuguese#holiday@group.v.calendar.google.comՊորտուգալիաPT
A
)hy.py#holiday@group.v.calendar.google.comՊարագվայPY
;
)hy.qa#holiday@group.v.calendar.google.com
ԿատարQA
C
)hy.re#holiday@group.v.calendar.google.comՌեյունիոնRE
G
/hy.romanian#holiday@group.v.calendar.google.comՌումինիաRO
=
)hy.rs#holiday@group.v.calendar.google.comՍերբիաRS
H
.hy.russian#holiday@group.v.calendar.google.comՌուսաստանRU
?
)hy.rw#holiday@group.v.calendar.google.comՌուանդաRW
X
3hy.saudiarabian#holiday@group.v.calendar.google.comՍաուդյան ԱրաբիաSA
C
)hy.sc#holiday@group.v.calendar.google.comՍեյշելներSC
=
)hy.sd#holiday@group.v.calendar.google.comՍուդանSD
B
.hy.swedish#holiday@group.v.calendar.google.comՇվեդիաSE
J
0hy.singapore#holiday@group.v.calendar.google.comՍինգապուրSG
S
)hy.sh#holiday@group.v.calendar.google.com"Սուրբ Հեղինեի կղզիSH
H
0hy.slovenian#holiday@group.v.calendar.google.comՍլովենիաSI
E
-hy.slovak#holiday@group.v.calendar.google.comՍլովակիաSK
F
)hy.sl#holiday@group.v.calendar.google.comՍիեռա ԼեոնեSL
D
)hy.sm#holiday@group.v.calendar.google.comՍան ՄարինոSM
?
)hy.sn#holiday@group.v.calendar.google.comՍենեգալSN
=
)hy.so#holiday@group.v.calendar.google.comՍոմալիSO
A
)hy.sr#holiday@group.v.calendar.google.comՍուրինամSR
P
)hy.ss#holiday@group.v.calendar.google.comՀարավային ՍուդանSS
T
)hy.st#holiday@group.v.calendar.google.com#Սան Տոմե և ՓրինսիպիST
A
)hy.sv#holiday@group.v.calendar.google.comՍալվադորSV
;
)hy.sy#holiday@group.v.calendar.google.com
ՍիրիաSY
C
)hy.sz#holiday@group.v.calendar.google.comՍվազիլենդSZ
7
)hy.td#holiday@group.v.calendar.google.comՉադTD
9
)hy.tg#holiday@group.v.calendar.google.comՏոգոTG
?
)hy.th#holiday@group.v.calendar.google.comԹայլանդTH
=
)hy.tn#holiday@group.v.calendar.google.comԹունիսTN
D
.hy.turkish#holiday@group.v.calendar.google.comԹուրքիաTR
Q
)hy.tt#holiday@group.v.calendar.google.com Տրինիդադ և ՏոբագոTT
A
-hy.taiwan#holiday@group.v.calendar.google.comԹայվանTW
A
)hy.tz#holiday@group.v.calendar.google.comՏանզանիաTZ
H
0hy.ukrainian#holiday@group.v.calendar.google.comՈւկրաինաUA
?
)hy.ug#holiday@group.v.calendar.google.comՈւգանդաUG
S
*hy.usa#holiday@group.v.calendar.google.com!Միացյալ ՆահանգներUS
C
)hy.uy#holiday@group.v.calendar.google.comՈւրուգվայUY
E
)hy.uz#holiday@group.v.calendar.google.comՈւզբեկստանUZ
?
)hy.va#holiday@group.v.calendar.google.comՎատիկանVA
E
)hy.ve#holiday@group.v.calendar.google.comՎենեսուելաVE
Y
)hy.vi#holiday@group.v.calendar.google.com(ԱՄՆ Վիրջինյան կղզիներVI
G
1hy.vietnamese#holiday@group.v.calendar.google.comՎիետնամVN
9
)hy.ye#holiday@group.v.calendar.google.comԵմենYE
;
)hy.yt#holiday@group.v.calendar.google.com
ՄայոտYT
j
)hy.sa#holiday@group.v.calendar.google.com9Հարավաֆրիկյան ՀանրապետությունZA
=
)hy.zm#holiday@group.v.calendar.google.comԶամբիաZM
A
)hy.zw#holiday@group.v.calendar.google.comԶիմբաբվեZWW
0hy.christian#holiday@group.v.calendar.google.com#Քրիստոնեական տոներY
.hy.judaism#holiday@group.v.calendar.google.com'Հրեական արձակուրդներQ
.hy.islamic#holiday@group.v.calendar.google.comՄահմեդական տոներ[
<hy.orthodox_christianity#holiday@group.v.calendar.google.comՈւղղափառ տոներhy_AM